import test from 'node:test';
import assert from 'node:assert/strict';
import {data,explore,attend,softmax,position} from '../src/lib/attention.mjs';
function close(a,b){if(Array.isArray(a)){assert.equal(a.length,b.length);a.forEach((v,i)=>close(v,b[i]));}else assert.ok(Math.abs(a-b)<1e-10,`${a} != ${b}`);}
test('worked attention and output projection match hand calculations',()=>{const r=explore(),a=1/(2+Math.exp(1/Math.sqrt(2)));close(r.heads[0].weights[2],[a,a,1-2*a,0]);close(r.heads[0].outputs[2],[a,a]);close(r.heads[1].outputs[2],[2/3,2/3]);close(r.projected[2],[a+1/3,a+1/3,2/3+a/2,2/3+a/2]);close(r.residual[2],r.projected[2].map((v,i)=>v+r.inputs[2][i]));});
test('all configurations normalize allowed keys and mix values within their bounds',()=>{for(const ending of ['fun','slow'])for(const p of ['none','sinusoidal'])for(const c of [false,true])for(const h of explore(ending,p,c).heads)for(let i=0;i<4;i++){close(h.weights[i].reduce((a,b)=>a+b,0),1);for(let j=0;j<4;j++){assert.ok(h.weights[i][j]>=0);if(c&&j>i){assert.equal(h.weights[i][j],0);assert.equal(h.masked[i][j],null);}}for(let d=0;d<2;d++){const vals=h.V.slice(0,c?i+1:4).map(v=>v[d]);assert.ok(h.outputs[i][d]>=Math.min(...vals)-1e-10&&h.outputs[i][d]<=Math.max(...vals)+1e-10);}}});
test('causal masking isolates earlier outputs from a future token replacement',()=>{for(const p of ['none','sinusoidal']){const a=explore('fun',p,true),b=explore('slow',p,true);close(a.residual.slice(0,3),b.residual.slice(0,3));assert.notDeepEqual(a.residual[3],b.residual[3]);const x=explore('fun',p,false),y=explore('slow',p,false);assert.notDeepEqual(x.projected[2],y.projected[2]);}});
test('diagonal visibility preserves first-token self attention',()=>{for(const h of explore().heads){close(h.weights[0],[1,0,0,0]);close(h.outputs[0],h.V[0]);}});
test('position-free unmasked attention is permutation equivariant',()=>{const x=explore().inputs,perm=[2,0,3,1];for(const h of data.heads){const a=attend(x,h,false),b=attend(perm.map(i=>x[i]),h,false);close(b.outputs,perm.map(i=>a.outputs[i]));close(b.weights,perm.map(i=>perm.map(j=>a.weights[i][j])));}});
test('sinusoidal encoding follows the stated zero-based formula',()=>{close(position(0),[0,1,0,1]);close(position(1),[Math.sin(1),Math.cos(1),Math.sin(.01),Math.cos(.01)]);const a=explore(),b=explore('fun','sinusoidal');assert.notDeepEqual(a.heads[0].weights,b.heads[0].weights);});
test('softmax is stable, ignores blocked scores, and rejects an empty visible set',()=>{close(softmax([1000,1000,null]),[.5,.5,0]);close(softmax([-1000,-1000,null]),[.5,.5,0]);assert.throws(()=>softmax([null,null]));});
test('reports serialize masks without infinity and validate public options',()=>{assert.equal(JSON.parse(JSON.stringify(explore())).heads[0].masked[0][1],null);for(const args of [['bad'],['fun','bad'],['fun','none',1]])assert.throws(()=>explore(...args));});
