import test from 'node:test';
import assert from 'node:assert/strict';
import {dataset,validateDataset,experiment,fitModel,sigmoid,logisticLoss,decide,feature} from '../src/lib/supervised-learning.mjs';
const near=(a,b,t=1e-10)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
test('regression fits the hand-derived solution and improves over its baseline on the example',()=>{const r=experiment();near(r.model.w,13/7);near(r.model.b,3);near(r.query.prediction,55/14);near(r.reports.train.model.mse,2/35);near(r.reports.validation.baseline.mse,8/3);assert.equal(r.reports.test,undefined);});
test('logistic loss is stable and fitted weights nearly zero the regularized gradient',()=>{near(sigmoid(0),.5);near(logisticLoss(Math.log(4),1),-Math.log(.8));for(const z of [-1000,1000])for(const y of [0,1])assert.ok(Number.isFinite(logisticLoss(z,y)));const rows=validateDataset().train;for(const strength of [0,.1,1]){const m=fitModel(rows,'classification',strength);const dw=rows.reduce((sum,r)=>sum+(sigmoid(m.w*feature(r.history_like_fraction)+m.b)-r.liked)*feature(r.history_like_fraction),0)/rows.length+strength*m.w;near(dw,0,1e-7);}});
test('changing a threshold leaves the fit and probability-sensitive loss unchanged',()=>{const a=experiment('classification',0,.75,.5),b=experiment('classification',0,.75,.9);assert.deepEqual(a.model,b.model);assert.equal(a.query.prediction,b.query.prediction);assert.deepEqual([a.query.predicted_class,b.query.predicted_class],[1,0]);assert.equal(a.reports.validation.model.log_loss,b.reports.validation.model.log_loss);assert.equal(decide(a.query.prediction,a.query.prediction),1);});
test('held-out records cannot influence fitted parameters or training metrics',()=>{const changed=structuredClone(dataset);changed.rows.slice(6).forEach(r=>{r.rating=5;r.liked=1-r.liked;r.history_like_fraction=.33;});for(const task of ['regression','classification']){const a=experiment(task),b=experiment(task,0,.75,.5,changed);assert.deepEqual(a.model,b.model);assert.deepEqual(a.reports.train,b.reports.train);assert.notDeepEqual(a.reports.validation,b.reports.validation);}});
test('regularization shrinks the weight; invalid and degenerate data fails explicitly',()=>{for(const task of ['regression','classification']){const ws=[0,.1,1].map(s=>Math.abs(experiment(task,s).model.w));assert.ok(ws[0]>ws[1]&&ws[1]>ws[2]);}for(const val of [null,NaN,Infinity,-1,2]){const d=structuredClone(dataset);d.rows[0].history_like_fraction=val;assert.throws(()=>experiment('regression',0,.75,.5,d));}const d=structuredClone(dataset);d.rows[6].viewer_id='V01';assert.throws(()=>validateDataset(d));assert.throws(()=>experiment('classification',0,.75,Infinity));const rows=structuredClone(validateDataset().train);rows.forEach(r=>r.history_like_fraction=.5);assert.throws(()=>fitModel(rows));assert.equal(fitModel(rows,'regression',1).w,0);});
