import {useState} from 'react';
import {data,defaults,runAgent} from '../lib/agents.mjs';
import '../styles/agents.css';
type Config={scenario:string;policy:string;maxTurns:number;maxTools:number;loopGuard:boolean};
export default function AgentLab(){
 const [config,setConfig]=useState<Config>({...defaults}),[step,setStep]=useState(0);
 const report=runAgent(config),frame=step?report.frames[step-1]:null,atEnd=step===report.frames.length;
 const status=atEnd?report.status:step?'running':'ready';
 function change(key:keyof Config,value:string|number|boolean){setConfig({...config,[key]:value});setStep(0);}
 function reset(){setConfig({...defaults});setStep(0);}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='chapter-32-agent-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab agent-lab" aria-labelledby="agent-title">
  <div className="lab-top"><span className="eyebrow">OBSERVE. CHOOSE. CHECK.</span><span className="lab-tag">Deterministic policies · no model loaded</span></div>
  <h3 id="agent-title">One goal. Watch the next decision.</h3><p>Find a calm adventure under 100 minutes with verified regional availability. Step through a complete simulated run; each control change starts again.</p>
  <div className="screen-only">
   <div className="agent-controls"><label htmlFor="agent-scenario">Environment scenario<select id="agent-scenario" value={config.scenario} onChange={e=>change('scenario',e.target.value)}>{data.scenarios.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label htmlFor="agent-policy">Decision policy<select id="agent-policy" value={config.policy} onChange={e=>change('policy',e.target.value)}>{data.policies.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label htmlFor="agent-maxTurns">Maximum decisions<select id="agent-maxTurns" value={config.maxTurns} onChange={e=>change('maxTurns',+e.target.value)}>{[2,3,4,6].map(n=><option key={n}>{n}</option>)}</select></label><label htmlFor="agent-maxTools">Maximum tool calls<select id="agent-maxTools" value={config.maxTools} onChange={e=>change('maxTools',+e.target.value)}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label></div>
   <label className="agent-toggle"><input id="agent-loopGuard" type="checkbox" checked={config.loopGuard} onChange={e=>change('loopGuard',e.target.checked)}/> Stop a repeated completed read against this fixed snapshot</label>
   <div className="agent-stepper"><button className="small-button" disabled={!step} onClick={()=>setStep(Math.max(0,step-1))}>Previous step</button><button className="primary-button" disabled={atEnd} onClick={()=>setStep(Math.min(report.frames.length,step+1))}>Next step</button><button className="small-button" disabled={atEnd} onClick={()=>setStep(report.frames.length)}>Run to end</button></div>
   <div className="agent-status" aria-live="polite"><p>Step <strong data-agent="step">{step}</strong> of {report.frames.length} · <strong data-agent="status">{status}</strong></p><p data-agent="answer">{atEnd?report.answer:frame?frame.observation:'Ready. No decision or tool call has been revealed yet.'}</p><p><strong data-agent="turns">{step}</strong> decisions shown · <strong data-agent="tools">{frame?.toolCalls||0}</strong> tool calls executed</p></div>
   {frame&&<article className="agent-decision"><span className="eyebrow">DECISION {frame.turn}</span><h4 data-agent="action">{frame.proposal.type==='tool'?frame.proposal.name:frame.proposal.type}</h4><p>{frame.proposal.summary}</p><p><strong>Observation:</strong> {frame.observation}</p><details className="workshop-detail"><summary>Inspect the proposal and current state</summary><pre>{JSON.stringify({proposal:frame.proposal,state:frame.state},null,2)}</pre></details></article>}
   <div className="agent-evidence"><h4>Evidence retained by the runner</h4><p data-agent="candidates">Candidates: {frame?.state.candidates.map((m:{id:string})=>m.id).join(', ')||'none yet'}.</p><p data-agent="checks">Availability: {frame&&Object.keys(frame.state.checks).length?Object.entries(frame.state.checks).map(([id,value])=>`${id} = ${value===null?'unknown':value?'available':'unavailable'}`).join('; '):'not checked'}.</p></div>
   <p className="lab-note">The forgetful policy deliberately ignores retained availability observations. The runner still keeps them for output verification and the display. Policy summaries are authored teaching text, not a real model's private reasoning.</p>
   {step>0&&<ol className="agent-trajectory" aria-label="Revealed decisions">{report.frames.slice(0,step).map((f:{turn:number;proposal:{type:string;name?:string};observation:string})=><li key={f.turn}><strong>{f.turn} · {f.proposal.name||f.proposal.type}</strong><span>{f.observation}</span></li>)}</ol>}
   <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset experiment</button><button className="small-button" onClick={download}>Download full agent report</button></div>
  </div>
  <div className="print-only"><p><strong>Worked run: the first candidate is unavailable.</strong> Adaptive policy, six-decision limit, four-tool limit, loop guard on.</p><table><thead><tr><th>Decision</th><th>Action</th><th>Observation or ending</th></tr></thead><tbody><tr><td>1</td><td>Search catalog</td><td>M001 and M003 match the metadata.</td></tr><tr><td>2</td><td>Check M001 in IN</td><td>Unavailable; retain this observation.</td></tr><tr><td>3</td><td>Check M003 in IN</td><td>Available; sufficient evidence now exists.</td></tr><tr><td>4</td><td>Propose final answer</td><td>Verified: Harbor Lights, 88 minutes.</td></tr></tbody></table><p><strong>Four decisions, three tool calls.</strong> With only three decisions allowed, the runner stops before the finish proposal. A forgetful policy repeats M001; the loop guard stops the repeat before executing it.</p></div>
  <noscript><p>Enable JavaScript for the step-through lab, or run the Python workbook and use the printed example.</p></noscript>
 </section>;
}
