import {useMemo,useState} from 'react';
import {defaults,evaluate} from '../lib/applied-systems.mjs';
import '../styles/applied-systems.css';
type Config={threshold:number;weight:number;k:number;forecast:string};
type Task='vision'|'recommendations'|'forecast';
const pct=(v:number|null)=>v===null?'Undefined':`${(v*100).toFixed(1)}%`;
export default function AppliedSystemsLab(){
 const [config,setConfig]=useState<Config>({...defaults}),[task,setTask]=useState<Task>('vision');
 const r=useMemo(()=>evaluate(config),[config]);
 function change(key:keyof Config,value:string|number){setConfig({...config,[key]:value});}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-39-applications-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const points=(key:'actual'|'prediction')=>r.forecast.rows.map((p,i)=>`${(48+i*86).toFixed(3)},${(175-p[key]).toFixed(3)}`).join(' ');
 return <section className="lab applied-lab" aria-labelledby="applied-title">
 <div className="lab-top"><span className="eyebrow">LOCATE. RANK. FORECAST.</span><span className="lab-tag">Three local experiments</span></div>
 <h3 id="applied-title">Same cinema. Three different tasks.</h3><p>Explore supplied detector outputs, authored movie signals, and simple forecasts. The data is fictional. No network or model calls run.</p>
 <div className="screen-only">
 <div className="applied-task-buttons" role="group" aria-label="Choose an application">{([['vision','Vision'],['recommendations','Recommendations'],['forecast','Forecasting']] as [Task,string][]).map(([id,label])=><button className="small-button" key={id} aria-pressed={task===id} onClick={()=>setTask(id)}>{label}</button>)}</div>
 <div hidden={task!=='vision'}>
 <div className="applied-controls"><label htmlFor="app-threshold">Keep predictions at or above this score<select id="app-threshold" value={config.threshold} onChange={e=>change('threshold',+e.target.value)}>{[.3,.6,.9].map(n=><option key={n} value={n}>{n.toFixed(1)}</option>)}</select></label></div>
 <p className="local-note">Four labeled posters in two frames. One class. Match at IoU ≥ 0.5, highest score first, at most once per truth object. No duplicate suppression is applied.</p>
 <div className="applied-stats" aria-live="polite"><div><span>TP / FP / FN</span><strong data-app="counts">{r.vision.tp} / {r.vision.fp} / {r.vision.fn}</strong><small>Found / extra / missed</small></div><div><span>Detection precision</span><strong data-app="vision-precision">{pct(r.vision.precision)}</strong><small>Correct among kept predictions</small></div><div><span>Detection recall</span><strong data-app="vision-recall">{pct(r.vision.recall)}</strong><small>Found among truth objects</small></div></div>
 <div className="applied-table" role="region" aria-label="Detection matches" tabIndex={0}><table><thead><tr><th>Prediction / frame</th><th>Score</th><th>IoU</th><th>Truth match / outcome</th></tr></thead><tbody>{r.vision.rows.map(p=><tr key={p.id}><td>{p.id} · {p.frame}<small>[{p.box.join(', ')}]</small></td><td>{p.score.toFixed(2)}</td><td>{p.iou.toFixed(3)}</td><td>{p.match??'None'}<small>{p.outcome}</small></td></tr>)}</tbody></table></div>
 <p className="local-note" data-app="missed">Missed truth objects: {r.vision.missed.join(', ')||'none'}. IoU shows the matched overlap, or the best overlap when unmatched. A high score can still be wrong.</p>
 </div>
 <div hidden={task!=='recommendations'}>
 <div className="applied-controls"><label htmlFor="app-weight">Content weight λ<select id="app-weight" value={config.weight} onChange={e=>change('weight',+e.target.value)}><option value="0">0 · collaborative-style score only</option><option value="0.5">0.5 · equal blend</option><option value="1">1 · content similarity only</option></select></label><label htmlFor="app-k">List size K<select id="app-k" value={config.k} onChange={e=>change('k',+e.target.value)}>{[2,3].map(n=><option key={n} value={n}>Top {n}</option>)}</select></label></div>
 <p className="local-note">Five eligible candidates; two marked relevant later. Moonlight Map is already watched; Distant Shore is unavailable. Both are excluded. Relevance labels never enter the score.</p>
 <div className="applied-stats" aria-live="polite"><div><span>Precision@{config.k}</span><strong data-app="rec-precision">{pct(r.recommendations.precision)}</strong><small>Relevant fraction of displayed list</small></div><div><span>Recall@{config.k}</span><strong data-app="rec-recall">{pct(r.recommendations.recall)}</strong><small>Coverage of the two relevant items</small></div><div><span>NDCG@{config.k}</span><strong data-app="ndcg">{r.recommendations.ndcg?.toFixed(6)??'Undefined'}</strong><small>Earlier relevant items count more</small></div></div>
 <div className="applied-table" role="region" aria-label="Ranked movie candidates" tabIndex={0}><table><thead><tr><th>Movie / rank</th><th>Content</th><th>Collaborative</th><th>Blend</th><th>Later relevance</th></tr></thead><tbody>{r.recommendations.rows.map((m,i)=><tr key={m.id} data-selected={m.selected}><td>{i+1}. {m.title}<small>{m.selected?'In displayed list':'Outside top K'} · {m.id}</small></td><td>{m.content.toFixed(2)}</td><td>{m.collaborative.toFixed(2)}</td><td>{m.score.toFixed(2)}</td><td>{m.relevant?'Relevant':'Not relevant'}</td></tr>)}</tbody></table></div>
 <p className="local-note">Scores are authored on comparable teaching scales. Ties use ascending movie ID. This is one viewer’s arithmetic example, not population evidence.</p>
 </div>
 <div hidden={task!=='forecast'}>
 <div className="applied-controls"><label htmlFor="app-forecast">One-day forecasting method<select id="app-forecast" value={config.forecast} onChange={e=>change('forecast',e.target.value)}><option value="last">Last observed value</option><option value="mean3">Mean of the last three days</option><option value="seasonal7">Same weekday last week</option></select></label></div>
 <p className="local-note">Seven rolling forecasts for days 15–21. Each is issued after the previous day’s count is observed. All source days must precede the forecast day.</p>
 <div className="applied-stats" aria-live="polite"><div><span>MAE</span><strong data-app="mae">{r.forecast.mae.toFixed(3)}</strong><small>Tickets per forecast, absolute error</small></div><div><span>RMSE</span><strong data-app="rmse">{r.forecast.rmse.toFixed(3)}</strong><small>Larger misses receive more weight</small></div><div><span>Horizon</span><strong>1 day</strong><small>A new origin for every forecast</small></div></div>
 <div className="applied-curve"><h4>Actual tickets and one-day predictions</h4><svg viewBox="0 0 600 215" role="img" aria-labelledby="app-curve-title app-curve-desc"><title id="app-curve-title">Ticket demand and rolling forecasts</title><desc id="app-curve-desc">Solid green is actual demand. Dashed gold is the chosen forecast. The table gives exact values and the observations each forecast uses.</desc>{[0,75,150].map(v=><g key={v}><line x1="48" y1={175-v} x2="564" y2={175-v} stroke="var(--line)"/><text x="40" y={179-v} textAnchor="end" fill="var(--muted)" fontSize="14">{v}</text></g>)}<polyline data-series="actual" fill="none" stroke="var(--accent)" strokeWidth="3" points={points('actual')}/><polyline data-series="prediction" fill="none" stroke="var(--gold)" strokeWidth="3" strokeDasharray="8 5" points={points('prediction')}/><text x="48" y="205" fill="var(--muted)" fontSize="14">Day 15</text><text x="564" y="205" textAnchor="end" fill="var(--muted)" fontSize="14">Day 21</text></svg><p className="local-note">Solid green: actual. Dashed gold: forecast. Counts are fictional.</p></div>
 <div className="applied-table" role="region" aria-label="Rolling forecast audit" tabIndex={0}><table><thead><tr><th>Predict day / origin</th><th>Source days</th><th>Forecast</th><th>Actual</th><th>Error</th></tr></thead><tbody>{r.forecast.rows.map(f=><tr key={f.day}><td>{f.day}<small>After day {f.origin}</small></td><td>{f.sourceDays.join(', ')}</td><td>{f.prediction.toFixed(3)}</td><td>{f.actual}</td><td>{f.error.toFixed(3)}</td></tr>)}</tbody></table></div>
 <p className="local-note">Error = actual − forecast; positive means underprediction. These point forecasts have no estimated uncertainty interval. Reusing this window to choose a method makes it development data.</p>
 </div>
 <div className="workshop-actions"><button className="small-button" onClick={()=>{setConfig({...defaults});setTask('vision');}}>Reset experiment</button><button className="small-button" onClick={download}>Download applications report</button></div>
 </div>
 <div className="print-only"><p><strong>Default settings:</strong> detector threshold 0.6; content weight 0.5; K = 2; seasonal-naive forecast with lag seven.</p><table><thead><tr><th>Experiment</th><th>Default result</th><th>Change to inspect</th></tr></thead><tbody><tr><td>Vision</td><td>3 TP, 2 FP, 1 FN. Precision 60%; recall 75%.</td><td>At threshold 0.9: 1 TP, 1 FP, 3 FN.</td></tr><tr><td>Recommendations</td><td>Precision/recall 0.5; NDCG 0.613147.</td><td>At K = 3: precision 2/3; recall 1; NDCG 0.919721.</td></tr><tr><td>Forecasting</td><td>MAE = RMSE = 5 tickets.</td><td>Last value: MAE 22.143; mean three: 31.905.</td></tr></tbody></table><p>Day 15’s seasonal forecast uses day 8: predicted 45, actual 50. This is rolling one-day evaluation, not a seven-day forecast issued once.</p></div>
 </section>;
}
