import {useMemo,useState} from 'react';
import {cnn,sequence,transfer} from '../lib/architectures.mjs';
const f=(x:number)=>x.toFixed(4);
function Grid({values,title,selected=-1,onSelect,highlight=[]}:{values:number[][];title:string;selected?:number;onSelect?:(index:number)=>void;highlight?:number[]}){
 return <div className="arch-grid-wrap"><p className="arch-grid-title">{title}</p><div className="arch-grid" style={{gridTemplateColumns:`repeat(${values[0].length},1fr)`}}>{values.flat().map((v,i)=>onSelect?<button key={i} type="button" className={selected===i?'selected':''} aria-pressed={selected===i} aria-label={`${title}, row ${Math.floor(i/values[0].length)+1}, column ${i%values[0].length+1}: ${v}`} onClick={()=>onSelect(i)}>{v}</button>:<span key={i} className={highlight.includes(i)?'highlighted':''}>{Number.isInteger(v)?v:f(v)}</span>)}</div></div>;
}
export default function ArchitectureLab(){
 const [mode,setMode]=useState('cnn'),[poster,setPoster]=useState('edge'),[filter,setFilter]=useState('vertical'),[stride,setStride]=useState(1),[padding,setPadding]=useState(0),[cell,setCell]=useState(0);
 const [history,setHistory]=useState('original'),[recurrent,setRecurrent]=useState(.5),[mask,setMask]=useState(true),[adapt,setAdapt]=useState('frozen');
 const c=useMemo(()=>cnn(poster,filter,stride,padding),[poster,filter,stride,padding]),s=useMemo(()=>sequence(history,recurrent,mask),[history,recurrent,mask]),t=useMemo(()=>transfer(adapt),[adapt]);
 const chosen=Math.min(cell,c.output.flat().length-1),row=Math.floor(chosen/c.output[0].length),column=chosen%c.output[0].length;
 const terms:{weight:number;value:number;index:number}[]=c.kernel.flatMap((line:number[],a:number)=>line.map((weight:number,b:number)=>{const r=row*stride+a-padding,col=column*stride+b-padding;return {weight,value:c.input[r]?.[col]??0,index:r>=0&&r<5&&col>=0&&col<5?r*5+col:-1};}));
 function reset(){setMode('cnn');setPoster('edge');setFilter('vertical');setStride(1);setPadding(0);setCell(0);setHistory('original');setRecurrent(.5);setMask(true);setAdapt('frozen');}
 function download(){const report=mode==='cnn'?{experiment:mode,...c,selected_cell:{row:row+1,column:column+1,terms}}:mode==='sequence'?{experiment:mode,...s}:{experiment:mode,...t};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-22-'+mode+'-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const printedSequence=sequence(),printedReverse=sequence('reversed'),printedTransfer=transfer(),printedFine=transfer('finetune');
 return <section className="lab architecture-lab" aria-label="Architecture arithmetic explorer">
  <div className="lab-top"><span className="eyebrow">SPACE. ORDER. REUSE.</span><span className="lab-tag">Three inspectable experiments</span></div>
  <h3>Same building blocks. Different structure.</h3><p>Slide a filter, carry a state, or choose which parameters may change. All fixtures and starting weights are hand-set; no pretrained model is loaded.</p>
  <div className="screen-only">
   <div className="arch-switcher" role="group" aria-label="Choose experiment">{[['cnn','1 · Poster filter'],['sequence','2 · Viewing history'],['transfer','3 · Freeze or adapt']].map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{label}</button>)}</div>
   {mode==='cnn'&&<div data-arch-panel="cnn">
    <div className="arch-controls"><label>Poster pattern<select id="arch-poster" value={poster} onChange={e=>{setPoster(e.target.value);setCell(0);}}><option value="edge">Bright left edge</option><option value="stripe">Vertical stripe</option><option value="cross">Cross</option></select></label><label>Filter<select id="arch-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="vertical">Vertical contrast</option><option value="horizontal">Horizontal contrast</option></select></label><label>Stride<select id="arch-stride" value={stride} onChange={e=>{setStride(Number(e.target.value));setCell(0);}}><option value="1">1 pixel</option><option value="2">2 pixels</option></select></label><label>Zero padding<select id="arch-padding" value={padding} onChange={e=>{setPadding(Number(e.target.value));setCell(0);}}><option value="0">None</option><option value="1">1 per side</option></select></label></div>
    <p className="lab-note">0 = dark, 1 = bright. Select an output cell to inspect its input patch. Highlighted input cells belong to that patch; out-of-image positions contribute zero.</p>
    <div className="arch-grids"><Grid title="Input · 5 × 5" values={c.input} highlight={terms.map(q=>q.index)}/><Grid title="Kernel · 3 × 3" values={c.kernel}/><Grid title="Raw output" values={c.output} selected={chosen} onSelect={setCell}/></div>
    <div className="arch-calculation" aria-live="polite"><strong data-arch="shape">Output: {c.output.length} × {c.output[0].length}</strong><p data-arch="sum">Cell ({row+1}, {column+1}): {terms.map(q=>`(${q.value} × ${q.weight})`).join(' + ')} = <b>{c.output[row][column]}</b></p><p>Bias = 0. ReLU keeps {Math.max(0,c.output[row][column])} for this cell.</p></div>
    <div className="arch-grids arch-grids-two"><Grid title="After ReLU" values={c.activation}/><Grid title="Max pool · 2 × 2, stride 2" values={c.pooled}/></div>
    <p className="arch-insight">Global average after ReLU: <strong data-arch="global">{f(c.global_mean)}</strong>. Max pooling drops any incomplete right/bottom window here. The filter has 9 weights + 1 bias = 10 parameters regardless of output size; these values are fixed in this experiment.</p>
   </div>}
   {mode==='sequence'&&<div data-arch-panel="sequence">
    <div className="arch-controls arch-controls-two"><label>Viewing order<select id="arch-history" value={history} onChange={e=>setHistory(e.target.value)}><option value="original">Adventure → Adventure → Romance</option><option value="reversed">Romance → Adventure → Adventure</option></select></label><label>Recurrent weight u<select id="arch-recurrent" value={recurrent} onChange={e=>setRecurrent(Number(e.target.value))}><option value="0">0 · no previous-state contribution</option><option value="0.5">0.5 · default</option><option value="1">1 · stronger contribution</option></select></label></div>
    <label className="arch-checkbox"><input id="arch-mask" type="checkbox" checked={mask} onChange={e=>setMask(e.target.checked)}/> Skip two padding positions using a mask</label>
    <p className="arch-equation">h₀ = 0 · hₜ = tanh(0.8xₜ + u hₜ₋₁)</p><p className="lab-note">Adventure = +1, romance = −1. These numbers encode watched genres, not likes/dislikes. A state is a signed internal value, not a probability.</p>
    <div className="arch-table" role="region" tabIndex={0} aria-label="Recurrent state trace"><table><thead><tr><th>Position</th><th>Input</th><th>Previous h</th><th>New h</th><th>Action</th></tr></thead><tbody>{s.steps.map(step=><tr key={step.step}><td>{step.step}</td><td>{step.padding?'PAD (0)':step.x===1?'Adventure (+1)':'Romance (−1)'}</td><td>{f(step.previous)}</td><td data-arch-step={step.step}>{f(step.state)}</td><td>{step.skipped?'Keep state':'Update'}</td></tr>)}</tbody></table></div>
    <div className="lab-metrics arch-metrics" aria-live="polite"><div><strong data-arch="mean">{f(s.mean)}</strong><span>Mean of real inputs</span></div><div><strong data-arch="real-final">{f(s.real_final)}</strong><span>After 3 real events</span></div><div><strong data-arch="final">{f(s.final)}</strong><span>After padding positions</span></div></div>
    <p className="arch-insight">{mask?'The mask preserves the state across padding. Reverse the history: the mean is unchanged, but the final state changes.':'Zero padding is being treated as two extra events. Even x = 0 changes the state through tanh(u h); zero alone is not a mask.'}</p>
   </div>}
   {mode==='transfer'&&<div data-arch-panel="transfer">
    <label>Update policy<select id="arch-adapt" value={adapt} onChange={e=>setAdapt(e.target.value)}><option value="frozen">Freeze backbone · train head only</option><option value="finetune">Adapt backbone and head</option></select></label>
    <p className="lab-note">Toy backbone: two inputs → two tanh features (6 parameters). Head: two features → one sigmoid (3 parameters). Authored movie features x = (0.8, 0.2), label = 1. One SGD step at rate 0.1 starts from the same weights each time.</p>
    <div className="lab-metrics arch-metrics" aria-live="polite"><div><strong data-arch="trainable">{t.trainable_count} / 9</strong><span>Trainable parameters</span></div><div><strong data-arch="loss-before">{f(t.before.loss)}</strong><span>Example loss before</span></div><div><strong data-arch="loss-after">{f(t.after.loss)}</strong><span>Example loss after</span></div></div>
    <div className="arch-table" role="region" tabIndex={0} aria-label="Parameter update trace"><table><thead><tr><th>Parameter</th><th>Before</th><th>After</th><th>May update?</th></tr></thead><tbody>{t.before_theta.map((v,i)=><tr key={i}><th>{['Backbone w₁₁','Backbone w₁₂','Backbone b₁','Backbone w₂₁','Backbone w₂₂','Backbone b₂','Head v₁','Head v₂','Head bias'][i]}</th><td>{f(v)}</td><td data-arch-param={i}>{f(t.after_theta[i])}</td><td>{t.trainable[i]?'Yes':'Frozen'}</td></tr>)}</tbody></table></div>
    <p className="arch-insight">Largest backbone change: <strong data-arch="delta">{f(t.backbone_change)}</strong>. {adapt==='frozen'?'The representation stays fixed; only the head learns.':'The representation and head both change.'} This demonstrates the update boundary with hand-set weights. One-example loss does not show that transfer improves generalization.</p>
   </div>}
   <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset experiments</button><button className="small-button" onClick={download}>Download calculation report</button></div>
  </div>
  <div className="print-only">
   <p><strong>Poster filter:</strong> for the bright-left pattern and vertical filter, stride 1 and no padding, the raw output has three identical rows [3, 3, 0]. ReLU leaves it unchanged. A 2 × 2 max pool with stride 2 returns [3]; global average pooling returns 2.</p>
   <table><thead><tr><th>Viewing order · u = 0.5</th><th>Input mean</th><th>Last real state</th></tr></thead><tbody><tr><td>Adventure → Adventure → Romance</td><td>{f(printedSequence.mean)}</td><td>{f(printedSequence.real_final)}</td></tr><tr><td>Romance → Adventure → Adventure</td><td>{f(printedReverse.mean)}</td><td>{f(printedReverse.real_final)}</td></tr></tbody></table>
   <p>Masking the two padding positions preserves the final real state. Without a mask, the original history ends at {f(sequence('original',.5,false).final)} instead of {f(printedSequence.final)}.</p>
   <table><thead><tr><th>One-step update policy</th><th>Trainable</th><th>Loss before</th><th>Loss after</th></tr></thead><tbody><tr><td>Frozen backbone</td><td>3 / 9</td><td>{f(printedTransfer.before.loss)}</td><td>{f(printedTransfer.after.loss)}</td></tr><tr><td>Adapt all parameters</td><td>9 / 9</td><td>{f(printedFine.before.loss)}</td><td>{f(printedFine.after.loss)}</td></tr></tbody></table>
   <p>The largest backbone change is 0 when frozen and {f(printedFine.backbone_change)} when adapted. The head's first update is identical in both modes because it uses the same starting features. These are local arithmetic results, not a pretrained-model benchmark.</p>
  </div>
 </section>;
}
