import {useMemo,useState} from 'react';
import {data,explore} from '../lib/attention.mjs';
import '../styles/attention.css';
const f=(x:number)=>x.toFixed(4),vec=(row:number[])=>'['+row.map(f).join(', ')+']',pct=(x:number)=>(100*x).toFixed(2)+'%';
export default function AttentionLab(){
 const [ending,setEnding]=useState('fun'),[positions,setPositions]=useState('none'),[causal,setCausal]=useState(true),[head,setHead]=useState(0),[query,setQuery]=useState(2),[source,setSource]=useState(1);
 const r=useMemo(()=>explore(ending,positions,causal),[ending,positions,causal]),h=r.heads[head],printed=explore();
 const contributions=h.V.map((v,j)=>v.map(x=>x*h.weights[query][j]));
 function reset(){setEnding('fun');setPositions('none');setCausal(true);setHead(0);setQuery(2);setSource(1);}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-24-attention-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab attention-lab" aria-label="Attention calculation explorer">
  <div className="lab-top"><span className="eyebrow">COMPARE. WEIGHT. COMBINE.</span><span className="lab-tag">Hand-set vectors · exact arithmetic</span></div>
  <h3>Same words. Different connections.</h3><p>Inspect one attention sublayer with two heads. All embeddings and projection matrices are hand-set for teaching; no model is trained.</p>
  <div className="screen-only">
   <div className="att-controls"><label>Last word<select id="att-ending" value={ending} onChange={e=>setEnding(e.target.value)}><option value="fun">this movie is fun</option><option value="slow">this movie is slow</option></select></label><label>Position information<select id="att-positions" value={positions} onChange={e=>setPositions(e.target.value)}><option value="none">None</option><option value="sinusoidal">Sinusoidal vectors</option></select></label><label>Attention head<select id="att-head" value={head} onChange={e=>setHead(Number(e.target.value))}><option value="0">Head 1</option><option value="1">Head 2</option></select></label></div>
   <label className="att-checkbox"><input id="att-causal" type="checkbox" checked={causal} onChange={e=>setCausal(e.target.checked)}/><span>Causal mask: each query sees itself and earlier positions.</span></label>
   <p className="att-insight" data-att="visibility">{causal?'Future keys are blocked before softmax. Changing the last word cannot alter an earlier row.':'Bidirectional attention sees all four positions. This is useful for encoder representations; it would expose future targets in shifted next-token training.'}</p>
   <p className="att-grid-help">Rows = querying positions. Columns = source positions. Select any cell to inspect its calculation. Numbers are mixing weights over positions, not next-word probabilities.</p>
   <div className="att-matrix" role="region" aria-label="Attention weights matrix" tabIndex={0}>
    <table><thead><tr><th scope="col">Query ↓<br/>Source →</th>{r.tokens.map((t,j)=><th key={j} scope="col">{j+1} · {t}</th>)}</tr></thead><tbody>{r.tokens.map((t,i)=><tr key={i} className={query===i?'att-selected-row':''}><th scope="row">{i+1} · {t}</th>{r.tokens.map((s,j)=><td key={j}><button data-att-cell={`${i}-${j}`} className={causal&&j>i?'att-blocked':''} aria-pressed={query===i&&source===j} aria-label={`Query ${i+1} ${t}, source ${j+1} ${s}: ${causal&&j>i?'blocked':pct(h.weights[i][j])}`} onClick={()=>{setQuery(i);setSource(j);}}><span className="att-cell-fill" aria-hidden="true" style={{opacity:h.weights[i][j]}}/><span>{causal&&j>i?'Blocked':pct(h.weights[i][j])}</span></button></td>)}</tr>)}</tbody></table>
   </div>
   <div className="att-calculation" aria-live="polite"><span className="eyebrow">SELECTED PAIR · {r.tokens[query]} → {r.tokens[source]}</span><p>Query q = <code data-att="q">{vec(h.Q[query])}</code><br/>Key k = <code data-att="k">{vec(h.K[source])}</code></p><p>Dot product = <strong data-att="dot">{f(h.raw[query][source])}</strong> · Divide by √2 = <strong data-att="scaled">{f(h.scaled[query][source])}</strong></p><p>After mask: <strong data-att="masked">{h.masked[query][source]===null?'−∞ (blocked)':f(h.masked[query][source])}</strong> · Row softmax weight: <strong data-att="weight">{pct(h.weights[query][source])}</strong></p></div>
   <h4>Combine values for “{r.tokens[query]}”</h4><div className="att-table" role="region" aria-label="Weighted value contributions" tabIndex={0}><table><thead><tr><th>Source</th><th>Weight</th><th>Value vector</th><th>Contribution</th></tr></thead><tbody>{r.tokens.map((t,j)=><tr key={j}><th>{t}</th><td>{pct(h.weights[query][j])}</td><td>{vec(h.V[j])}</td><td data-att-contribution={j}>{vec(contributions[j])}</td></tr>)}</tbody></table></div>
   <p className="att-result">Sum of contributions = <strong data-att="output">{vec(h.outputs[query])}</strong></p><p className="lab-note">Each row's weights sum to 1 before dropout; this experiment has no dropout. The result is a feature vector, so negative coordinates are allowed when source values contain them.</p>
   <details className="workshop-detail att-combine"><summary>Follow both heads and the residual connection</summary><div className="att-flow"><p>Head 1: <code>{vec(r.heads[0].outputs[query])}</code><br/>Head 2: <code>{vec(r.heads[1].outputs[query])}</code></p><p>Concatenate → <code data-att="concat">{vec(r.concatenated[query])}</code></p><p>Multiply by W<sub>O</sub> → <code data-att="projected">{vec(r.projected[query])}</code></p><p>Add input X → <code data-att="residual">{vec(r.residual[query])}</code></p></div><p className="lab-note">Switching the displayed head changes the inspection view only; both heads are always computed. This arithmetic example omits normalization, the feed-forward network, and the vocabulary head. It is not a complete transformer block.</p></details>
   <details className="workshop-detail att-vectors"><summary>Inspect inputs, Q, K, V, and the fixed matrices</summary><div className="att-table att-wide" role="region" aria-label="Input and projected vectors" tabIndex={0}><table><thead><tr><th>Token</th><th>Embedding + position = X</th><th>Q</th><th>K</th><th>V</th></tr></thead><tbody>{r.tokens.map((t,i)=><tr key={i}><th>{i+1} · {t}</th><td>{vec(r.inputs[i])}</td><td>{vec(h.Q[i])}</td><td>{vec(h.K[i])}</td><td>{vec(h.V[i])}</td></tr>)}</tbody></table></div><p className="lab-note">Rows are tokens. Matrices multiply on the right: Q = XWq, K = XWk, V = XWv. Sinusoidal positions use indices 0–3 and are added without embedding scaling. All coordinates are illustrative, without assigned linguistic meanings.</p><pre aria-label="Fixed attention matrices"><code>{JSON.stringify({head:data.heads[head],Wo:data.Wo},null,2)}</code></pre></details>
   <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset experiment</button><button className="small-button" onClick={download}>Download calculation report</button></div>
  </div>
  <div className="print-only"><p>Default: <strong>this movie is fun</strong>, no positional vectors, causal masking, Head 1. At the third input “is”, q = [1, 1]. The four raw dot products are [1, 1, 2, 1]; divide by √2 and block the fourth key before softmax.</p><table><thead><tr><th>Source</th><th>Weight</th><th>Value</th><th>Weighted value</th></tr></thead><tbody>{printed.tokens.map((t,j)=><tr key={j}><td>{t}</td><td>{f(printed.heads[0].weights[2][j])}</td><td>{vec(printed.heads[0].V[j])}</td><td>{vec(printed.heads[0].V[j].map(x=>x*printed.heads[0].weights[2][j]))}</td></tr>)}</tbody></table><p>Head 1 output = <strong>{vec(printed.heads[0].outputs[2])}</strong>. Head 2 gives equal weight to the three visible keys and outputs [0.6667, 0.6667]. Concatenate both heads, multiply by the supplied W<sub>O</sub>, and add X to obtain <strong>{vec(printed.residual[2])}</strong>.</p><p>Replacing “fun” with “slow” cannot change these earlier outputs when causal masking is enabled. The workbook reproduces both heads and all positions. This is attention arithmetic, not a trained transformer or a vocabulary prediction.</p></div>
 </section>;
}
