import {useMemo,useState} from 'react';
import {defaults,evaluate} from '../lib/connections.mjs';
import '../styles/connections.css';
type Config={steps:number;topology:string;allocation:string;targetHigh:number;strategy:string;budget:number};
type Task='graph'|'causal'|'active';
type CausalRow={group:string;withY:number;withN:number;withoutY:number;withoutN:number;withRate:number;withoutRate:number;difference:number;weight:number};
const pct=(v:number)=>`${(v*100).toFixed(1)}%`;
const pp=(v:number)=>`${v>0?'+':''}${(v*100).toFixed(1)} pp`;
export default function ConnectionsLab(){
 const [config,setConfig]=useState<Config>({...defaults}),[task,setTask]=useState<Task>('graph');
 const r=useMemo(()=>evaluate(config),[config]);
 function change(key:keyof Config,value:string|number){setConfig({...config,[key]:value});}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-40-connections-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const positions:Record<string,number>={A:65,B:200,C:335,D:470,E:620};
 return <section className="lab connections-lab" aria-labelledby="connections-title">
 <div className="lab-top"><span className="eyebrow">CONNECT. COMPARE. QUERY.</span><span className="lab-tag">Three local experiments</span></div>
 <h3 id="connections-title">What changes when the connections change?</h3><p>Follow information through movie relationships, compare banner outcomes, and choose reviews to label. All data and predictions are fictional.</p>
 <div className="screen-only">
 <div className="connections-task-buttons" role="group" aria-label="Choose an experiment">{([['graph','Graphs'],['causal','Causality'],['active','Label queries']] as [Task,string][]).map(([id,label])=><button className="small-button" key={id} aria-pressed={task===id} onClick={()=>setTask(id)}>{label}</button>)}</div>
 <div hidden={task!=='graph'}>
 <div className="connections-controls"><label htmlFor="conn-steps">Message-passing rounds<select id="conn-steps" value={config.steps} onChange={e=>change('steps',+e.target.value)}>{[0,1,3].map(n=><option key={n} value={n}>{n} {n===1?'round':'rounds'}</option>)}</select></label><label htmlFor="conn-topology">Movie connections<select id="conn-topology" value={config.topology} onChange={e=>change('topology',e.target.value)}><option value="chain">Chain A–B–C–D; E isolated</option><option value="shortcut">Add shortcut A–D; E isolated</option></select></label></div>
 <p className="local-note">Each round: half the old value + half the old neighbors’ mean. Updates are simultaneous. Values are features, not probabilities; no weights are trained.</p>
 <div className="connections-stats" aria-live="polite"><div><span>Completed rounds</span><strong data-conn="rounds">{config.steps}</strong><small>Each uses the previous snapshot</small></div><div><span>D’s final feature</span><strong data-conn="d-value">{r.graph.rows.find(n=>n.id==='D')!.final.toFixed(6)}</strong><small>Watch how A reaches D</small></div><div><span>Isolated E’s feature</span><strong data-conn="e-value">{r.graph.rows.find(n=>n.id==='E')!.final.toFixed(6)}</strong><small>No neighbors to aggregate</small></div></div>
 <div className="connections-network" role="region" aria-label="Current movie graph" tabIndex={0}><svg viewBox="0 0 690 190" role="img" aria-labelledby="conn-network-title conn-network-desc"><title id="conn-network-title">{`Movie graph after ${config.steps} rounds`}</title><desc id="conn-network-desc">{(config.topology==='chain'?'A, B, C, and D form a chain.':'A, B, C, and D form a cycle with shortcut A–D.')+' E is isolated. Feature values are also listed in the table.'}</desc>{r.graph.edges.map(([a,b])=>a==='A'&&b==='D'?<path key={a+b} d="M65 66 Q267 -12 470 66" fill="none" stroke="var(--gold)" strokeWidth="2" strokeDasharray="6 4"/>:<line key={a+b} x1={positions[a]} y1="85" x2={positions[b]} y2="85" stroke="var(--accent)" strokeWidth="2"/>)}{r.graph.rows.map(n=><g key={n.id}><circle cx={positions[n.id]} cy="85" r="25" fill="var(--panel)" stroke="var(--accent)" strokeWidth="2"/><text x={positions[n.id]} y="91" textAnchor="middle" fill="var(--ink)" fontSize="18">{n.id}</text><text x={positions[n.id]} y="143" textAnchor="middle" fill="var(--ink)" fontSize="16">{n.final.toFixed(3)}</text></g>)}</svg></div>
 <div className="connections-table" role="region" aria-label="Movie feature updates" tabIndex={0}><table><thead><tr><th>Movie</th><th>Neighbors</th><th>Initial</th><th>Final</th></tr></thead><tbody>{r.graph.rows.map(n=><tr key={n.id}><td>{n.id} · {n.title}</td><td>{n.neighbors.join(', ')||'None'}</td><td>{n.value.toFixed(3)}</td><td>{n.final.toFixed(6)}</td></tr>)}</tbody></table></div>
 <details className="connections-trace"><summary>Inspect the round-by-round values</summary><div className="connections-table" role="region" aria-label="Propagation history" tabIndex={0}><table><thead><tr><th>Round</th>{['A','B','C','D','E'].map(id=><th key={id}>{id}</th>)}</tr></thead><tbody>{r.graph.history.map(h=><tr key={h.step}><td>{h.step}</td>{['A','B','C','D','E'].map(id=><td key={id}>{h.values[id].toFixed(6)}</td>)}</tr>)}</tbody></table></div></details>
 </div>
 <div hidden={task!=='causal'}>
 <div className="connections-controls"><label htmlFor="conn-allocation">Observed viewer counts<select id="conn-allocation" value={config.allocation} onChange={e=>change('allocation',e.target.value)}><option value="unbalanced">Unbalanced toy table</option><option value="balanced">Balanced toy table</option></select></label><label htmlFor="conn-target">High-interest share of target audience<select id="conn-target" value={config.targetHigh} onChange={e=>change('targetHigh',+e.target.value)}>{[.25,.5,.75].map(n=><option key={n} value={n}>{n*100}% high / {(1-n)*100}% low</option>)}</select></label></div>
 <p className="local-note">Outcome: starts watching. The two tables have the same within-group rates but different group counts. Balanced counts alone do not establish random assignment.</p>
 <div className="connections-stats" aria-live="polite"><div><span>Pooled contrast</span><strong data-conn="crude">{pp(r.causal.crudeDifference)}</strong><small>Observed with − without banner</small></div><div><span>Standardized contrast</span><strong data-conn="adjusted">{pp(r.causal.adjustedDifference)}</strong><small>Both rates use the target weights</small></div><div><span>Target rates: with / without</span><strong data-conn="target-rates">{pct(r.causal.adjustedWith)} / {pct(r.causal.adjustedWithout)}</strong><small>pp means percentage points</small></div></div>
 <div className="connections-table" role="region" aria-label="Banner outcome groups" tabIndex={0}><table><thead><tr><th>Prior interest</th><th>With banner</th><th>Without banner</th><th>Group contrast</th><th>Target weight</th></tr></thead><tbody>{r.causal.rows.map((g:CausalRow)=><tr key={g.group}><td>{g.group}</td><td>{g.withY} / {g.withN}<small>{pct(g.withRate)}</small></td><td>{g.withoutY} / {g.withoutN}<small>{pct(g.withoutRate)}</small></td><td>{pp(g.difference)}</td><td>{pct(g.weight)}</td></tr>)}</tbody></table></div>
 <p className="local-note" data-conn="pooled-rates">Pooled rates: {pct(r.causal.crudeWith)} with banner; {pct(r.causal.crudeWithout)} without banner. Each uses its own observed group mixture.</p>
 <p className="local-note"><strong>Interpretation limit:</strong> adjustment becomes a causal effect estimate only under the assumptions explained above, including sufficient confounder adjustment, overlap, and a well-defined treatment. This arithmetic demonstration provides no uncertainty interval.</p>
 </div>
 <div hidden={task!=='active'}>
 <div className="connections-controls"><label htmlFor="conn-strategy">Which reviews to query<select id="conn-strategy" value={config.strategy} onChange={e=>change('strategy',e.target.value)}><option value="uncertain">Most uncertain first</option><option value="confident">Most confident first · comparison</option></select></label><label htmlFor="conn-budget">Annotation budget<select id="conn-budget" value={config.budget} onChange={e=>change('budget',+e.target.value)}>{[1,2].map(n=><option key={n} value={n}>{n} {n===1?'review':'reviews'}</option>)}</select></label></div>
 <p className="local-note">p is an authored prediction of positive sentiment. Select using entropy, then reveal a supplied annotation only for queried reviews. This is one selection round; no model is retrained.</p>
 <div className="connections-stats" aria-live="polite"><div><span>Selected reviews</span><strong data-conn="selected">{r.active.selected.join(', ')}</strong><small>Annotations are excluded from ranking</small></div><div><span>Labels requested</span><strong data-conn="requested">{r.active.labelsRequested}</strong><small>Your chosen annotation budget</small></div><div><span>Mean selected entropy</span><strong data-conn="entropy">{r.active.meanEntropy.toFixed(6)}</strong><small>Bits, not an accuracy score</small></div></div>
 <div className="connections-table" role="region" aria-label="Review annotation queries" tabIndex={0}><table><thead><tr><th>Review / query status</th><th>p(positive)</th><th>Entropy</th><th>Revealed annotation</th></tr></thead><tbody>{r.active.rows.map(q=><tr key={q.id} data-selected={q.selected}><td>{q.id} · {q.text}<small>{q.selected?'Queried':'Not queried'}</small></td><td>{q.p.toFixed(2)}</td><td>{q.entropy.toFixed(6)}</td><td>{q.annotation===null?'Hidden':q.annotation===1?'Positive (1)':'Negative (0)'}</td></tr>)}</tbody></table></div>
 <p className="local-note">Rank by six-decimal entropy, then ascending review ID for ties. Confidence can be wrong: the sarcastic R5 is predicted positive with p = 0.99. Evaluate learning gains only after annotation, training, and a separate evaluation.</p>
 </div>
 <div className="workshop-actions"><button className="small-button" onClick={()=>{setConfig({...defaults});setTask('graph');}}>Reset experiment</button><button className="small-button" onClick={download}>Download connections report</button></div>
 </div>
 <div className="print-only"><p><strong>Default settings:</strong> one round on the chain; unbalanced banner counts; a 50/50 target audience; query the two most uncertain reviews.</p><table><thead><tr><th>Experiment</th><th>Default result</th><th>Change to inspect</th></tr></thead><tbody><tr><td>Graph</td><td>A = 0.5; B = 0.25; C = D = 0; E = 0.4.</td><td>Add A–D: D becomes 0.25 after one round.</td></tr><tr><td>Banner</td><td>Pooled contrast +26 pp; standardized contrast −10 pp.</td><td>Balanced table: pooled contrast also becomes −10 pp.</td></tr><tr><td>Label queries</td><td>R1 and R2; mean entropy 0.996387 bits.</td><td>Confident first selects R5 and R6; it does not prove better learning.</td></tr></tbody></table><p>Graph values are fixed features. Standardization needs assumptions for a causal interpretation. Query selection alone does not train a model.</p></div>
 </section>;
}


