import {useState} from 'react';
import {prepareData} from '../lib/data-preparation.mjs';
const baseline=prepareData();
const comparison=[['median','train'],['mean','train'],['median','all'],['mean','all']].map(([strategy,scope])=>prepareData(strategy,scope));
const format=(value:number)=>Number.isInteger(value)?String(value):value.toFixed(4);
export default function DataPreparationLab(){
  const [strategy,setStrategy]=useState('median');const [scope,setScope]=useState('train');const [eventId,setEventId]=useState('E04');
  const result=prepareData(strategy,scope);
  const rows=Object.entries(result.splits).flatMap(([split,items])=>items.map(row=>({...row,split})));
  const selected=rows.find(row=>row.event_id===eventId)!;
  const prepared=result.prepared[selected.split];const vector=prepared.X[prepared.event_ids.indexOf(eventId)];
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=scope==='all'?'chapter-12-leakage-demo.json':'chapter-12-prepared-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="lab data-prep" aria-label="Data preparation workbench">
    <div className="lab-top"><span className="eyebrow">FROM RAW ROWS TO MODEL INPUTS</span><span className="lab-tag">Real calculations · synthetic data</span></div>
    <h3>Same rows. Different preparation.</h3><p>13 raw records become 10 labeled events: one duplicate, one invalid runtime, and one missing label are kept out of the training table. No predictive model runs here.</p>
    <div className="screen-only">
      <div className="training-controls"><label htmlFor="prep-strategy">Fill missing runtimes with<select id="prep-strategy" value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="median">Median</option><option value="mean">Mean</option></select></label><label htmlFor="prep-scope">Learn preprocessing from<select id="prep-scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="train">Training rows only · correct</option><option value="all">All splits · leakage demonstration</option></select></label></div>
      <div className={'prep-notice'+(scope==='all'?' prep-leaky':'')} role="status" data-prep="notice">{scope==='train'?'Fit on 6 training events. Reuse those values on 2 validation and 2 test events.':'Deliberately leaky: validation and test events influence the fill value, scaling, and genre vocabulary. Use this only as a comparison.'}</div>
      <div className="lab-metrics prep-metrics" aria-live="polite"><div><strong data-prep="fill">{format(result.state.fill_value)}</strong><span>Missing-value fill (minutes)</span></div><div><strong data-prep="mean">{format(result.state.runtime_mean)}</strong><span>Mean after filling</span></div><div><strong data-prep="columns">{result.state.feature_names.length}</strong><span>Feature columns</span></div></div>
      <label className="workshop-label" htmlFor="prep-event">Inspect one event<select id="prep-event" value={eventId} onChange={e=>setEventId(e.target.value)}>{rows.map(row=><option key={row.event_id} value={row.event_id}>{row.event_id} · {row.split} · {row.genre}{row.runtime_minutes===null?' · runtime missing':''}</option>)}</select></label>
      <div className="prep-vector" aria-live="polite"><p data-prep="row"><strong>{selected.event_id}:</strong> raw runtime {selected.runtime_minutes??'missing'}, genre {selected.genre}. Label <code>y = {selected.liked}</code> stays outside the input vector.</p><dl className="prep-features">{result.state.feature_names.map((name,i)=><div key={name}><dt>{name}</dt><dd data-feature={name}>{format(vector[i])}</dd></div>)}</dl><p className="local-note">runtime_z = (filled runtime − {format(result.state.runtime_mean)}) / {format(result.state.runtime_scale)}. A missing-value flag preserves the original absence.</p></div>
      <div className="workshop-actions"><button className="small-button" onClick={()=>{setStrategy('median');setScope('train');setEventId('E04');}}>Reset preparation</button><button className="small-button" onClick={download}>{scope==='all'?'Download leakage comparison':'Download prepared data'}</button></div>
      <details className="workshop-detail"><summary>Inspect the cleaning audit and split membership</summary><p>One copy of E03 was removed. Input row 12 (E11) has a negative runtime and is quarantined. E12 has no label; it is excluded from supervised examples, not relabeled as 0.</p><div className="prep-table-wrap" tabIndex={0} role="region" aria-label="Cleaned movie-viewing records"><table><thead><tr><th>Event</th><th>Viewer</th><th>Split</th><th>Runtime</th><th>Genre</th><th>Label</th></tr></thead><tbody>{rows.map(row=><tr key={row.event_id}><td>{row.event_id}</td><td>{row.viewer_id}</td><td>{row.split}</td><td>{row.runtime_minutes??'missing'}</td><td>{row.genre}</td><td>{row.liked}</td></tr>)}</tbody></table></div><p>All events from a viewer stay together. Viewer IDs and after-watch reviews are not feature columns.</p></details>
    </div>
    <div className="print-only"><p><strong>Group split:</strong> U01–U03 supply 6 training events; U04 supplies 2 validation events; U05 supplies 2 test events.</p><table><thead><tr><th>Strategy</th><th>Fit scope</th><th>Fill</th><th>Scaling mean</th><th>Columns</th></tr></thead><tbody>{comparison.map(run=><tr key={run.state.strategy+run.fit_scope}><td>{run.state.strategy}</td><td>{run.fit_scope==='train'?'Train only':'All (leaky)'}</td><td>{format(run.state.fill_value)}</td><td>{format(run.state.runtime_mean)}</td><td>{run.state.feature_names.length}</td></tr>)}</tbody></table><p>Default E04: missing runtime becomes 110, then runtime_z ≈ −0.1118. The missing flag is 1, the sci-fi column is 1, and other genre columns are 0. E07's documentary genre uses the unknown bucket under the training-only vocabulary.</p><p>The prepared training matrix has {baseline.prepared.train.X.length} rows and {baseline.state.feature_names.length} columns. Validation and test each have 2 rows with those same columns. The all-splits modes intentionally demonstrate leakage; no performance score is measured.</p></div>
    <noscript><p>Enable JavaScript for the workbench, or use the PDF and Python workbook.</p></noscript>
  </section>;
}
