import {useMemo,useState} from 'react';
import {data,memory,compression} from '../lib/llm-efficiency.mjs';
import '../styles/efficiency.css';
const f=(x:number)=>x.toFixed(4),signed=(x:number)=>(x>=0?'+':'')+f(x);
export default function EfficiencyLab(){
 const [panel,setPanel]=useState('memory'),[weightBits,setWeightBits]=useState(16),[kvHeads,setKvHeads]=useState(8),[cacheBits,setCacheBits]=useState(16),[batch,setBatch]=useState(1),[tokens,setTokens]=useState(4096),[budget,setBudget]=useState(16);
 const [preset,setPreset]=useState('balanced'),[quantBits,setQuantBits]=useState(4),[grouping,setGrouping]=useState('tensor'),[selected,setSelected]=useState(4);
 const m=useMemo(()=>memory(weightBits,kvHeads,cacheBits,batch,tokens,budget),[weightBits,kvHeads,cacheBits,batch,tokens,budget]),q=useMemo(()=>compression(preset,quantBits,grouping),[preset,quantBits,grouping]);
 const row=q.rows[selected],extent=Math.max(budget,m.gib.total),printedM=memory(),printedQ=compression();
 function reset(){setPanel('memory');setWeightBits(16);setKvHeads(8);setCacheBits(16);setBatch(1);setTokens(4096);setBudget(16);setPreset('balanced');setQuantBits(4);setGrouping('tensor');setSelected(4);}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({memory:m,compression:q},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-26-efficiency-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab efficiency-lab" aria-label="Memory and quantization experiment">
  <div className="lab-top"><span className="eyebrow">COUNT. COMPRESS. COMPARE.</span><span className="lab-tag">Calculated estimates · no GPU run</span></div>
  <h3>Smaller numbers. Different tradeoffs.</h3><p>Estimate memory for a hypothetical movie assistant, then inspect quantization on six hand-set weights. These are separate teaching calculations, not a hardware benchmark.</p>
  <div className="screen-only">
   <div className="eff-tabs" role="group" aria-label="Experiment view"><button className="small-button" aria-pressed={panel==='memory'} onClick={()=>setPanel('memory')}>1 · Plan memory</button><button className="small-button" aria-pressed={panel==='quant'} onClick={()=>setPanel('quant')}>2 · Inspect quantization</button></div>
   <div hidden={panel!=='memory'}>
    <p className="lab-note">Fixed assumptions: 7 billion parameters, 32 layers, 32 query heads, head width 128. All sequences keep the same number of tokens. One model copy; no prefix sharing or offloading.</p>
    <div className="eff-controls"><label>Weight storage<select id="eff-weight" value={weightBits} onChange={e=>setWeightBits(Number(e.target.value))}>{[16,8,4].map(n=><option key={n} value={n}>{n}-bit payload</option>)}</select></label><label>KV heads · architecture comparison<select id="eff-heads" value={kvHeads} onChange={e=>setKvHeads(Number(e.target.value))}><option value="32">32 · Multi-head (MHA)</option><option value="8">8 · Grouped-query (GQA)</option><option value="1">1 · Multi-query (MQA)</option></select></label><label>KV-cache storage<select id="eff-cache" value={cacheBits} onChange={e=>setCacheBits(Number(e.target.value))}>{[16,8].map(n=><option key={n} value={n}>{n}-bit payload</option>)}</select></label><label>Concurrent sequences<select id="eff-batch" value={batch} onChange={e=>setBatch(Number(e.target.value))}>{[1,4,8].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Retained tokens per sequence<select id="eff-tokens" value={tokens} onChange={e=>setTokens(Number(e.target.value))}>{[1024,4096,8192].map(n=><option key={n} value={n}>{n.toLocaleString('en-US')} · prompt + output</option>)}</select></label><label>Memory budget<select id="eff-budget" value={budget} onChange={e=>setBudget(Number(e.target.value))}>{[8,16,24].map(n=><option key={n} value={n}>{n} GiB</option>)}</select></label></div>
    <div className="eff-memory-summary" aria-live="polite"><p><strong data-eff="total">{f(m.gib.total)} GiB</strong> modeled total · <span data-eff="status">{m.withinEstimate?'Within estimate':'Over budget'}</span></p><p>Budget minus estimate: <strong data-eff="headroom">{signed(m.gib.headroom)} GiB</strong></p></div>
    <div className="eff-chart" role="img" aria-label={`Memory: weights ${f(m.gib.weights)}, cache ${f(m.gib.cache)}, reserve ${m.gib.reserve}, budget ${budget} GiB. ${m.withinEstimate?'Within estimate':'Over budget'}.`}><div className="eff-track"><span className="eff-weights" style={{width:100*m.gib.weights/extent+'%'}}/><span className="eff-cache" style={{width:100*m.gib.cache/extent+'%'}}/><span className="eff-reserve" style={{width:100*m.gib.reserve/extent+'%'}}/><span className="eff-budget-line" style={{left:Math.min(99.7,100*budget/extent)+'%'}}/></div><p className="lab-note">Bar scale: 0–{f(extent)} GiB · vertical line = {budget} GiB budget</p></div>
    <div className="eff-table" role="region" aria-label="Memory breakdown" tabIndex={0}><table><thead><tr><th>Allocation</th><th>GiB</th><th>What it counts</th></tr></thead><tbody><tr><th><span className="eff-key eff-weights"/>Weights</th><td data-eff="weights">{f(m.gib.weights)}</td><td>Ideal packed payload</td></tr><tr><th><span className="eff-key eff-cache"/>KV cache</th><td data-eff="cache">{f(m.gib.cache)}</td><td>Keys and values for {batch} {batch===1?'sequence':'sequences'}</td></tr><tr><th><span className="eff-key eff-reserve"/>Other runtime</th><td>{f(m.gib.reserve)}</td><td>Illustrative fixed reserve</td></tr></tbody></table></div>
    <p className="eff-insight">This estimate allows at most <strong data-eff="capacity">{m.maxSequences}</strong> {m.maxSequences===1?'sequence':'sequences'} of {tokens.toLocaleString('en-US')} tokens under these assumptions. Real capacity can be lower. The 2 GiB reserve is not a measurement; quantization metadata, allocation behavior, and actual runtime peaks still need checking.</p>
    <details className="workshop-detail eff-formula"><summary>Inspect the memory formula and its limits</summary><p>Weights = 7,000,000,000 × {weightBits} / 8 = {m.weightsBytes.toLocaleString('en-US')} bytes.</p><p>Cache = 2 × {batch} × {tokens} × 32 × {kvHeads} × 128 × {cacheBits} / 8 = <strong data-eff="cache-bytes">{m.cacheBytes.toLocaleString('en-US')}</strong> bytes.</p><p>One retained token uses {m.cachePerToken.toLocaleString('en-US')} cache bytes per sequence across all layers. Divide bytes by 2³⁰ for GiB. Capacity floors (budget − weights − reserve) / cache per sequence, with a minimum of zero.</p><p>Changing KV heads compares hypothetical architectures. It does not convert a trained checkpoint. Parameter count stays fixed here to isolate cache size; actual architectures may differ. Weight and cache precisions are independent. Packed-payload counts omit scales, zero points, alignment, and tensors kept at higher precision.</p></details>
   </div>
   <div hidden={panel!=='quant'}>
    <div className="eff-controls"><label>Weight example<select id="eff-preset" value={preset} onChange={e=>setPreset(e.target.value)}><option value="balanced">Moderate values</option><option value="outlier">One outlier · final weight 6</option></select></label><label>Integer codes<select id="eff-quant" value={quantBits} onChange={e=>setQuantBits(Number(e.target.value))}>{[4,8].map(n=><option key={n} value={n}>{n} bits</option>)}</select></label><label>Scale grouping<select id="eff-group" value={grouping} onChange={e=>setGrouping(e.target.value)}><option value="tensor">One scale for all weights</option><option value="pairs">One scale per pair</option></select></label></div>
    <p className="lab-note">Select a weight to trace its integer code and reconstructed value. Scroll the table sideways on smaller screens to see every column. The symmetric code range is −{q.qmax} to +{q.qmax}; the most negative signed code is unused.</p>
    <div className="eff-table eff-wide" role="region" aria-label="Quantized weights" tabIndex={0}><table><thead><tr><th>Weight</th><th>Original</th><th>Group</th><th>Code</th><th>Restored</th><th>Absolute error</th></tr></thead><tbody>{q.rows.map((r,i)=><tr key={i}><th><button className="small-button" aria-label={`Inspect weight ${i+1}`} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{i+1}</button></th><td>{f(r.original)}</td><td>{r.group}</td><td data-eff-code={i}>{r.code}</td><td>{f(r.restored)}</td><td>{f(Math.abs(r.error))}</td></tr>)}</tbody></table></div>
    <div className="eff-insight" aria-live="polite"><p>Weight {selected+1}: <strong>{f(row.original)}</strong> · group {row.group}</p><p>Scale = <strong data-eff="scale">{f(row.scale)}</strong><br/>Divide by scale → <strong data-eff="scaled">{f(row.original/row.scale)}</strong><br/>Round half away from zero, then clamp → <strong data-eff="code">{row.code}</strong><br/>Code × scale → <strong data-eff="restored">{f(row.restored)}</strong></p></div>
    <div className="eff-table" role="region" aria-label="Quantization comparison" tabIndex={0}><table><thead><tr><th>Measure</th><th>Value</th></tr></thead><tbody><tr><th>Mean absolute weight error</th><td data-eff="mae">{f(q.mae)}</td></tr><tr><th>Maximum weight error</th><td data-eff="max">{f(q.maxError)}</td></tr><tr><th>Original matching score</th><td data-eff="original-score">{f(q.originalScore)}</td></tr><tr><th>Reconstructed matching score</th><td data-eff="restored-score">{f(q.restoredScore)}</td></tr><tr><th>Score change</th><td data-eff="score-change">{signed(q.scoreChange)}</td></tr></tbody></table></div>
    <p className="eff-insight">Modeled packed storage: <strong data-eff="storage">{q.payloadBytes} payload + {q.scaleBytes} scale = {q.totalBytes} bytes</strong>, versus {q.fp32Bytes} bytes for six float32 weights. Extra groups add metadata. These are layout estimates, not the size of the JSON file.</p>
    <details className="workshop-detail eff-score"><summary>Inspect the score and quantizer assumptions</summary><p>Hand-set movie features: <code>{JSON.stringify(data.features)}</code>. Matching score = sum of feature × weight. It has no probability interpretation and does not measure recommendation quality.</p><p>Each group uses scale = max absolute weight / {q.qmax}; all-zero groups use scale 1. This demo keeps calculations at host floating-point precision and does not physically pack integers or round scales to float32. The byte estimate assumes four bytes per stored scale, without alignment or headers.</p><p>Try the outlier with pair grouping. Its mean weight error falls, but this particular score's absolute error grows. Cancellation and feature values matter; judge a compressed LLM on real tasks.</p></details>
   </div>
   <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset experiment</button><button className="small-button" onClick={download}>Download calculation report</button></div>
  </div>
  <div className="print-only"><p>Default memory estimate: 7B parameters, 16-bit weights, 32 layers, 8 KV heads of width 128, 16-bit cache, one 4096-token sequence, and a 16 GiB budget.</p><table><thead><tr><th>Weights</th><th>KV cache</th><th>Reserve</th><th>Total</th></tr></thead><tbody><tr><td>{f(printedM.gib.weights)} GiB</td><td>0.5000 GiB</td><td>2.0000 GiB</td><td>{f(printedM.gib.total)} GiB</td></tr></tbody></table><p>Headroom = <strong>0.4615 GiB</strong>. With 32 KV heads, cache becomes 2 GiB and total becomes 17.0385 GiB. Weight-only 4-bit payload reduces default total to 5.7596 GiB. The reserve is illustrative; these figures do not certify that a real model fits.</p><p>Default quantizer: 4-bit symmetric codes, one scale = 1/7. Fixed features = [0.2, 0.6, 0.1, 0.3, 0.8, 1].</p><table><thead><tr><th>Original</th><th>Code</th><th>Restored</th><th>Absolute error</th></tr></thead><tbody>{printedQ.rows.map(r=><tr key={r.index}><td>{f(r.original)}</td><td>{r.code}</td><td>{f(r.restored)}</td><td>{f(Math.abs(r.error))}</td></tr>)}</tbody></table><p>Mean weight error = <strong>{f(printedQ.mae)}</strong>. Matching score changes from <strong>0.8820 to 0.9143</strong>. Packed-layout estimate = 3 payload bytes + 4 scale bytes = 7 bytes, versus 24 bytes at float32. None of these quantities is task accuracy or measured speed.</p></div>
 </section>;
}
