import {useId,useMemo,useState} from 'react';
import {experiment} from '../lib/model-evaluation.mjs';
const percent=(x:number|null)=>x===null?'Undefined':(100*x).toFixed(2)+'%';
const number=(x:number|null)=>x===null?'Undefined':x.toFixed(4);
const name=(s:string)=>s==='baseline'?'Constant baseline':'Candidate '+s.toUpperCase();
const printed=[experiment('a',.5),experiment('a',.6),experiment('b',.7),experiment('baseline',.5)];
export default function EvaluationLab(){
  const [candidate,setCandidate]=useState('a'),[threshold,setThreshold]=useState(.5),[slice,setSlice]=useState('all'),[cost,setCost]=useState('misses');
  const result=useMemo(()=>experiment(candidate,threshold,slice,cost),[candidate,threshold,slice,cost]);
  const r=result.validation,c=r.confusion,winner=result.selection.winner,costs=result.configuration.costs;
  const id='evaluation-'+useId().replace(/[^a-zA-Z0-9]/g,'');
  const xp=(x:number)=>140+300*x,yp=(y:number)=>340-300*y;
  const reset=()=>{setCandidate('a');setThreshold(.5);setSlice('all');setCost('misses');};
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-15-evaluation-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="lab evaluation-lab" aria-label="Model evaluation workbench">
    <div className="lab-top"><span className="eyebrow">COUNT ERRORS. CHOOSE THE TRADEOFF.</span><span className="lab-tag">Real metrics · authored predictions</span></div>
    <h3>Same predictions. Different decisions.</h3><p>Twelve fictional validation events contain observed thumbs-up labels and two frozen sets of invented probabilities. We calculate their metrics here; no model is trained by this explorer.</p>
    <div className="screen-only">
      <div className="training-controls"><label htmlFor="eval-candidate">Prediction set<select id="eval-candidate" value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="a">Candidate A</option><option value="b">Candidate B</option><option value="baseline">Constant baseline · p = 0.25</option></select></label><label htmlFor="eval-slice">Validation events<select id="eval-slice" value={slice} onChange={e=>setSlice(e.target.value)}><option value="all">All histories · 12 events</option><option value="short">Short history · fewer than 5 ratings</option><option value="long">Long history · at least 5 ratings</option></select></label><label htmlFor="eval-cost">Cost assumption<select id="eval-cost" value={cost} onChange={e=>setCost(e.target.value)}><option value="misses">Missed likes cost ×3</option><option value="unwanted">Unwanted suggestions cost ×3</option><option value="equal">Both errors cost the same</option></select></label><label htmlFor="eval-threshold" className="evaluation-threshold">Decision threshold <strong>{threshold.toFixed(2)}</strong><input id="eval-threshold" type="range" min="0" max="1" step="0.05" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label></div>
      <p className="eval-policy">Predict thumbs-up when p ≥ {threshold.toFixed(2)}. Each false positive costs {costs.fp}; each missed like costs {costs.fn}. These are teaching units, not measured business costs.</p>
      <p className="local-note" data-eval="sample">{r.n} events · {r.positives} observed likes ({percent(r.prevalence)}) · threshold edits leave the supplied probabilities fixed.</p>
      <div className="lab-metrics evaluation-metrics" aria-live="polite"><div><strong data-eval="accuracy">{percent(r.accuracy)}</strong><span>Accuracy</span></div><div><strong data-eval="precision">{percent(r.precision)}</strong><span>Precision</span></div><div><strong data-eval="recall">{percent(r.recall)}</strong><span>Recall</span></div><div><strong data-eval="f1">{number(r.f1)}</strong><span>F1 score</span></div><div><strong data-eval="cost">{r.total_cost}</strong><span>Total weighted error cost</span></div><div><strong data-eval="loss">{number(r.log_loss)}</strong><span>Mean log loss</span></div></div>
      <div className="eval-table-wrap" tabIndex={0} role="region" aria-label="Confusion matrix"><table className="eval-confusion"><caption>Counts for the current validation slice</caption><thead><tr><th scope="col">Observed ↓ / predicted →</th><th scope="col">Thumbs-up</th><th scope="col">Thumbs-down</th></tr></thead><tbody><tr><th scope="row">Observed thumbs-up</th><td><strong data-eval="tp">{c.tp}</strong> TP · found likes</td><td className="eval-error"><strong data-eval="fn">{c.fn}</strong> FN · missed likes</td></tr><tr><th scope="row">Observed thumbs-down</th><td className="eval-error"><strong data-eval="fp">{c.fp}</strong> FP · unwanted suggestions</td><td><strong data-eval="tn">{c.tn}</strong> TN · correct negatives</td></tr></tbody></table></div><p className="local-note eval-scroll-hint">Scroll sideways for both prediction columns.</p>
      <figure className="training-figure"><div className="training-plot-scroll" tabIndex={0} role="region" aria-label="ROC curve and current threshold"><svg viewBox="0 0 600 405" role="img" aria-labelledby={id+'-title '+id+'-desc'}><title id={id+'-title'}>{'ROC curve for '+name(candidate)}</title><desc id={id+'-desc'}>The curve sweeps every distinct score in the current validation slice. A gold circle marks the false positive rate and recall at the selected threshold. The dashed diagonal represents chance-level ranking.</desc>
        {[0,.25,.5,.75,1].map(v=><g key={v}><line x1="140" x2="440" y1={yp(v)} y2={yp(v)} className="plot-grid"/><line x1={xp(v)} x2={xp(v)} y1="40" y2="340" className="plot-grid"/><text x="128" y={yp(v)+4} textAnchor="end" className="plot-tick">{v}</text><text x={xp(v)} y="362" textAnchor="middle" className="plot-tick">{v}</text></g>)}
        <text x="140" y="23" className="plot-label">Recall / true positive rate</text><text x="290" y="391" textAnchor="middle" className="plot-label">False positive rate</text><line x1="140" y1="340" x2="440" y2="40" className="eval-chance"/>
        {r.roc&&<polyline fill="none" points={r.roc.map(p=>`${xp(p.fpr)},${yp(p.tpr)}`).join(' ')} className="prediction-line"/>}{r.fpr!==null&&r.recall!==null&&<circle cx={xp(r.fpr)} cy={yp(r.recall)} r="7" className="eval-operating-point"/>}
      </svg></div><figcaption>Line = thresholds swept together; gold point = the current decision. The threshold is not an axis. AUC stays fixed when only the threshold moves.{' '}<span className="mobile-only">Scroll sideways to inspect the full chart.</span></figcaption></figure>
      <p className="eval-secondary">ROC-AUC: <strong data-eval="auc">{number(r.auc)}</strong> · Brier score: <strong data-eval="brier">{number(r.brier)}</strong> · Balanced accuracy: <strong>{percent(r.balanced_accuracy)}</strong> · Cost per event: <strong>{number(r.cost_per_event)}</strong></p>
      <div className="eval-selection"><h4>Compare a fixed set on validation</h4><p data-eval="winner">Lowest cost: {name(winner.candidate)} at threshold {winner.threshold.toFixed(2)}, with cost {winner.total_cost} across all 12 validation events.</p><p className="local-note">This comparison always uses both candidates and five preset thresholds on all validation rows. Only the cost assumption changes its winner; the prediction and slice controls above are separate exploration.</p><button className="small-button" onClick={()=>{setCandidate(winner.candidate);setThreshold(winner.threshold);setSlice('all');}}>Use selected policy</button><details className="workshop-detail eval-comparison"><summary>Inspect all 10 validation configurations</summary><div className="eval-table-wrap" tabIndex={0} role="region" aria-label="Validation selection comparison"><table><thead><tr><th>Candidate</th><th>Threshold</th><th>Total cost</th><th>Accuracy</th></tr></thead><tbody>{result.selection.comparison.map(row=><tr key={row.candidate+row.threshold}><td>{name(row.candidate)}{row===winner?' · selected':''}</td><td>{row.threshold.toFixed(2)}</td><td>{row.total_cost}</td><td>{percent(row.accuracy)}</td></tr>)}</tbody></table></div><p>Ties keep the first row in this displayed order. The winning validation score is a selection result, not an unbiased final estimate. Test evaluation is reserved for the workbook.</p></details></div>
      <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset evaluation</button><button className="small-button" onClick={download}>Download evaluation result</button></div>
      <details className="workshop-detail eval-events"><summary>Inspect the individual predictions</summary><div className="eval-table-wrap" tabIndex={0} role="region" aria-label="Individual validation predictions"><table><thead><tr><th>Event / movie</th><th>Earlier ratings</th><th>Observed like</th><th>Probability</th><th>Decision / outcome</th></tr></thead><tbody>{r.rows.map(row=><tr key={row.event_id}><td>{row.event_id} · {row.movie}</td><td>{row.prior_ratings}</td><td>{row.liked}</td><td>{row.probability.toFixed(2)}</td><td>{row.predicted} · {row.outcome}</td></tr>)}</tbody></table></div><p>Each supplied event belongs to a different viewer. Both candidates are evaluated on exactly the same selected rows. An observed dislike is 0; missing feedback is not present in this snapshot.</p></details>
    </div>
    <div className="print-only"><p>Default: Candidate A, threshold 0.50, all 12 validation events, FP cost 1 and FN cost 3. TP = 3, FP = 2, TN = 7, FN = 0. Accuracy is 83.33%, precision 60%, recall 100%, and F1 0.7500.</p><table><thead><tr><th>Prediction set / threshold</th><th>Accuracy</th><th>Precision</th><th>Recall</th><th>Cost</th></tr></thead><tbody>{printed.map(p=><tr key={p.configuration.candidate+p.configuration.threshold}><td>{name(p.configuration.candidate)} / {p.configuration.threshold.toFixed(2)}</td><td>{percent(p.validation.accuracy)}</td><td>{percent(p.validation.precision)}</td><td>{percent(p.validation.recall)}</td><td>{p.validation.total_cost}</td></tr>)}</tbody></table><p>Candidate A has ROC-AUC 0.9259, log loss 0.4485, and Brier score 0.1438. Moving only its threshold changes none of these three values. The fixed validation comparison selects A at 0.60 under the default cost rule. With FP cost 3 and FN cost 1, it selects B at 0.70. These are synthetic selection results, not measured production gains.</p></div>
    <noscript><p>Enable JavaScript to explore, or use the Python workbook and the PDF's fixed comparison.</p></noscript>
  </section>;
}
