import {useState} from 'react';
import {data,corruption,generate} from '../lib/generation.mjs';
import '../styles/generation.css';
const f=(n:number)=>n.toFixed(4);
type Point=number[];
function Plot({points,path=[],id}:{points:{point:Point;label:string;shape:string}[];path?:Point[];id:string}){
 const extent=Math.max(3,Math.ceil(Math.max(...[...points.map(p=>p.point),...path].flat().map(Math.abs))+.5));
 const px=(v:number)=>240+v*175/extent,py=(v:number)=>210-v*175/extent;
 return <div className="generation-chart"><svg viewBox="0 0 480 450" role="img" aria-labelledby={`${id}-title ${id}-desc`}><title id={`${id}-title`}>Toy poster-style coordinates</title><desc id={`${id}-desc`}>Horizontal: cool to warm. Vertical: spare to busy. Dashed circles mark one-coordinate-standard-deviation radii around style means, not image-quality targets. {points.map(p=>`${p.label}: (${f(p.point[0])}, ${f(p.point[1])})`).join('. ')}</desc>
  {[-extent,0,extent].map(v=><g key={v}><path d={`M65 ${py(v)} H415 M${px(v)} 35 V385`} stroke="var(--line)"/><text x="54" y={py(v)+4} textAnchor="end">{v}</text><text x={px(v)} y="407" textAnchor="middle">{v}</text></g>)}
  <text x="240" y="432" textAnchor="middle">Cool ← color → warm</text><text x="18" y="210" textAnchor="middle" transform="rotate(-90 18 210)">Spare ← composition → busy</text>
  {Object.values(data.styles).map((style:{label:string;mean:number[]})=><g key={style.label}><circle cx={px(style.mean[0])} cy={py(style.mean[1])} r={.5*175/extent} fill="var(--accent-soft)" fillOpacity=".45" stroke="var(--muted)" strokeDasharray="4 4"/><text x={px(style.mean[0])} y={py(style.mean[1])-.5*175/extent-8} textAnchor="middle">{style.label.split(' ')[0]}</text></g>)}
  {path.length>0&&<path d={path.map((p,i)=>`${i?'L':'M'}${px(p[0])} ${py(p[1])}`).join(' ')} fill="none" stroke="var(--accent)" strokeWidth="2.5"/>}
  {path.slice(1,-1).map((p,i)=><circle key={i} cx={px(p[0])} cy={py(p[1])} r="2.5" fill="var(--accent)"/>)}
  {points.map(p=><g key={p.label}><title>{p.label}</title>{p.shape==='circle'?<circle cx={px(p.point[0])} cy={py(p.point[1])} r="6" fill="var(--paper)" stroke="var(--ink)" strokeWidth="2"/>:p.shape==='square'?<rect x={px(p.point[0])-5} y={py(p.point[1])-5} width="10" height="10" fill="var(--gold)" stroke="var(--ink)"/>:<path d={`M${px(p.point[0])} ${py(p.point[1])-8} l7 14 h-14Z`} fill="var(--accent)" stroke="var(--paper)"/>}</g>)}
 </svg><p className="lab-note">{points.map(p=>`${p.shape==='circle'?'○':p.shape==='square'?'■':'▲'} ${p.label}`).join(' · ')}. Axes rescale to fit the points.</p></div>;
}
export default function GenerationLab(){
 const [view,setView]=useState(1),[style,setStyle]=useState('calm'),[seed,setSeed]=useState(42),[level,setLevel]=useState(4),[estimator,setEstimator]=useState('conditional');
 const [sampleStyle,setSampleStyle]=useState('calm'),[sampleSeed,setSampleSeed]=useState(42),[guidance,setGuidance]=useState(1),[steps,setSteps]=useState(8);
 const c=corruption(style,seed,level,estimator),g=generate(sampleStyle,sampleSeed,guidance,steps);
 function reset(){setView(1);setStyle('calm');setSeed(42);setLevel(4);setEstimator('conditional');setSampleStyle('calm');setSampleSeed(42);setGuidance(1);setSteps(8);}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({corruption:c,generation:g},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='chapter-29-generation-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab generation-lab" aria-labelledby="generation-title">
  <div className="lab-top"><span className="eyebrow">CORRUPT. ESTIMATE. SAMPLE.</span><span className="lab-tag">Two coordinates · no image model</span></div>
  <h3 id="generation-title">Add noise. Estimate. Generate.</h3><p>Explore an exactly known toy distribution of poster styles. These coordinates illustrate the mathematics; they do not generate pictures or measure quality.</p>
  <div className="screen-only">
   <div className="generation-tabs"><button className="small-button" aria-pressed={view===1} onClick={()=>setView(1)}>1 · Add and estimate noise</button><button className="small-button" aria-pressed={view===2} onClick={()=>setView(2)}>2 · Generate with guidance</button></div>
   <div hidden={view!==1}>
    <div className="generation-controls"><label htmlFor="gen-style">Original style<select id="gen-style" value={style} onChange={e=>setStyle(e.target.value)}><option value="calm">Calm</option><option value="adventure">Adventure</option></select></label><label htmlFor="gen-seed">Seed<select id="gen-seed" value={seed} onChange={e=>setSeed(+e.target.value)}>{data.seeds.map(v=><option key={v}>{v}</option>)}</select></label><label htmlFor="gen-estimator">Noise estimator<select id="gen-estimator" value={estimator} onChange={e=>setEstimator(e.target.value)}><option value="conditional">Conditional: knows the style</option><option value="unconditional">Unconditional: style unknown</option><option value="oracle">Teaching oracle: knows true noise</option></select></label></div>
    <div className="slider-row"><label htmlFor="gen-level">Noise level <output>{level} / 7</output></label><input id="gen-level" type="range" min="1" max="7" step="1" value={level} onChange={e=>setLevel(+e.target.value)}/><p className="lab-note">Holding the seed and style fixed keeps the original and the random noise draw fixed. This slider changes their mixing coefficients.</p></div>
    <div className="generation-insight" aria-live="polite"><p>Signal coefficient a = <strong data-gen="a">{f(c.a)}</strong> · signal scale √a = <strong data-gen="signal">{f(c.signalScale)}</strong> · noise scale √(1−a) = <strong data-gen="noise">{f(c.noiseScale)}</strong></p><p>Reconstruction MSE = <strong data-gen="mse">{f(c.mse)}</strong> · noise-error amplification = <strong data-gen="amplification">{f(c.errorAmplification)}</strong></p><p className="lab-note">{estimator==='oracle'?'The oracle uses the actual hidden noise draw. Exact recovery here is a teaching identity, not what a generative model normally knows.':'The analytic estimator returns a posterior-mean noise prediction. It does not know the original noise draw; more corruption generally leaves more uncertainty.'}</p></div>
    <Plot id="gen-corruption" points={[{point:c.clean,label:'Original',shape:'circle'},{point:c.noisy,label:'Noisy point',shape:'square'},{point:c.reconstructed,label:'Clean estimate',shape:'triangle'}]}/>
    <div className="generation-table"><table><thead><tr><th>Point</th><th>Color</th><th>Composition</th></tr></thead><tbody>{[['Original',c.clean],['Noisy',c.noisy],['Estimate',c.reconstructed]].map(([label,point])=><tr key={label as string}><th>{label as string}</th>{(point as Point).map((n,j)=><td key={j} data-coordinate={`${label}-${j}`}>{f(n)}</td>)}</tr>)}</tbody></table></div>
    <details className="workshop-detail"><summary>Inspect the noise prediction</summary><p>Actual noise: [{c.epsilon.map(f).join(', ')}]. Predicted noise: [{c.predictedNoise.map(f).join(', ')}]. The clean estimate is (noisy point − noise scale × predicted noise) / signal scale.</p><p>The MSE compares only these two numerical coordinates. A single example's error need not increase at every noise level.</p></details>
   </div>
   <div hidden={view!==2}>
    <p className="lab-note">A fresh standard-normal draw starts an independent sampling experiment. Each step combines conditional and unconditional analytic predictions using εu + s(εc − εu), then makes a deterministic DDIM-style update. No original poster is supplied.</p>
    <div className="generation-controls"><label htmlFor="gen-sample-style">Target style<select id="gen-sample-style" value={sampleStyle} onChange={e=>setSampleStyle(e.target.value)}><option value="calm">Calm</option><option value="adventure">Adventure</option></select></label><label htmlFor="gen-sample-seed">Sampling seed<select id="gen-sample-seed" value={sampleSeed} onChange={e=>setSampleSeed(+e.target.value)}>{data.seeds.map(v=><option key={v}>{v}</option>)}</select></label><label htmlFor="gen-guidance">Guidance s<select id="gen-guidance" value={guidance} onChange={e=>setGuidance(+e.target.value)}>{[0,1,3,7].map(v=><option key={v}>{v}</option>)}</select></label><label htmlFor="gen-steps">Sampling steps<select id="gen-steps" value={steps} onChange={e=>setSteps(+e.target.value)}>{[4,8,16].map(v=><option key={v}>{v}</option>)}</select></label></div>
    <div className="generation-insight" aria-live="polite"><p>Final color = <strong data-gen="final-x">{f(g.final[0])}</strong> · final composition = <strong data-gen="final-y">{f(g.final[1])}</strong></p><p>{guidance===0?'Unconditional sampling: switching the target style leaves this path unchanged.':guidance===1?'Conditional sampling: use the target-style prediction directly.':'Extrapolated guidance: stronger steering changes the sampled distribution and may distort it.'}</p><p className="lab-note">Start at a ≈ 0.001 and finish at a = 1. Finite steps and an approximate starting distribution mean the results are not exact target-distribution samples. Closer to a style center does not mean a better poster.</p></div>
    <Plot id="gen-sampling" path={g.history.map((r:{point:Point})=>r.point)} points={[{point:g.start,label:'Starting noise',shape:'circle'},{point:g.final,label:'Generated point',shape:'triangle'}]}/>
    <details className="workshop-detail"><summary>Trace every sampling step</summary><div className="generation-table"><table><thead><tr><th>Step</th><th>a</th><th>Color</th><th>Composition</th></tr></thead><tbody>{g.history.map((r:{step:number;a:number;point:Point})=><tr key={r.step}><td>{r.step}</td><td>{f(r.a)}</td><td>{f(r.point[0])}</td><td>{f(r.point[1])}</td></tr>)}</tbody></table></div></details>
   </div>
   <div className="workshop-actions"><button className="small-button" onClick={download}>Download generation report</button><button className="small-button" onClick={reset}>Reset experiment</button></div>
  </div>
  <div className="print-only"><p><strong>Worked scalar example:</strong> clean value x₀ = 1, true noise ε = 2, and signal coefficient a = 0.25. Signal scale = 0.5000; noise scale ≈ 0.8660. The corrupted value is 2.2321.</p><table><thead><tr><th>Noise estimate</th><th>Clean estimate</th><th>Interpretation</th></tr></thead><tbody><tr><td>2.0000</td><td>1.0000</td><td>Oracle: uses the true noise</td></tr><tr><td>1.5000</td><td>1.8660</td><td>Noise error changes reconstruction</td></tr></tbody></table><p>Noise-error amplification = √((1−a)/a) = 1.7321. During generation there is no original value to recover. A sampler starts with noise and follows repeated predictions. With our guidance convention, s = 0 ignores the condition, s = 1 uses it directly, and s &gt; 1 extrapolates. None of these values proves visual quality.</p></div>
 </section>;
}
