import {useMemo,useState} from 'react';
import {data,tokenize,explore,score} from '../lib/language-model.mjs';
const f=(x:number)=>x.toFixed(4),pct=(x:number)=>(100*x).toFixed(2)+'%';
export default function LanguageLab(){
 const [mode,setMode]=useState('tokens'),[text,setText]=useState(data.samples[0]),[budget,setBudget]=useState(16),[prefix,setPrefix]=useState(data.prefixes[0]),[alpha,setAlpha]=useState(1),[temperature,setTemperature]=useState(1),[topk,setTopk]=useState(0),[method,setMethod]=useState('greedy'),[scoreCase,setScoreCase]=useState('familiar');
 const bpe=useMemo(()=>{try{return {value:tokenize(text,budget),error:''};}catch(e){return {value:null,error:e instanceof Error?e.message:'Invalid text.'};}},[text,budget]);
 const lm=useMemo(()=>explore(prefix,alpha,temperature,topk,method,scoreCase),[prefix,alpha,temperature,topk,method,scoreCase]);
 function reset(){setMode('tokens');setText(data.samples[0]);setBudget(16);setPrefix(data.prefixes[0]);setAlpha(1);setTemperature(1);setTopk(0);setMethod('greedy');setScoreCase('familiar');}
 function download(){const report=mode==='tokens'?bpe.value:lm;if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify({experiment:mode,...report},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-23-'+mode+'-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const printed=tokenize(),un=score(undefined,0),smooth=score(undefined,1);
 return <section className="lab language-lab" aria-label="Tokenization and language modeling explorer">
  <div className="lab-top"><span className="eyebrow">TEXT. TOKENS. PROBABILITIES.</span><span className="lab-tag">Six authored training sentences</span></div>
  <h3>Inspect the pieces. Predict the next one.</h3><p>Two independent experiments: a learned byte-pair tokenizer and a word-based bigram model. The second model does not use the first experiment's token IDs.</p>
  <div className="screen-only">
   <div className="lang-switcher" role="group" aria-label="Choose experiment"><button aria-pressed={mode==='tokens'} onClick={()=>setMode('tokens')}>1 · Tokenize text</button><button aria-pressed={mode==='model'} onClick={()=>setMode('model')}>2 · Predict and score</button></div>
   {mode==='tokens'&&<div data-lang-panel="tokens">
    <div className="lang-controls"><label>Load an example<select id="lang-sample" value={data.samples.includes(text)?text:''} onChange={e=>setText(e.target.value)}><option value="" disabled>Custom text</option>{data.samples.map(s=><option key={s} value={s}>{JSON.stringify(s)}</option>)}</select></label><label>Learned merge budget<select id="lang-merges" value={budget} onChange={e=>setBudget(Number(e.target.value))}>{[0,8,16,24].map(n=><option key={n} value={n}>{n} merges</option>)}</select></label></div>
    <label>Text to encode<textarea id="lang-text" rows={2} value={text} onChange={e=>setText(e.target.value)} spellCheck={false}/></label><p className="lab-note">Up to 200 Unicode code points. Case, spaces, and punctuation are preserved. Merge rules come only from the fixed corpus below.</p>
    {bpe.error&&<p className="lang-error" role="alert">{bpe.error}</p>}
    {bpe.value&&<>
     <div className="lab-metrics lang-metrics" aria-live="polite"><div><strong data-lang="codepoints">{bpe.value.codepoints}</strong><span>Unicode code points</span></div><div><strong data-lang="bytes">{bpe.value.byte_count}</strong><span>UTF-8 bytes</span></div><div><strong data-lang="tokens">{bpe.value.ids.length}</strong><span>BPE tokens</span></div></div>
     <div className="lang-tokens" aria-label="Encoded token pieces and IDs">{bpe.value.tokens.map((t,i)=><div key={i} className="lang-token"><span>{t.piece}</span><small>ID {t.id}</small></div>)}{!bpe.value.tokens.length&&<p>Empty text: no tokens.</p>}</div>
     <p className="lang-insight" data-lang="roundtrip">Round trip: {bpe.value.roundtrip?'exact match':'mismatch'} · Vocabulary: {bpe.value.vocab_size} entries = 256 base bytes + {bpe.value.merges.length} learned merges.</p>
     <p className="lab-note">␠ marks a space for display. A byte fragment that is not valid UTF-8 on its own appears as hex; concatenate all token bytes before decoding. IDs identify entries and do not measure meaning.</p>
     <details className="workshop-detail lang-merges"><summary>Inspect the learned merge rules</summary><p className="lab-note">Highest adjacent-pair count first. Ties use lower left ID, then lower right ID. Each replacement runs left to right without overlap. This teaching tokenizer permits merges across spaces.</p><div className="lang-table" role="region" tabIndex={0} aria-label="Byte-pair merge rules"><table><thead><tr><th>Rank</th><th>Pair IDs</th><th>Count</th><th>New ID / piece</th></tr></thead><tbody>{bpe.value.merges.map(m=><tr key={m.id}><td>{m.rank}</td><td>{m.left} + {m.right}</td><td>{m.count}</td><td>{m.id} · {m.piece}</td></tr>)}</tbody></table></div>{!bpe.value.merges.length&&<p>No merges: one token per byte.</p>}</details>
    </>}
   </div>}
   {mode==='model'&&<div data-lang-panel="model">
    <div className="lang-controls"><label>Prefix<select id="lang-prefix" value={prefix} onChange={e=>setPrefix(e.target.value)}>{data.prefixes.map(p=><option key={p}>{p}</option>)}</select></label><label>Additive smoothing<select id="lang-alpha" value={alpha} onChange={e=>setAlpha(Number(e.target.value))}><option value="0">α = 0 · observed counts only</option><option value="1">α = 1 · add one to every target</option></select></label></div>
    <div className="lang-controls lang-controls-three"><label>Selection<select id="lang-method" value={method} onChange={e=>setMethod(e.target.value)}><option value="greedy">Greedy</option><option value="sample">Seeded sampling</option></select></label><label>Temperature<select id="lang-temperature" value={temperature} onChange={e=>setTemperature(Number(e.target.value))}>{[.5,1,2].map(t=><option key={t} value={t}>{t}</option>)}</select></label><label>Top-k filter<select id="lang-topk" value={topk} onChange={e=>setTopk(Number(e.target.value))}><option value="0">Keep all</option><option value="3">Keep top 3</option></select></label></div>
    <p className="lang-equation">Context used: <strong data-lang="context">{lm.context}</strong> · Observed next tokens: {lm.total} · Denominator: {lm.total} + {alpha} × 13 = {lm.denominator}</p>
    <div className="lang-table" role="region" tabIndex={0} aria-label="Next token distribution"><table><thead><tr><th>Candidate</th><th>Count</th><th>Base p</th><th>Adjusted q</th></tr></thead><tbody>{[...lm.rows].sort((a,b)=>b.probability-a.probability||a.id-b.id).map(r=><tr key={r.id}><th>{r.token}</th><td>{r.count}</td><td data-lang-base={r.id}>{pct(r.probability)}</td><td data-lang-adjusted={r.id}>{pct(r.sampling_probability)}</td></tr>)}</tbody></table></div>
    <p className="lab-note">q applies temperature, then top-k filtering and renormalization. Sampling draws from q; greedy always chooses its largest entry, so q is not a greedy selection frequency. Ties use lower vocabulary ID.</p>
    <div className="lang-generation" aria-live="polite"><span className="eyebrow">COMPUTED CONTINUATION</span><p data-lang="generated">{lm.generation.text}</p><small data-lang="stop">{lm.generation.steps.length} new tokens · {lm.generation.stop}</small></div>
    <p className="lab-note">Each change restarts from seed 42, with a limit of 10 new tokens including the end token. The bigram uses only the last token; earlier words in the prefix do not change this distribution.</p>
    <details className="workshop-detail lang-generation-trace"><summary>Follow the generated tokens</summary><div className="lang-table" role="region" tabIndex={0} aria-label="Generation trace"><table><thead><tr><th>Context</th><th>Chosen</th><th>Base p</th><th>Adjusted q</th></tr></thead><tbody>{lm.generation.steps.map(s=><tr key={s.position}><td>{s.context}</td><td>{s.token}</td><td>{f(s.base_probability)}</td><td>{f(s.sampling_probability)}</td></tr>)}</tbody></table></div></details>
    <h4 className="lang-subtitle">Score a fixed sentence</h4><label>Sentence<select id="lang-score" value={scoreCase} onChange={e=>setScoreCase(e.target.value)}><option value="familiar">Familiar · this movie is fun .</option><option value="recombined">Recombined · this movie feels long .</option><option value="unknown">Unseen word · this movie is dazzling .</option></select></label>
    <div className="lab-metrics lang-metrics" aria-live="polite"><div><strong data-lang="targets">{lm.scoring.target_count}</strong><span>Targets, including end token</span></div><div><strong data-lang="nll">{lm.scoring.mean_nll===null?'Infinite':f(lm.scoring.mean_nll)}</strong><span>Mean negative log-probability</span></div><div><strong data-lang="perplexity">{lm.scoring.perplexity===null?'Infinite':f(lm.scoring.perplexity)}</strong><span>Perplexity</span></div></div>
    <p className="lang-insight">Scoring uses the observed sentence prefix and <strong>base probabilities</strong>. Temperature and top-k do not alter this score. {lm.scoring.unknowns.length>0&&<>“{lm.scoring.unknowns.join(', ')}” maps to {'<unk>'}; this score is for that mapped sequence, not the exact unseen word. </>}{lm.scoring.zero_probabilities>0&&<>{lm.scoring.zero_probabilities} transitions have zero probability, so loss and perplexity are infinite.</>}</p>
    <details className="workshop-detail lang-score-trace"><summary>Inspect each target's probability and loss</summary><div className="lang-table" role="region" tabIndex={0} aria-label="Sentence scoring trace"><table><thead><tr><th>Previous</th><th>Target</th><th>Base p</th><th>−ln(p)</th></tr></thead><tbody>{lm.scoring.steps.map(s=><tr key={s.position}><td>{s.context}</td><td>{s.token}</td><td>{f(s.probability)}</td><td>{s.nll===null?'Infinite':f(s.nll)}</td></tr>)}</tbody></table></div></details>
   </div>}
   <details className="workshop-detail lang-corpus"><summary>Read all six training sentences</summary><ol>{data.corpus.map((sentence,i)=><li key={i}>{sentence}</li>)}</ol><p className="lab-note">The repeated sentence intentionally affects counts. All cases are visible development examples; none establishes held-out language quality. The BPE tokenizer preserves raw bytes. The separate bigram lowercases ASCII words and splits punctuation.</p></details>
   <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset experiments</button><button className="small-button" disabled={mode==='tokens'&&!bpe.value} onClick={download}>Download calculation report</button></div>
  </div>
  <div className="print-only">
   <p><strong>Tokenization:</strong> “this movie is fun.” has {printed.codepoints} code points and {printed.byte_count} UTF-8 bytes. With 16 learned merges it becomes four tokens: <code>this␠movie␠is␠ | f | un | .</code>, IDs <code>270, 102, 268, 46</code>. The first learned pair is byte 115 (“s”) + byte 32 (space), observed 10 times. The full decoded text is unchanged.</p>
   <p><strong>Next token after “is”:</strong> counts are fun = 2, slow = 1, warm = 1. With α = 0 their probabilities are 0.5, 0.25, 0.25. With α = 1 and vocabulary size 13, they become 3/17, 2/17, 2/17; every other target gets 1/17. Greedy continuation of “this movie is” is “fun.” followed by the end token.</p>
   <table><thead><tr><th>Fixed sentence / policy</th><th>Mean loss</th><th>Perplexity</th></tr></thead><tbody><tr><td>this movie is fun . · α = 0</td><td>{f(un.mean_nll!)}</td><td>{f(un.perplexity!)}</td></tr><tr><td>this movie is fun . · α = 1</td><td>{f(smooth.mean_nll!)}</td><td>{f(smooth.perplexity!)}</td></tr><tr><td>this movie is dazzling . · α = 0</td><td>Infinite</td><td>Infinite</td></tr></tbody></table>
   <p>All scores include six targets, including the end token. “dazzling” maps to the unknown symbol. Scoring uses base probabilities, independent of temperature and sampling. These are teaching cases, not a test-set benchmark or factual-confidence measurement.</p>
  </div>
 </section>;
}
