import {useMemo,useState} from 'react';
import {data,train,generate} from '../lib/llm-lifecycle.mjs';
import '../styles/lifecycle.css';
const f=(x:number)=>x.toFixed(4),pct=(x:number)=>(100*x).toFixed(2)+'%';
type Checkpoint='initial'|'pretrained'|'adapted';
const names:Record<string,string>={initial:'Initial',pretrained:'After pretraining',adapted:'After SFT'};
export default function LifecycleLab(){
 const [panel,setPanel]=useState('train'),[mask,setMask]=useState('reply'),[steps,setSteps]=useState(80),[checkpoint,setCheckpoint]=useState<Checkpoint>('adapted'),[prompt,setPrompt]=useState('comedy'),[method,setMethod]=useState('greedy'),[temperature,setTemperature]=useState(1),[limit,setLimit]=useState(8),[step,setStep]=useState(0);
 const r=useMemo(()=>train(mask,steps),[mask,steps]);
 const g=useMemo(()=>generate(r.checkpoints[checkpoint],prompt,method,temperature,limit),[r,checkpoint,prompt,method,temperature,limit]);
 const index=Math.min(step,g.trace.length-1),selected=g.trace[index];
 const candidates=selected.probabilities.map((p:number,id:number)=>({id,p,token:data.vocabulary[id]})).sort((a:{p:number;id:number},b:{p:number;id:number})=>b.p-a.p||a.id-b.id).slice(0,5);
 const printed=useMemo(()=>train(),[]);
 function reset(){setPanel('train');setMask('reply');setSteps(80);setCheckpoint('adapted');setPrompt('comedy');setMethod('greedy');setTemperature(1);setLimit(8);setStep(0);}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({training:r,checkpoint,generation:g},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-25-lifecycle-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab lifecycle-lab" aria-label="Training and generation experiment">
  <div className="lab-top"><span className="eyebrow">TRAIN. FREEZE. GENERATE.</span><span className="lab-tag">Tiny trainable token table</span></div>
  <h3>Same model. Two different jobs.</h3><p>Train 15-token probability tables on movie text, then generate from a saved checkpoint. This is a two-token-context model, not a transformer or a useful recommender.</p>
  <div className="screen-only">
   <div className="life-tabs" role="group" aria-label="Experiment stage"><button className="small-button" aria-pressed={panel==='train'} onClick={()=>setPanel('train')}>1 · Train and compare</button><button className="small-button" aria-pressed={panel==='generate'} onClick={()=>setPanel('generate')}>2 · Generate from a checkpoint</button></div>
   <div hidden={panel!=='train'}>
    <div className="life-controls"><label>SFT loss mask<select id="life-mask" value={mask} onChange={e=>setMask(e.target.value)}><option value="reply">Assistant reply only</option><option value="all">All conversation tokens</option></select></label><label>SFT update steps<select id="life-steps" value={steps} onChange={e=>setSteps(Number(e.target.value))}><option value="0">0 · Base checkpoint</option><option value="20">20 updates</option><option value="80">80 updates</option></select></label></div>
    <p className="life-insight">Each setting starts from zero logits, performs <strong>80 pretraining updates</strong>, then <strong>{steps} SFT updates</strong>. Each update uses the entire chosen dataset. SFT scores <strong data-life="targets">{r.sft_targets}</strong> targets per update.</p>
    <div className="life-table" role="region" aria-label="Checkpoint losses" tabIndex={0}><table><thead><tr><th>Checkpoint</th><th>Prose loss<br/>(same 30 targets)</th><th>Reply loss<br/>(same 16 targets)</th></tr></thead><tbody>{r.stages.map(s=><tr key={s.name}><th>{names[s.name]}</th><td data-life={'prose-'+s.name}>{f(s.pretrain_loss)}</td><td data-life={'reply-'+s.name}>{f(s.reply_loss)}</td></tr>)}</tbody></table></div>
    <p className="lab-note">Lower is better for these visible training examples. Both columns use fixed evaluation targets even when the training mask changes. There is no held-out test set or recommendation-quality score.</p>
    <h4>Which targets teach the model?</h4><p>The first conversation is <code>{'<user> comedy <assistant> Moonlight Map . <eos>'}</code>. The whole prefix remains available. Only the selected targets contribute direct loss.</p>
    <div className="life-table life-wide" role="region" aria-label="Demonstration targets and loss mask" tabIndex={0}><table><thead><tr><th>Two-token context</th><th>Next target</th><th>Scored?</th><th>Before SFT</th><th>After SFT</th></tr></thead><tbody>{r.demonstration.map((row,i)=><tr key={i}><td><code>{row.context}</code></td><td><code>{row.target}</code></td><td data-life-mask={i}>{row.selected?'Yes':'No'}</td><td>{pct(row.before)}</td><td>{pct(row.after)}</td></tr>)}</tbody></table></div>
    <p className="life-insight" data-life="mask-note">{mask==='reply'?'Reply-only training updates rows separate from the prose rows in this tiny table, so its prose loss stays unchanged. Shared neural-network weights do not have this guarantee.':'All-token training also updates the shared start context to predict a user marker. Its old prose loss rises: fitting the new format can interfere with an earlier task.'}</p>
    <details className="workshop-detail life-data"><summary>Inspect the complete training data and update rule</summary><p>Pretraining: six sentences, each with an appended end token. SFT: four demonstrations, each with role markers and an end token. Repeated examples are intentional weights in this tiny exercise.</p><pre><code>{JSON.stringify({pretraining:data.pretraining,demonstrations:data.demonstrations},null,2)}</code></pre><p>Each context pair has an independent row of 15 logits. Start all rows at zero. Compute softmax, average the selected target losses, and update each logit by −3 × its accumulated gradient. The learning rate 3 is specific to this toy table. It is not a recommended LLM setting.</p><p>For a target, the logit gradient is (probability − target indicator) / number of scored targets. The JSON report includes every checkpoint, all loss-history steps, and the generation trace.</p></details>
   </div>
   <div hidden={panel!=='generate'}>
    <div className="life-controls"><label>Frozen checkpoint<select id="life-checkpoint" value={checkpoint} onChange={e=>{setCheckpoint(e.target.value as Checkpoint);setStep(0);}}><option value="initial">Initial · untrained</option><option value="pretrained">After pretraining</option><option value="adapted">After SFT · current settings</option></select></label><label>Prompt<select id="life-prompt" value={prompt} onChange={e=>{setPrompt(e.target.value);setStep(0);}}><option value="comedy">Ask for a comedy</option><option value="drama">Ask for a drama</option><option value="prose">Continue “comedy is”</option></select></label><label>Token selection<select id="life-method" value={method} onChange={e=>{setMethod(e.target.value);setStep(0);}}><option value="greedy">Greedy · highest probability</option><option value="sample">Sample · fixed seed 42</option></select></label><label>Temperature<select id="life-temperature" value={temperature} onChange={e=>{setTemperature(Number(e.target.value));setStep(0);}}>{[.75,1,1.5].map(t=><option key={t} value={t}>{t}</option>)}</select></label><label>Maximum new tokens<select id="life-limit" value={limit} onChange={e=>{setLimit(Number(e.target.value));setStep(0);}}>{[1,4,8].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div>
    <p className="lab-note">Current SFT setup: {mask==='reply'?'reply-only':'all-token'} loss, {steps} updates. Inference controls never update weights. Temperature changes probabilities; greedy ranking stays the same for positive temperatures.</p>
    <p>Formatted prefix: <code data-life="prefix">{g.prefix.join(' ')}</code></p>
    <div className="life-result" aria-live="polite"><span className="eyebrow">GENERATED TEXT</span><p data-life="text">{g.text||'(empty reply)'}</p><p className="life-token-line" data-life="tokens">{g.tokens.join(' → ')}</p><span data-life="stop">{g.stop}</span> · {g.tokens.length} new tokens, including any end token</div>
    <h4>Replay one prediction</h4><div className="life-replay" role="group" aria-label="Generated token steps">{g.trace.map((row,i)=><button key={i} className="small-button" aria-pressed={index===i} onClick={()=>setStep(i)}>{i+1} · {row.token}</button>)}</div>
    <div className="life-insight"><p>Context used: <code data-life="context">{selected.context}</code><br/>Chosen token: <strong data-life="chosen">{selected.token}</strong></p><p>Base probability: <strong data-life="base">{pct(selected.base[selected.id])}</strong><br/>After temperature: <strong data-life="probability">{pct(selected.probabilities[selected.id])}</strong><br/>Random draw: <strong data-life="draw">{selected.draw===null?'None · greedy':selected.draw.toFixed(8)}</strong></p><p>{selected.known_context?'This context has a stored logit row; an untrained row remains uniform.':'Unseen context: the demonstration model falls back to uniform probabilities.'}</p></div>
    <div className="life-table" role="region" aria-label="Top five candidate tokens" tabIndex={0}><table><thead><tr><th>Top 5 of 15 tokens</th><th>Adjusted probability</th></tr></thead><tbody>{candidates.map(c=><tr key={c.id}><td><code>{c.token}</code></td><td>{pct(c.p)}</td></tr>)}</tbody></table></div>
    <p className="lab-note">Sampling draws from all 15 tokens in vocabulary order, not just the five displayed. Ties in greedy mode use the lowest token ID. End token stops immediately, even on the last allowed step. There is no top-k filter, KV cache, or preference optimization in this workbook.</p>
   </div>
   <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset experiment</button><button className="small-button" onClick={download}>Download calculation report</button></div>
  </div>
  <div className="print-only"><p>Default: 80 full-batch pretraining updates, then 80 reply-only SFT updates. The 15-token model conditions only on the previous two tokens. The learning rate is 3; each step averages the loss across the selected targets.</p><table><thead><tr><th>Checkpoint</th><th>Prose loss</th><th>Reply loss</th></tr></thead><tbody>{printed.stages.map(s=><tr key={s.name}><td>{names[s.name]}</td><td>{f(s.pretrain_loss)}</td><td>{f(s.reply_loss)}</td></tr>)}</tbody></table><p>The reply-only mask excludes the three prompt targets and scores the four reply targets in each demonstration. Across four demonstrations, that is 16 targets per update; all-token training scores 28.</p><p>Frozen SFT checkpoint + comedy prompt + greedy selection → <strong>Moonlight → Map → . → &lt;eos&gt;</strong>. Visible reply: <strong>Moonlight Map.</strong> The first reply-token probability rises from 6.67% before SFT to 96.42% afterward. A one-token limit returns “Moonlight” and stops at the limit; a four-token limit reaches the end token.</p><p>With all-token SFT for 80 updates, prose loss rises to 1.1543 while reply loss falls to 0.0715. These are training-set measurements from independent context tables, not evidence about a real LLM's generalization.</p></div>
 </section>;
}
