import {useState} from 'react';
import {data,match,sampleVideo} from '../lib/multimodal.mjs';
import '../styles/multimodal.css';
const f=(n:number)=>n.toFixed(4),times=(ns:number[])=>ns.length?ns.join(', ')+' s':'none';
export default function MultimodalLab(){
 const [view,setView]=useState(1),[query,setQuery]=useState('calm'),[space,setSpace]=useState('aligned'),[temperature,setTemperature]=useState(.5),[candidates,setCandidates]=useState('all');
 const [interval,setInterval]=useState(4),[phase,setPhase]=useState(0),[resolution,setResolution]=useState(224),[alignAudio,setAlignAudio]=useState(true);
 const m=match(query,space,temperature,candidates),v=sampleVideo(interval,phase,resolution,alignAudio);
 function reset(){setView(1);setQuery('calm');setSpace('aligned');setTemperature(.5);setCandidates('all');setInterval(4);setPhase(0);setResolution(224);setAlignAudio(true);}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({matching:m,video:v},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='chapter-30-multimodal-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const tx=(t:number)=>140+t*25;
 return <section className="lab multimodal-lab" aria-labelledby="multimodal-title">
  <div className="lab-top"><span className="eyebrow">ALIGN. SAMPLE. TRACE.</span><span className="lab-tag">Toy vectors and annotations · no model loaded</span></div>
  <h3 id="multimodal-title">Match meanings. Keep the timeline.</h3><p>Inspect cross-modal scores and a synthetic trailer. The calculations are real; the embeddings and scene descriptions are hand-set teaching data.</p>
  <div className="screen-only">
   <div className="multi-tabs"><button className="small-button" aria-pressed={view===1} onClick={()=>setView(1)}>1 · Match text and posters</button><button className="small-button" aria-pressed={view===2} onClick={()=>setView(2)}>2 · Sample a trailer</button></div>
   <div hidden={view!==1}>
    <p className="lab-note">Three-dimensional vectors stand in for learned embeddings. “Mismatched” rotates only image coordinates from [x, y, z] to [z, x, y], leaving text unchanged. No encoder is trained here, and vector coordinates have no assigned human meaning.</p>
    <div className="multi-controls"><label htmlFor="multi-query">Text query<select id="multi-query" value={query} onChange={e=>setQuery(e.target.value)}>{data.queries.map(q=><option key={q.id} value={q.id}>{q.text}</option>)}</select></label><label htmlFor="multi-space">Encoder compatibility<select id="multi-space" value={space} onChange={e=>setSpace(e.target.value)}><option value="aligned">Aligned pair</option><option value="mismatched">Mismatched image encoder</option></select></label><label htmlFor="multi-temperature">Softmax temperature τ<select id="multi-temperature" value={temperature} onChange={e=>setTemperature(+e.target.value)}>{[.1,.5,1].map(n=><option key={n}>{n}</option>)}</select></label><label htmlFor="multi-candidates">Candidate posters<select id="multi-candidates" value={candidates} onChange={e=>setCandidates(e.target.value)}><option value="all">All three posters</option><option value="earth">Moonlight Map + Neon Chase</option><option value="moon">Moonlight Map only</option></select></label></div>
    <div className="multi-insight" aria-live="polite"><p>Highest similarity: <strong data-multi="winner">{m.rows[0].title}</strong>.</p><p>{space==='aligned'?'These hand-set vectors illustrate a compatible space. Similarity ranks a candidate; it does not verify a movie fact.':'Dimensions still match, but the coordinate systems no longer align. The resulting ranking can favor the wrong poster.'}</p><p className="lab-note">Softmax shares sum to 100% over the selected candidates. They are not calibrated confidence in relevance. Lowering τ sharpens the shares without changing this fixed-vector ranking.</p></div>
    <div className="multi-results">{m.rows.map((row:{id:string;title:string;score:number;share:number})=><article className="multi-result" key={row.id} data-poster={row.id}><h4>{row.title}</h4><p>{data.posters.find(p=>p.id===row.id)?.description}</p><p>Cosine similarity: <strong data-score={row.id}>{f(row.score)}</strong> · softmax share: <strong data-share={row.id}>{(row.share*100).toFixed(2)}%</strong></p><div className="multi-bar" aria-hidden="true"><span style={{width:Number((row.share*100).toFixed(4))+'%'}}/></div></article>)}</div>
    <details className="workshop-detail"><summary>Inspect vectors and the calculation</summary><p>Query vector: [{m.queryVector.join(', ')}]. Cosine = dot product divided by both vector norms. Share = exp(score/τ) divided by the sum of exp(score/τ) across the selected candidates.</p><div className="multi-table"><table><thead><tr><th>Poster</th><th>Image vector</th></tr></thead><tbody>{m.rows.map((row:{id:string;title:string;vector:number[]})=><tr key={row.id}><td>{row.title}</td><td>[{row.vector.join(', ')}]</td></tr>)}</tbody></table></div><p>The implementation subtracts the largest logit before exponentiating for numerical stability; the shares are unchanged.</p></details>
   </div>
   <div hidden={view!==2}>
    <p className="lab-note">The invented trailer lasts 20 seconds. Its complete annotations show a lantern only in [5, 6) seconds. Each selected frame is described perfectly here to isolate coverage; a real recognition model may still miss a visible object.</p>
    <div className="multi-controls"><label htmlFor="multi-interval">Frame interval (seconds)<select id="multi-interval" value={interval} onChange={e=>setInterval(+e.target.value)}>{[1,2,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label htmlFor="multi-resolution">Square frame size (pixels)<select id="multi-resolution" value={resolution} onChange={e=>setResolution(+e.target.value)}>{[224,448].map(n=><option key={n}>{n}</option>)}</select></label><label htmlFor="multi-audio">Map clip-local audio times<select id="multi-audio" value={alignAudio?'mapped':'local'} onChange={e=>setAlignAudio(e.target.value==='mapped')}><option value="mapped">Apply the required +4-second offset</option><option value="local">Omit the offset (incorrect)</option></select></label></div>
    <div className="slider-row"><label htmlFor="multi-phase">Sampling phase <output>{phase}</output></label><input id="multi-phase" type="range" min="0" max="0.75" step="0.25" value={phase} onChange={e=>setPhase(+e.target.value)}/><p className="lab-note">First frame = phase × interval. Then sample every interval while time is less than 20 seconds. Phase 0.25 with a four-second interval starts at one second.</p></div>
    <div className="multi-insight" aria-live="polite"><p><strong data-multi="observed">{v.observed?'Lantern observed in sampled frames':'Lantern not observed in sampled frames'}</strong>. Hit times: <strong data-multi="hits">{times(v.hitTimes)}</strong>.</p><p><strong data-multi="frame-count">{v.frames.length}</strong> frames × <strong data-multi="patches">{v.patchesPerFrame}</strong> patch positions = <strong data-multi="total">{v.totalPatches}</strong> total.</p><p className="lab-note">This counts only 16 × 16 image patches, with no special tokens, pooling, or audio. It is not a provider token count or a complete compute estimate. Higher resolution changes spatial detail, not temporal coverage.</p></div>
    <div className="multi-timeline" tabIndex={0} role="region" aria-label="Trailer timeline; scroll horizontally on small screens"><svg viewBox="0 0 680 225" role="img" aria-labelledby="multi-time-title multi-time-desc"><title id="multi-time-title">Source scenes, sampled frames, and mapped audio</title><desc id="multi-time-desc">The known lantern interval is 5 to 6 seconds. Samples occur at {times(v.frames.map((r:{time:number})=>r.time))}. The reported audio interval is {v.audio.start.toFixed(1)} to {v.audio.end.toFixed(1)} seconds. {alignAudio?'Its source offset is applied.':'Its source offset is incorrectly omitted.'}</desc>
     {data.trailer.scenes.map(s=><g key={s.label}><rect x={tx(s.start)} y="35" width={(s.end-s.start)*25} height="28" fill={s.label==='Lantern'?'var(--gold)':'var(--accent-soft)'} stroke="var(--line)"/>{s.end-s.start>2&&<text x={tx((s.start+s.end)/2)} y="54" textAnchor="middle">{s.label}</text>}</g>)}
     <text x="120" y="54" textAnchor="end">Known scenes</text><text x="120" y="108" textAnchor="end">Sampled frames</text><text x="120" y="160" textAnchor="end">Transcript line</text><path d="M140 103 H640" stroke="var(--line)"/>
     {v.frames.map((r:{time:number;event:boolean})=><circle key={r.time} cx={tx(r.time)} cy="103" r="5" fill={r.event?'var(--gold)':'var(--accent)'}><title>{`${r.time} seconds${r.event?': lantern observed':''}`}</title></circle>)}
     <rect x={tx(v.audio.start)} y="142" width={(v.audio.end-v.audio.start)*25} height="24" fill="var(--accent-soft)" stroke="var(--accent)" strokeDasharray={alignAudio?undefined:'4 3'}/>
     {[0,5,10,15,20].map(t=><g key={t}><path d={`M${tx(t)} 180 V186`} stroke="var(--muted)"/><text x={tx(t)} y="202" textAnchor="middle">{`${t}s`}</text></g>)}
    </svg></div><p className="lab-note">Gold scene band: the known lantern event. Dots: inspected frames. The full annotation is available only because this is a teaching example.</p>
    <div className="multi-insight"><p>Clip-local transcript: 0.8–2.2 s. The clip begins at source 4 s.</p><p>Reported source interval: <strong data-multi="audio-time">{v.audio.start.toFixed(1)}–{v.audio.end.toFixed(1)} s</strong>. Sampled frames in that interval: <strong data-multi="audio-overlap">{times(v.audio.overlapFrames)}</strong>.</p><p>“{v.audio.text}”</p><p className="lab-note">{alignAudio?'The clock mapping is correct. The line mentions a lantern; visual evidence must still establish whether it is shown.':'The omitted offset points to the wrong part of the original trailer. More frames or higher resolution cannot repair this clock error.'}</p></div>
    <details className="workshop-detail"><summary>Inspect every selected frame</summary><div className="multi-table multi-trace"><table><thead><tr><th>Source time</th><th>Prewritten annotation</th></tr></thead><tbody>{v.frames.map((r:{time:number;caption:string})=><tr key={r.time}><td>{r.time} s</td><td>{r.caption}</td></tr>)}</tbody></table></div></details>
   </div>
   <div className="workshop-actions"><button className="small-button" onClick={download}>Download multimodal report</button><button className="small-button" onClick={reset}>Reset experiment</button></div>
  </div>
  <div className="print-only"><p><strong>Alignment:</strong> equal vector dimensions do not guarantee compatible encoders. With a single candidate, softmax assigns it 100% regardless of relevance. Lowering temperature sharpens shares but does not change the ranking of fixed cosine scores.</p><p><strong>Video example:</strong> the known lantern interval is [5, 6) seconds. Use a four-second sampling interval and 224 × 224 frames with 16 × 16 patches.</p><table><thead><tr><th>Phase</th><th>Sample times (seconds)</th><th>Lantern seen?</th><th>Patch positions</th></tr></thead><tbody><tr><td>0</td><td>0, 4, 8, 12, 16</td><td>No</td><td>980</td></tr><tr><td>0.25</td><td>1, 5, 9, 13, 17</td><td>Yes, at 5</td><td>980</td></tr></tbody></table><p>Each frame has 196 patch positions. At 448 × 448, the same five frames have 3,920 in total; the sampled times do not change. A clip starting at source 4 seconds maps local 0.8–2.2 seconds to source 4.8–6.2 seconds. A transcript mention is not proof of a visible object.</p></div>
 </section>;
}
