import {useMemo,useState} from 'react';
import {train,movies,sampleGradient} from '../lib/neural-network.mjs';
const fixed=(n:number)=>n.toFixed(4);
export default function NeuralNetworkLab(){
 const [architecture,setArchitecture]=useState('hidden'),[steps,setSteps]=useState(0),[rate,setRate]=useState(0.5),[movieId,setMovie]=useState('N1');
 const r=useMemo(()=>train(architecture,steps,rate)!,[architecture,steps,rate]);
 const movie=movies.find(m=>m.id===movieId)!;const f=sampleGradient(r.theta,movie.x,movie.y);
 const maxLoss=Math.max(0.75,...r.history.map(p=>p.loss));
 const points=r.history.map(p=>`${55+530*p.step/Math.max(steps,1)},${190-150*p.loss/maxLoss}`).join(' ');
 function reset(){setArchitecture('hidden');setSteps(0);setRate(0.5);setMovie('N1');}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-20-neural-network.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab neural-lab" aria-label="Neural network workbench">
  <div className="lab-top"><span className="eyebrow">FOLLOW THE NUMBERS.</span><span className="lab-tag">Real local training · 4 fictional movies</span></div>
  <h3>Same preferences. Different capacity.</h3>
  <p>A viewer likes exactly one of adventure and romance. Compare a sigmoid of a linear score with a 2 → 3 → 1 tanh network. Every row below is training data; there is no test score.</p>
  <div className="screen-only">
   <div className="training-controls"><label>Architecture<select id="nn-architecture" value={architecture} onChange={e=>{setArchitecture(e.target.value);setSteps(0);}}><option value="hidden">Hidden layer · 13 parameters</option><option value="linear">Linear score + sigmoid · 3 parameters</option></select></label><label>Learning rate<select id="nn-rate" value={rate} onChange={e=>{setRate(Number(e.target.value));setSteps(0);}}>{[0.1,0.5,2].map(v=><option key={v} value={v}>{v}{v===0.5?' · default':''}</option>)}</select></label></div>
   <div className="workshop-actions"><button className="small-button" disabled={steps===2000} onClick={()=>setSteps(Math.min(2000,steps+1))}>Train 1 step</button><button className="small-button" disabled={steps===2000} onClick={()=>setSteps(Math.min(2000,steps+100))}>Train 100 steps</button><button className="small-button" disabled={steps===2000} onClick={()=>setSteps(2000)}>Train to 2,000</button><button className="small-button" onClick={reset}>Reset network</button></div>
   <p className="lab-note">One step uses the mean gradient of all four rows. Each step is also one epoch here. Changing architecture or learning rate restarts its fixed initialization. Training stops at 2,000 steps; that is a display limit, not a convergence guarantee.</p>
   <div className="lab-metrics nn-metrics" aria-live="polite"><div><strong data-nn="steps">{r.steps}</strong><span>Training steps</span></div><div><strong data-nn="loss">{fixed(r.loss)}</strong><span>Mean training log loss</span></div><div><strong data-nn="accuracy">{(100*r.accuracy).toFixed(0)}%</strong><span>Training accuracy</span></div></div>
   <div className="nn-chart"><svg viewBox="0 0 630 245" role="img" aria-labelledby="nn-loss-title nn-loss-desc"><title id="nn-loss-title">Mean training loss over completed steps</title><desc id="nn-loss-desc">Loss starts at {fixed(r.history[0].loss)} and is {fixed(r.loss)} at step {steps}. Points are recorded every 20 steps and at the selected final step.</desc><path d="M55 30V190H590" fill="none" stroke="var(--muted)"/><line x1="55" x2="590" y1={190-150*Math.log(2)/maxLoss} y2={190-150*Math.log(2)/maxLoss} stroke="var(--muted)" stroke-dasharray="4 4"/><text x="590" y={183-150*Math.log(2)/maxLoss} textAnchor="end">ln(2): p = 0.5 everywhere</text><polyline points={points} fill="none" stroke="var(--accent)" strokeWidth="2.8"/>{r.history.length===1&&<circle cx="55" cy={190-150*r.loss/maxLoss} r="4" fill="var(--accent)"/>}<text x="44" y="194" textAnchor="end">0</text><text x="44" y="45" textAnchor="end">{maxLoss.toFixed(2)}</text><text x="55" y="213">0</text><text x="585" y="213" textAnchor="end">{steps||'No updates yet'}</text><text x="320" y="237" textAnchor="middle">Completed training steps</text></svg></div>
   <div className="nn-table" role="region" aria-label="Training movie predictions" tabIndex={0}><table><thead><tr><th>Movie · (adventure, romance)</th><th>Label</th><th>p(like)</th><th>Decision</th></tr></thead><tbody>{r.rows.map(m=><tr key={m.id} data-movie={m.id}><td>{m.title}<small>({m.x.join(', ')})</small></td><td>{m.y?'Like':'Dislike'}</td><td data-nn-prob={m.id}>{fixed(m.p)}</td><td>{m.predicted?'Like':'Dislike'}{m.predicted!==m.y?' ✕':' ✓'}</td></tr>)}</tbody></table></div>
   <p className="lab-note">Decision: like if p ≥ 0.5, using the unrounded value. Near 0.5, tiny numerical differences may change a label while the loss barely changes. Read the probabilities and loss as well as accuracy.</p>
   <details className="workshop-detail nn-trace"><summary>Trace one movie through the current network</summary><label>Movie<select id="nn-movie" value={movieId} onChange={e=>setMovie(e.target.value)}>{movies.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label>
    <dl className="nn-trace-values"><dt>Input x / known label y</dt><dd>({movie.x.join(', ')}) / {movie.y}</dd>{f.h.length>0&&<><dt>Hidden sums a</dt><dd data-nn="hidden-sums">{f.a.map(fixed).join(', ')}</dd><dt>Hidden activations tanh(a)</dt><dd>{f.h.map(fixed).join(', ')}</dd></>}<dt>Output logit z / probability p</dt><dd data-nn="trace-output">{fixed(f.z)} / {fixed(f.p)}</dd><dt>This row's loss / output gradient p − y</dt><dd>{fixed(f.loss)} / {fixed(f.p-movie.y)}</dd></dl>
    <p className="lab-note">The label is used only to compute loss and gradients; it does not enter the forward calculation. Gradients below average all four rows, so they differ from this row's gradient.</p>
    <div className="nn-table" role="region" aria-label="Parameters and mean loss gradients" tabIndex={0}><table><thead><tr><th>Parameter</th><th>Current</th><th>Mean gradient</th><th>Next update Δ</th></tr></thead><tbody>{r.theta.map((v,i)=><tr key={i}><td>{architecture==='linear'?['w₁','w₂','b'][i]:i<9?`h${Math.floor(i/3)+1} ${['w₁','w₂','bias'][i%3]}`:i<12?`v${i-8}`:'output bias'}</td><td>{fixed(v)}</td><td>{fixed(r.gradient[i])}</td><td>{fixed(-rate*r.gradient[i])}</td></tr>)}</tbody></table></div><p className="lab-note">“Next update” is a preview; opening this trace does not apply it. Negative gradient means gradient descent increases that parameter.</p>
   </details>
   <div className="workshop-actions"><button className="small-button" onClick={download}>Download training report</button></div>
  </div>
  <div className="print-only"><p>Fixed initialization, learning rate 0.5, all four rows in each update:</p><table><thead><tr><th>Model / steps</th><th>Mean training loss</th><th>Training accuracy</th></tr></thead><tbody>{[['linear',0],['linear',2000],['hidden',0],['hidden',2000]].map(([a,n])=>{const v=train(String(a),Number(n),0.5)!;return <tr key={a+'-'+n}><td>{a==='hidden'?'Tanh network':'Linear score'} / {n}</td><td>{fixed(v.loss)}</td><td>{(100*v.accuracy).toFixed(0)}%</td></tr>;})}</tbody></table><p>After 2,000 steps, the tanh network's probabilities for N1–N4 are approximately 0.9968, 0.9968, 0.0043, and 0.0003. The linear model approaches 0.5 for all four. These are fitted training predictions, not calibrated probabilities for real viewers.</p><p>Initial N1 trace: hidden sums (0.7, −0.5, 0.75), hidden activations (0.6044, −0.4621, 0.6351), logit 0.5634, probability 0.6372, loss 0.4506. The single-row first-weight gradient is −0.0921; the full-batch mean gradient is +0.0256.</p></div>
 </section>;
}
