import {useState} from 'react';
import {defaults,evaluate} from '../lib/operations.mjs';
import '../styles/operations.css';
type Config={scenario:string;share:number;retries:number;deadline:number;rollback:string};
const decisions:Record<string,string>={rolled_back:'Rolled back',review_needed:'Review needed',baseline_only:'Baseline only',observe_more:'Keep observing',rollback_next_window:'Rollback from next window',observe:'Observe'};
export default function OperationsLab(){
 const [config,setConfig]=useState<Config>({...defaults}),[selected,setSelected]=useState('R01');
 const r=evaluate(config),t=r.totals,chosen=r.rows.find(row=>row.id===selected)||r.rows[0];
 function change(key:keyof Config,value:string|number){setConfig({...config,[key]:value});}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-36-operations-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab operations-lab" aria-labelledby="operations-title">
 <div className="lab-top"><span className="eyebrow">RELEASE. OBSERVE. RECOVER.</span><span className="lab-tag">Local simulation · no deployment</span></div>
 <h3 id="operations-title">Twenty requests. A release decision.</h3><p>Route authored movie requests across four windows of five. Timings, quality labels, and costs are fictional. Checks run at each window end; rollback affects subsequent requests.</p>
 <div className="screen-only">
 <div className="operations-controls">
 <label htmlFor="ops-scenario">Operating conditions<select id="ops-scenario" value={config.scenario} onChange={e=>change('scenario',e.target.value)}><option value="healthy">Healthy versions</option><option value="bad_release">Candidate recommends the wrong movie</option><option value="provider_fault">Shared provider faults</option></select></label>
 <label htmlFor="ops-share">Planned candidate traffic<select id="ops-share" value={config.share} onChange={e=>change('share',+e.target.value)}>{[0,20,60,100].map(n=><option key={n} value={n}>{n}% of each window before rollback</option>)}</select></label>
 <label htmlFor="ops-retries">Retries after a simulated 503<select id="ops-retries" value={config.retries} onChange={e=>change('retries',+e.target.value)}><option value="0">No retry</option><option value="1">At most one retry</option></select></label>
 <label htmlFor="ops-deadline">Total request deadline<select id="ops-deadline" value={config.deadline} onChange={e=>change('deadline',+e.target.value)}><option value="1200">1200 ms, including backoff</option><option value="2400">2400 ms, including backoff</option></select></label>
 <label htmlFor="ops-rollback">Response to a bad candidate result<select id="ops-rollback" value={config.rollback} onChange={e=>change('rollback',e.target.value)}><option value="automatic">Rollback at the window boundary</option><option value="observe">Observe only; keep routing</option></select></label>
 </div>
 <div className="operations-stats" aria-live="polite"><div><span>Good requests · quality + deadline</span><strong data-ops="good">{t.good}/{t.n}</strong><small>{t.goodPercent?.toFixed(1)}% useful, timely responses</small></div><div><span>Final HTTP 200</span><strong data-ops="http">{t.httpOk}/{t.n}</strong><small>A transport result, not a quality score</small></div><div><span>Actually sent to candidate</span><strong data-ops="candidate">{t.candidate}</strong><small>Rollback can reduce planned exposure</small></div><div><span>Provider attempts</span><strong data-ops="attempts">{t.attempts}</strong><small>Includes failed and timed-out attempts</small></div><div><span>Total fictional cost</span><strong data-ops="cost">{t.costUnits}</strong><small>Reserved units per attempted call</small></div><div><span>p95 final elapsed time</span><strong data-ops="p95">{t.p95} ms</strong><small>Includes failures and retry backoff</small></div></div>
 <div className="operations-status" role="status"><h4>Rollout: <span data-ops="decision">{decisions[r.decision]}</span></h4><p>Teaching SLO: at least 95% good requests. Allowed bad: {r.allowedBad}; observed bad: {t.bad}; remaining budget: <strong data-ops="budget">{r.budgetRemaining}</strong>. <span data-ops="slo">{r.sloMet?'SLO met':'SLO missed'}</span>.</p><p>{r.rollbackAfter?`Rollback decided after window ${r.rollbackAfter}. Earlier results remain in the totals.`:'No automatic promotion occurs. This small fixture run cannot approve production.'}</p></div>
 <div className="operations-table" role="region" aria-label="Rollout windows" tabIndex={0}><table><thead><tr><th>Window</th><th>Candidate</th><th>Good / all</th><th>Next action</th></tr></thead><tbody>{r.windows.map(w=><tr key={w.window}><td>{w.window}</td><td>{w.candidate}/5<small>{w.candidateBad} candidate failures</small></td><td>{w.good}/5</td><td>{decisions[w.action]}</td></tr>)}</tbody></table></div>
 <details className="operations-inspector"><summary>Inspect one request and its attempts</summary><label htmlFor="ops-record">Request<select id="ops-record" value={chosen.id} onChange={e=>setSelected(e.target.value)}>{r.rows.map(row=><option key={row.id} value={row.id}>{row.id} · {row.version} · {row.reason}</option>)}</select></label><pre>{JSON.stringify(chosen,null,2)}</pre></details>
 <p className="local-note">Assignment uses fixed slots, not random sampling. The simulator knows fixture quality immediately. It models no queue, real billing, model generation, circuit breaker, or fallback. Retry backoff is fixed at 200 ms.</p>
 <div className="workshop-actions"><button className="small-button" onClick={()=>{setConfig({...defaults});setSelected('R01');}}>Reset experiment</button><button className="small-button" onClick={download}>Download operations report</button></div>
 </div>
 <div className="print-only"><p><strong>Worked rollout:</strong> twenty movie requests, bad candidate release, 2400 ms deadline. All requests return HTTP 200, but some recommendations are wrong.</p><table><thead><tr><th>Policy</th><th>Good / 20</th><th>Candidate requests</th><th>Cost units</th></tr></thead><tbody><tr><td>20% share, observe only</td><td>16/20</td><td>4</td><td>56</td></tr><tr><td>20% share, automatic rollback</td><td>19/20</td><td>1</td><td>59</td></tr><tr><td>100% share, automatic rollback</td><td>18/20</td><td>5</td><td>55</td></tr></tbody></table><p>Rollback occurs after the first five-request window. Default 19/20 meets the teaching 95% SLO but stops the release. Under shared provider faults, one retry improves 12/20 to 16/20 good at 2400 ms; at 1200 ms it remains 12/20. Attempts increase from 20 to 28.</p></div>
 </section>;
}
