import {useState} from 'react';
import {dataset,compare,audit} from '../lib/rag-evaluation.mjs';
const pct=(v:number|null)=>v===null?'Undefined':(100*v).toFixed(2)+'%';
export default function RagEvaluationLab(){
 const [config,setConfig]=useState('wide'),[slice,setSlice]=useState('all'),[caseId,setCase]=useState('Q1'),[fixture,setFixture]=useState('complete');
 const r=compare(config,slice),a=audit(fixture),row=r.rows.find(q=>q.id===caseId)||r.rows[0];
 function reset(){setConfig('wide');setSlice('all');setCase('Q1');setFixture('complete');}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({comparison:r,audit:a},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='chapter-19-rag-evaluation.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const metrics=[['task_success','Task success'],['answer_coverage','Answer coverage'],['answered_accuracy','Accuracy when answering'],['false_answer_rate','False answers on missing facts'],['retrieval_recall','Required-fact retrieval recall'],['context_recall','Required-fact context recall'],['quote_support','Exact-quote support']] as const;
 return <section className="lab rag-eval-lab" aria-label="RAG evaluation workbench">
  <div className="lab-top"><span className="eyebrow">MEASURE THE TRADEOFF.</span><span className="lab-tag">8 teaching cases · no model calls</span></div>
  <h3>Better overall. Worse on one question.</h3>
  <p>Run the Chapter 18 pipeline on a public development set. BM25 and packing are real; answers use the same deterministic formatter. Reference facts grade the result afterward. This is not a held-out model benchmark.</p>
  <div className="screen-only">
   <div className="training-controls"><label>Candidate configuration<select id="rag-eval-config" value={config} onChange={e=>setConfig(e.target.value)}>{dataset.configurations.map(c=><option key={c.id} value={c.id}>{c.label} · K={c.k}, budget={c.budget}</option>)}</select></label><label>Question slice<select id="rag-eval-slice" value={slice} onChange={e=>setSlice(e.target.value)}><option value="all">All 8 questions</option><option value="answerable">6 answerable questions</option><option value="missing">2 missing-fact questions</option></select></label></div>
   <p className="eval-policy">Baseline A uses section chunks, K = 1, and a 50-word-unit evidence budget. B changes only K to 3; C reduces B's budget to 20. These word units are not model tokens.</p>
   <div className="lab-metrics rag-eval-metrics"><div><strong data-rag-eval="success">{r.candidate.successes}/{r.candidate.queries}</strong><span>Candidate successes</span></div><div><strong data-rag-eval="wins">{r.paired.wins} / {r.paired.losses}</strong><span>Wins / losses vs. A</span></div><div><strong data-rag-eval="delta">{r.paired.delta===null?'Undefined':`${r.paired.delta>=0?'+':''}${(r.paired.delta*100).toFixed(2)} pp`}</strong><span>Change in task success</span></div></div>
   <div className="rag-eval-table" tabIndex={0} role="region" aria-label="Configuration metrics"><table className="rag-eval-comparison"><thead><tr><th>Metric</th><th>Baseline A</th><th>Candidate</th></tr></thead><tbody>{metrics.map(([key,label])=><tr key={key}><th scope="row">{label}</th><td>{pct(r.baseline[key])}</td><td data-eval-metric={key}>{pct(r.candidate[key])}</td></tr>)}<tr><th scope="row">Mean evidence word units</th><td>{r.baseline.mean_evidence_units?.toFixed(2)??'Undefined'}</td><td data-eval-metric="units">{r.candidate.mean_evidence_units?.toFixed(2)??'Undefined'}</td></tr></tbody></table></div>
   <p className="lab-note">Retrieval/context recall average over answerable questions only. Quote support pools emitted quotes. Zero denominators are undefined; abstentions do not receive a perfect support score.</p>
   <p className="lab-note mobile-only">Scroll the question table sideways to see each diagnosis.</p><div className="rag-eval-table" tabIndex={0} role="region" aria-label="Per-question outcomes"><table className="rag-eval-rows"><thead><tr><th>Question</th><th>Result</th><th>First issue or outcome</th></tr></thead><tbody>{r.rows.map(q=><tr key={q.id} data-case-id={q.id}><td><strong>{q.id}</strong> {q.question}</td><td>{q.success?'Pass':'Fail'}</td><td>{q.diagnosis}</td></tr>)}</tbody></table></div>
   <details className="workshop-detail eval-case"><summary>Inspect a question's evidence and grading</summary><label className="eval-case-select">Question<select id="rag-eval-case" value={row?.id||''} onChange={e=>setCase(e.target.value)}>{r.rows.map(q=><option key={q.id} value={q.id}>{q.id} · {q.question}</option>)}</select></label>{row&&<><p><strong>Reference facts:</strong> <span data-rag-eval="gold">{row.gold.join(', ')||'None: requested fact absent from this snapshot'}</span></p><p><strong>Retrieved:</strong> {row.retrieved_facts.join(', ')||'No required facts'}<br/><strong>Packed:</strong> {row.packed_facts.join(', ')||'No required facts'}</p><div className="eval-case-answer"><strong>Formatter output</strong>{row.claims.length?row.claims.map((c,i)=><p key={i}>{c.title}: “{c.quote}” <small>[{c.source_id}]</small></p>):<p>Insufficient evidence.</p>}</div><p><strong>Diagnosis:</strong> <span data-rag-eval="diagnosis">{row.diagnosis}</span></p><pre>{JSON.stringify({candidates:row.trace.candidates.map(c=>c.id),packed:row.trace.context.selected.map(c=>c.id),omitted:row.trace.context.omitted,covered_facts:row.covered_facts},null,2)}</pre></>}</details>
   <div className="eval-audit"><span className="eyebrow">A DIFFERENT QUESTION: DOES THE CITATION SUPPORT IT?</span><h4>Audit an authored answer</h4><p>{a.question}</p><label>Answer fixture<select id="rag-eval-audit" value={fixture} onChange={e=>setFixture(e.target.value)}>{dataset.audit.fixtures.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label>
    <div className="eval-audit-claims">{a.claims.map((c,i)=><p key={i}>{c.text} <small>{c.citations.map(id=>`[${id}]`).join(' ')||'[no citation]'}</small></p>)}</div>
    <div className="rag-eval-table" tabIndex={0} role="region" aria-label="Citation audit metrics"><table className="rag-audit-metrics"><tbody>{([['context_support','Claims supported somewhere in context'],['valid_citation_ids','Existing citation IDs'],['citation_precision','Supporting citation links'],['citation_coverage','Claims with a supporting citation'],['required_fact_coverage','Required facts covered']] as const).map(([key,label])=><tr key={key}><th scope="row">{label}</th><td data-audit-metric={key}>{pct(a.metrics[key])}</td></tr>)}</tbody></table></div>
    <p data-rag-eval="audit-note">{a.note}</p><details className="workshop-detail audit-labels"><summary>Inspect sources and authored judgments</summary>{a.sources.map(s=><p key={s.id}><strong>{s.id}</strong><br/>{s.text}</p>)}<pre>{JSON.stringify(a.claims.map(c=>({claim:c.text,supported_by:c.supported_by,covers:c.covers})),null,2)}</pre></details><p className="lab-note">{a.annotation}</p>
   </div>
   <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset evaluation</button><button className="small-button" onClick={download}>Download evaluation report</button></div>
  </div>
  <div className="print-only"><p>All 8 questions: 6 answerable, 2 missing a requested fact. Same corpus, section chunks, and deterministic formatter in all configurations.</p><table><thead><tr><th>Configuration</th><th>Task success</th><th>Retrieval / context recall</th><th>False-answer rate</th></tr></thead><tbody><tr><td>A: K=1, budget 50</td><td>5/8 = 62.50%</td><td>50% / 50%</td><td>0/2 = 0%</td></tr><tr><td>B: K=3, budget 50</td><td>7/8 = 87.50%</td><td>100% / 100%</td><td>1/2 = 50%</td></tr><tr><td>C: K=3, budget 20</td><td>5/8 = 62.50%</td><td>100% / 50%</td><td>0/2 = 0%</td></tr></tbody></table><p>B has 3 wins, 1 loss, and 4 ties against A: +25 percentage points overall. Q5 is the loss: Unlisted Voyage's runtime is unknown, but the formatter returns Moonlight Map's 105-minute runtime. Every emitted quote is copied from context; that alone does not make it the right answer.</p><p>C finds the required evidence but loses some of it while packing. Mean evidence units are 11.875 for A, 39.75 for B, and 11.875 for C; these are not latency or token measurements.</p><p>Citation audit: a runtime-only answer can be fully supported yet cover only 1 of 2 requested facts. A wrong attached citation can have a valid ID and zero citation support. A true Winter Road fact can be correctly cited and cover none of the requested Quiet Orbit facts.</p></div>
 </section>;
}
