import {useState} from 'react';
import {defaults,evaluate} from '../lib/reasoning.mjs';
import '../styles/reasoning.css';
type Config={minutes:number;offline:string;evidence:string;prior:number;penalty:number};
const labels:Record<string,string>={recommend:'Recommend',abstain:'Skip for now',no_feasible_movie:'No feasible movie'};
export default function ReasoningLab(){
 const [config,setConfig]=useState<Config>({...defaults});const r=evaluate(config),chosen=r.rows.find(m=>m.id===r.chosen);
 function change(key:keyof Config,value:string|number){setConfig({...config,[key]:value});}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-37-reasoning-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab reasoning-lab" aria-labelledby="reasoning-title">
 <div className="lab-top"><span className="eyebrow">RULES. BELIEFS. CHOICES.</span><span className="lab-tag">Local model · fictional data</span></div>
 <h3 id="reasoning-title">Rules first. Then reason under uncertainty.</h3><p>Choose a film for a train journey. Enforce time and offline constraints, update a mood belief from trailer feedback, and compare expected utility with skipping.</p>
 <div className="screen-only">
 <div className="reasoning-controls">
 <label htmlFor="reason-minutes">Available movie time<select id="reason-minutes" value={config.minutes} onChange={e=>change('minutes',+e.target.value)}>{[80,100,120].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label>
 <label htmlFor="reason-offline">Playback constraint<select id="reason-offline" value={config.offline} onChange={e=>change('offline',e.target.value)}><option value="yes">Offline required</option><option value="no">Online allowed</option></select></label>
 <label htmlFor="reason-evidence">Sci-fi trailer feedback<select id="reason-evidence" value={config.evidence} onChange={e=>change('evidence',e.target.value)}><option value="unknown">Unknown / not observed</option><option value="liked">Liked</option><option value="disliked">Disliked</option></select></label>
 <label htmlFor="reason-prior">Prior probability of a sci-fi mood<select id="reason-prior" value={config.prior} onChange={e=>change('prior',+e.target.value)}>{[20,50,80].map(n=><option key={n} value={n}>{n}% before feedback</option>)}</select></label>
 <label htmlFor="reason-penalty">Cost of disappointment<select id="reason-penalty" value={config.penalty} onChange={e=>change('penalty',+e.target.value)}>{[1,4,10].map(n=><option key={n} value={n}>−{n} utility units</option>)}</select></label>
 </div>
 <div className="reasoning-stats" aria-live="polite"><div><span>Posterior sci-fi mood probability</span><strong data-reason="posterior">{(r.posterior*100).toFixed(2)}%</strong><small>Enjoyment is a separate probability</small></div><div><span>Eligible films</span><strong data-reason="eligible">{r.eligible}/4</strong><small>Must satisfy both hard constraints</small></div></div>
 <div className="reasoning-status" role="status"><h4 data-reason="decision">{labels[r.decision]}{chosen?`: ${chosen.title}`:''}</h4><p>Selected expected utility: <strong data-reason="utility">{r.bestUtility.toFixed(3)}</strong>. Enjoyment earns +5; disappointment costs {config.penalty}; skipping earns 0.</p><p>{r.decision==='no_feasible_movie'?'No film fits the constraints. Changing a belief cannot make a film shorter.':r.decision==='abstain'?'Films fit, but none beats skipping under the selected utilities.':`${chosen?.title} is feasible and has the highest positive utility. This is a result of authored assumptions, not a measured user preference.`}</p></div>
 <div className="reasoning-table" role="region" aria-label="Movie eligibility and expected utility" tabIndex={0}><table><thead><tr><th>Movie</th><th>Eligibility</th><th>P(enjoy)</th><th>Expected utility</th></tr></thead><tbody>{r.rows.map(m=><tr key={m.id}><td>{m.title}<small>{m.minutes} min · {m.downloaded?'downloaded':'online only'}</small></td><td>{m.eligible?'Eligible':m.reasons.join('; ')}</td><td>{(m.enjoyment*100).toFixed(2)}%</td><td>{m.utility.toFixed(3)}{m.id===r.chosen?' · selected':''}</td></tr>)}</tbody></table></div>
 <details className="reasoning-inspector"><summary>Inspect the probability model and search traces</summary><p>H = sci-fi mood. P(liked | H) = 0.8; P(liked | not H) = 0.2. Each row mixes its two enjoyment probabilities using the posterior. Unknown feedback gives no update.</p><pre>{JSON.stringify({posterior:r.posterior,movies:r.rows.map(m=>({title:m.title,enjoy_if_scifi:m.enjoy_if_scifi,enjoy_if_other:m.enjoy_if_other})),searches:r.searches},null,2)}</pre><p>The fixed preparation graph is separate from the controls. “Expanded” lists nodes popped, including the goal. BFS costs 10; UCS and A* cost 3.</p></details>
 <p className="local-note">Probabilities, costs, and movies are fictional. This lab enumerates four films; it does not train a model or run a general logic solver. Reports use six decimals. Ties prefer skipping at zero, then catalog order.</p>
 <div className="workshop-actions"><button className="small-button" onClick={()=>setConfig({...defaults})}>Reset experiment</button><button className="small-button" onClick={download}>Download reasoning report</button></div>
 </div>
 <div className="print-only"><p><strong>Worked decision:</strong> 100 minutes, offline required, prior 50%, liked trailer, disappointment cost 4. The posterior is 80%; only the first two films are eligible.</p><table><thead><tr><th>Movie</th><th>P(enjoy)</th><th>Expected utility</th><th>Allowed?</th></tr></thead><tbody><tr><td>Quiet Orbit</td><td>78%</td><td>3.02</td><td>Yes · chosen</td></tr><tr><td>Lantern Lane</td><td>48%</td><td>0.32</td><td>Yes</td></tr><tr><td>Comet Chase</td><td>86.4%</td><td>3.776</td><td>No · time + offline</td></tr><tr><td>Silent Harbor</td><td>58%</td><td>1.22</td><td>No · time</td></tr></tbody></table><p>At 120 minutes with online access, Comet Chase wins. At default time with unknown feedback and penalty 10, both eligible utilities are −1: skip. At 80 minutes, no film is feasible. Separate graph: BFS cost 10; UCS and A* cost 3.</p></div>
 </section>;
}
