import {useMemo,useState} from 'react';
import {defaults,evaluate} from '../lib/reinforcement.mjs';
import '../styles/reinforcement.css';
type Config={objective:string;epsilon:number;gamma:number;alpha:number;episodes:number;seed:number};
export default function ReinforcementLab(){
 const [config,setConfig]=useState<Config>({...defaults});const r=useMemo(()=>evaluate(config),[config]);
 const points=r.curve.map((p,i)=>`${(42+i*638/(r.curve.length-1)).toFixed(3)},${(166-p.mean*22).toFixed(3)}`).join(' ');
 function change(key:keyof Config,value:string|number){setConfig({...config,[key]:value});}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-38-reinforcement-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab reinforcement-lab" aria-labelledby="reinforcement-title">
 <div className="lab-top"><span className="eyebrow">ACT. LEARN. TRY AGAIN.</span><span className="lab-tag">Local Q-learning · fictional viewers</span></div>
 <h3 id="reinforcement-title">Ask now. Recommend better later.</h3><p>Train a four-entry Q-table, then freeze it and evaluate greedily. Each control change starts a fresh seeded run. Rewards and transitions are deterministic; exploration is randomized.</p>
 <div className="screen-only">
 <div className="reinforcement-controls">
 <label htmlFor="rl-objective">Reward definition<select id="rl-objective" value={config.objective} onChange={e=>change('objective',e.target.value)}><option value="satisfaction">Satisfaction teaching score</option><option value="clicks">Click-proxy teaching score</option></select></label>
 <label htmlFor="rl-epsilon">Exploration probability ε<select id="rl-epsilon" value={config.epsilon} onChange={e=>change('epsilon',+e.target.value)}>{[0,.1,.3].map(n=><option key={n} value={n}>{n*100}% random-action branch</option>)}</select></label>
 <label htmlFor="rl-gamma">Future-reward discount γ<select id="rl-gamma" value={config.gamma} onChange={e=>change('gamma',+e.target.value)}>{[0,.5,.9].map(n=><option key={n} value={n}>{n} · {n===0?'next reward only':`${n*100}% weight per next step`}</option>)}</select></label>
 <label htmlFor="rl-alpha">Learning rate α<select id="rl-alpha" value={config.alpha} onChange={e=>change('alpha',+e.target.value)}>{[.1,.5].map(n=><option key={n} value={n}>{n} · move {n*100}% toward each target</option>)}</select></label>
 <label htmlFor="rl-episodes">Training episodes<select id="rl-episodes" value={config.episodes} onChange={e=>change('episodes',+e.target.value)}>{[60,200].map(n=><option key={n} value={n}>{n} movie sessions</option>)}</select></label>
 <label htmlFor="rl-seed">Exploration seed<select id="rl-seed" value={config.seed} onChange={e=>change('seed',+e.target.value)}>{[7,19].map(n=><option key={n} value={n}>Seed {n}</option>)}</select></label>
 </div>
 <div className="reinforcement-stats" aria-live="polite"><div><span>Greedy discounted return</span><strong data-rl="discounted">{r.greedy.discounted.toFixed(3)}</strong><small>Chosen reward, weighted by γ</small></div><div><span>Greedy satisfaction return</span><strong data-rl="satisfaction">{r.greedy.satisfaction}</strong><small>Undiscounted, on a fixed scale</small></div><div><span>Mean training return</span><strong data-rl="training">{r.trainingMean.toFixed(3)}</strong><small>Undiscounted, with exploration</small></div><div><span>Gap to best discounted return</span><strong data-rl="gap">{r.gap.toFixed(3)}</strong><small>Known only to this toy evaluator</small></div></div>
 <div className="reinforcement-status" role="status"><h4>Frozen greedy policy</h4><p data-rl="path">{r.greedy.trace.map(a=>a.label).join(' → ')}</p><p>Total selected-objective reward: <strong data-rl="total">{r.greedy.total}</strong>. <span data-rl="status">{r.gap===0?'Matches a best route in this model.':'Has not found a best route for this objective.'}</span></p><p>Training used <span data-rl="steps">{r.steps}</span> transitions and <span data-rl="explorations">{r.exploratorySteps}</span> random-action selections. A random selection may choose the greedy action too.</p></div>
 <div className="rl-curve"><h4>Training return, averaged in blocks of 20</h4><svg viewBox="0 0 720 210" role="img" aria-labelledby="rl-curve-title rl-curve-desc"><title id="rl-curve-title">Mean undiscounted training return</title><desc id="rl-curve-desc">Each point averages twenty sequential training episodes. This is one seeded run, not an uncertainty interval or a held-out evaluation.</desc>{[0,2,4,6].map(v=><g key={v}><line x1="42" y1={166-v*22} x2="680" y2={166-v*22} stroke="var(--line)"/><text x="30" y={170-v*22} textAnchor="end" fill="var(--muted)" fontSize="12">{v}</text></g>)}<polyline fill="none" stroke="var(--accent)" strokeWidth="3" points={points}/>{r.curve.map((p,i)=><circle key={p.episode} cx={+(42+i*638/(r.curve.length-1)).toFixed(3)} cy={+(166-p.mean*22).toFixed(3)} r="4" fill="var(--accent)"><title>{`Through episode ${p.episode}: mean ${p.mean}`}</title></circle>)}<text x="42" y="195" fill="var(--muted)" fontSize="12">Episode 20</text><text x="680" y="195" textAnchor="end" fill="var(--muted)" fontSize="12">{`Episode ${config.episodes}`}</text></svg><p className="local-note">Scores can fluctuate while exploring. A rising curve alone does not prove generalization or safety.</p></div>
 <div className="reinforcement-table" role="region" aria-label="Learned action values and visits" tabIndex={0}><table><thead><tr><th>State / action</th><th>Learned Q</th><th>Visits</th><th>Optimal Q in model</th></tr></thead><tbody>{r.rows.map(a=><tr key={a.state+a.action}><td>{a.label}<small>{a.state==='start'?'Start':'Preference known'}</small></td><td>{a.q.toFixed(3)}</td><td>{a.visits}</td><td>{a.optimalQ.toFixed(3)}</td></tr>)}</tbody></table></div>
 <details className="reinforcement-inspector"><summary>Inspect the first twelve learning updates</summary><p>Each record shows the old Q value, observed reward, next-state maximum, target, TD error, and updated value. Terminal transitions have nextMax = 0. Displayed numbers are rounded; learning uses full precision.</p><pre>{JSON.stringify(r.updates,null,2)}</pre></details>
 <p className="local-note">Every simulated viewer follows the same authored model. The optimal-value column is for comparison and never enters training. Evaluation uses the same environment, so it is not a test on new users.</p>
 <div className="workshop-actions"><button className="small-button" onClick={()=>setConfig({...defaults})}>Reset experiment</button><button className="small-button" onClick={download}>Download reinforcement report</button></div>
 </div>
 <div className="print-only"><p><strong>Worked runs:</strong> 200 episodes, seed 7, α = 0.5. The default uses satisfaction, ε = 0.3, and γ = 0.9. Evaluation turns exploration off.</p><table><thead><tr><th>Change from default</th><th>Greedy route</th><th>Discounted objective</th><th>Raw satisfaction</th></tr></thead><tbody><tr><td>None</td><td>Ask → matched</td><td>4.4</td><td>5</td></tr><tr><td>Exploration ε = 0</td><td>Familiar</td><td>2</td><td>2</td></tr><tr><td>Discount γ = 0</td><td>Familiar</td><td>2</td><td>2</td></tr><tr><td>Click-proxy reward</td><td>Familiar</td><td>4</td><td>2</td></tr></tbody></table><p>Default mean training return is 3.175; final greedy raw return is 5. Different rewards define different objectives. At only 60 default episodes, matched has zero visits and the policy still chooses familiar.</p></div>
 </section>;
}
