import {useMemo,useState} from 'react';
import {defaults,evaluate} from '../lib/research.mjs';
import '../styles/research.css';
type Config={scope:string;overlap:string;sample:number;protocol:string;remove:string};
type Task='audit'|'uncertainty'|'ablation';
const pct=(v:number|null)=>v===null?'Undefined':`${(v*100).toFixed(2)}%`;
const pp=(v:number|null)=>v===null?'Undefined':`${v>0?'+':''}${(v*100).toFixed(2)} pp`;
export default function ResearchLab(){
 const [config,setConfig]=useState<Config>({...defaults}),[task,setTask]=useState<Task>('audit');
 const r=useMemo(()=>evaluate(config),[config]),u=r.uncertainty.selected!,a=r.ablation;
 function change(key:keyof Config,value:string|number){setConfig({...config,[key]:value});}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const el=document.createElement('a');el.href=url;el.download='chapter-41-research-report.json';el.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab research-lab" aria-labelledby="research-title">
 <div className="lab-top"><span className="eyebrow">READ. TEST. QUALIFY.</span><span className="lab-tag">Three local experiments</span></div>
 <h3 id="research-title">What does this result actually establish?</h3><p>Audit three separate fictional studies of a movie assistant. Outcomes are supplied teaching data; changing a setting calculates a report, without running a model or collecting evidence.</p>
 <div className="screen-only">
 <div className="research-task-buttons" role="group" aria-label="Choose a research experiment">{([['audit','Benchmark audit'],['uncertainty','Uncertainty'],['ablation','Ablations']] as [Task,string][]).map(([id,label])=><button className="small-button" key={id} aria-pressed={task===id} onClick={()=>setTask(id)}>{label}</button>)}</div>
 <div hidden={task!=='audit'}>
 <div className="research-controls"><label htmlFor="res-scope">Task slice<select id="res-scope" value={config.scope} onChange={e=>change('scope',e.target.value)}><option value="all">All three tasks</option><option value="facts">Catalog facts</option><option value="preferences">Preference matching</option><option value="tools">Tool use</option></select></label><label htmlFor="res-overlap">Documented training overlap<select id="res-overlap" value={config.overlap} onChange={e=>change('overlap',e.target.value)}><option value="keep">Keep all cases</option><option value="exclude">Exclude flagged cases from both systems</option></select></label></div>
 <p className="local-note">1 = pass, 0 = fail under a supplied task-specific rubric. Flags denote fictional, documented overlap with candidate training material. The same retained cases score both systems.</p>
 <div className="research-stats" aria-live="polite"><div><span>Baseline pass rate</span><strong data-res="baseline">{pct(r.audit.baselineRate)}</strong><small>{r.audit.baseline} / {r.audit.n} retained cases</small></div><div><span>Candidate pass rate</span><strong data-res="candidate">{pct(r.audit.candidateRate)}</strong><small>{r.audit.candidate} / {r.audit.n} retained cases</small></div><div><span>Candidate − baseline</span><strong data-res="difference">{pp(r.audit.difference)}</strong><small>pp means percentage points</small></div></div>
 <p className="local-note" data-res="pairs">Candidate wins / losses / ties: {r.audit.wins} / {r.audit.losses} / {r.audit.ties}. Excluded: {r.audit.excluded}.</p>
 <div className="research-table" role="region" aria-label="Paired benchmark cases" tabIndex={0}><table><thead><tr><th>Case / task</th><th>Overlap flag</th><th>Baseline</th><th>Candidate</th><th>Included?</th></tr></thead><tbody>{r.audit.rows.map(q=><tr key={q.id} data-included={q.included}><td>{q.id} · {q.question}<small>{q.task}</small></td><td>{q.overlap?'Yes':'No known overlap'}</td><td>{q.baseline}</td><td>{q.candidate}</td><td>{q.included?'Yes':'Excluded'}</td></tr>)}</tbody></table></div>
 <p className="local-note">Filtering changes the evaluated population. It neither proves overlap caused the difference nor certifies that the retained data is clean. Twelve authored cases do not establish a population winner.</p>
 </div>
 <div hidden={task!=='uncertainty'}>
 <div className="research-controls"><label htmlFor="res-sample">Hypothetical independent trials<select id="res-sample" value={config.sample} onChange={e=>change('sample',+e.target.value)}>{[25,100,400].map(n=><option key={n} value={n}>{n} trials · {n*.8} successes</option>)}</select></label></div>
 <p className="local-note">Three hypothetical binomial study summaries, each with 80% observed success. These are not duplicated rows or repeated runs of the same cases. Wilson intervals use z = 1.96.</p>
 <div className="research-stats" aria-live="polite"><div><span>Observed rate</span><strong data-res="rate">{pct(u.rate)}</strong><small>{u.passed} / {u.n} successes</small></div><div><span>95% Wilson interval</span><strong data-res="interval">{pct(u.low)} – {pct(u.high)}</strong><small>One success rate, under stated assumptions</small></div><div><span>Interval width</span><strong data-res="width">{pct(u.width)?.replace('%',' pp')}</strong><small>Smaller width means more precision</small></div></div>
 <div className="research-intervals" role="region" aria-label="Confidence interval comparison" tabIndex={0}><svg viewBox="0 0 680 235" role="img" aria-labelledby="research-chart-title research-chart-desc"><title id="research-chart-title">Same observed rate, different sampling precision</title><desc id="research-chart-desc">Three horizontal 95% Wilson intervals with a point at 80 percent. Intervals narrow as independent sample size increases. Exact endpoints appear in the table.</desc>{[0,.25,.5,.75,1].map(v=><g key={v}><line x1={90+560*v} y1="24" x2={90+560*v} y2="183" stroke="var(--line)"/><text x={90+560*v} y="211" textAnchor="middle" fill="var(--muted)" fontSize="14">{v*100}%</text></g>)}{r.uncertainty.rows.map((s,i)=><g key={s.n} data-sample={s.n}><text x="15" y={52+i*58} fill="var(--ink)" fontSize="15">n={s.n}</text><line data-range="interval" x1={90+560*s.low!} x2={90+560*s.high!} y1={47+i*58} y2={47+i*58} stroke={s.selected?'var(--accent)':'var(--muted)'} strokeWidth={s.selected?5:2}/><circle cx={90+560*s.rate!} cy={47+i*58} r={s.selected?6:4} fill={s.selected?'var(--accent)':'var(--muted)'}/></g>)}</svg></div>
 <div className="research-table" role="region" aria-label="Wilson interval results" tabIndex={0}><table><thead><tr><th>Successes / trials</th><th>Rate</th><th>Lower</th><th>Upper</th><th>Width</th></tr></thead><tbody>{r.uncertainty.rows.map(s=><tr key={s.n} data-selected={s.selected}><td>{s.passed} / {s.n}</td><td>{pct(s.rate)}</td><td>{pct(s.low)}</td><td>{pct(s.high)}</td><td>{pct(s.width).replace('%',' pp')}</td></tr>)}</tbody></table></div>
 <p className="local-note">Independent trials with a common success probability are assumed. This interval does not capture model-training variability or repair bias. It is not a confidence interval for a difference between two systems.</p>
 </div>
 <div hidden={task!=='ablation'}>
 <div className="research-controls"><label htmlFor="res-protocol">Resource protocol<select id="res-protocol" value={config.protocol} onChange={e=>change('protocol',e.target.value)}><option value="matched">Matched token limits · 1,500 each</option><option value="unequal">Full system gets 3,000; others 1,500</option></select></label><label htmlFor="res-remove">Remove from the full system<select id="res-remove" value={config.remove} onChange={e=>change('remove',e.target.value)}><option value="retrieval">Retrieval</option><option value="reranker">Reranker</option><option value="both">Both components</option></select></label></div>
 <p className="local-note">Same 100 authored evaluation cases, model, prompts, and scoring within a protocol. Retrieval narrows the small catalog; reranking reorders it; neither uses a fixed order. Results are supplied, not trained here.</p>
 <div className="research-stats" aria-live="polite"><div><span>Full − ablated</span><strong data-res="contrast">{pp(a.contrast)}</strong><small>{pct(a.full!.rate)} − {pct(a.ablated!.rate)}</small></div><div><span>Token limits</span><strong data-res="matched">{a.matched?'Matched':'Different'}</strong><small>{a.full!.budget.toLocaleString('en-US')} / {a.ablated!.budget.toLocaleString('en-US')}</small></div><div><span>Interaction contrast</span><strong data-res="interaction">{a.interaction===null?'Not isolated':pp(a.interaction)}</strong><small>Both − retrieval − reranker + neither</small></div></div>
 <div className="research-table" role="region" aria-label="Ablation variants" tabIndex={0}><table><thead><tr><th>Variant</th><th>Passes / cases</th><th>Pass rate</th><th>Token limit</th></tr></thead><tbody>{a.rows.map(v=><tr key={v.id} data-selected={v.selected}><td>{v.name}<small>{v.selected?'Selected comparison':'Reference variant'}</small></td><td>{v.passed} / {v.n}</td><td>{pct(v.rate)}</td><td>{v.budget.toLocaleString('en-US')}</td></tr>)}</tbody></table></div>
 <p className="research-insight" data-res="interpretation">{a.matched?'This comparison holds the token limit fixed. It describes a component change in this setup; it does not establish a universal contribution or statistical significance.':'This comparison changes both components and token limits. Do not attribute the entire difference to the removed component.'}</p>
 <p className="local-note">A matched token ceiling does not establish equal latency or cost. No case-level ablation outcomes or repeated runs are supplied, so no paired interval is estimated.</p>
 </div>
 <div className="workshop-actions"><button className="small-button" onClick={()=>{setConfig({...defaults});setTask('audit');}}>Reset experiment</button><button className="small-button" onClick={download}>Download research report</button></div>
 </div>
 <div className="print-only"><p><strong>Default settings:</strong> all tasks, keep overlap; 25 hypothetical trials; matched token limits, remove retrieval.</p><table><thead><tr><th>Experiment</th><th>Default result</th><th>Change to inspect</th></tr></thead><tbody><tr><td>Benchmark audit</td><td>Baseline 6/12; candidate 9/12. Difference +25 pp.</td><td>Exclude overlap: 6/8 versus 5/8; −12.5 pp.</td></tr><tr><td>Uncertainty</td><td>20/25; Wilson interval 60.87%–91.14%.</td><td>320/400: interval 75.80%–83.63%.</td></tr><tr><td>Ablations</td><td>84% − 65% = 19 pp at equal limits.</td><td>Unequal limits: 90% − 65% = 25 pp; changes are mixed.</td></tr></tbody></table><p>All three datasets are authored and separate. Filtering does not prove causation, interval precision does not guarantee validity, and an ablation conclusion depends on its controls.</p></div>
 </section>;
}
