import {useMemo,useState} from 'react';
import {dataset,search} from '../lib/information-retrieval.mjs';
const names:Record<string,string>={overlap:'Term overlap',tfidf:'Log TF-IDF',bm25:'BM25'};
const pct=(v:number|null)=>v===null?'Undefined':(100*v).toFixed(2)+'%';
const printed=['overlap','tfidf','bm25'].map(m=>search('space rescue',m));
export default function RetrievalLab(){
  const [query,setQuery]=useState('space rescue'),[method,setMethod]=useState('bm25'),[mode,setMode]=useState('any'),[limit,setLimit]=useState('all'),[k,setK]=useState(3),[k1,setK1]=useState(1.2),[b,setB]=useState(.75);
  const r=useMemo(()=>search(query,method,mode,limit,k,k1,b),[query,method,mode,limit,k,k1,b]);
  const reset=()=>{setQuery('space rescue');setMethod('bm25');setMode('any');setLimit('all');setK(3);setK1(1.2);setB(.75);};
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-16-search-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="lab retrieval-lab" aria-label="Movie search explorer">
    <div className="lab-top"><span className="eyebrow">FOLLOW THE WORDS. EXPLAIN THE RANK.</span><span className="lab-tag">Real search · fictional catalog</span></div>
    <h3>One query. Three ways to rank.</h3><p>Search eight authored movie summaries locally. Titles label the results; only summary words are indexed. No model or external service is called.</p>
    <div className="screen-only">
      <label className="retrieval-query" htmlFor="retrieval-query">Search words<input id="retrieval-query" type="search" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} autoComplete="off"/></label>
      <div className="retrieval-presets" aria-label="Example queries">{dataset.queries.map(q=><button type="button" key={q.query} className="small-button" onClick={()=>setQuery(q.query)}>{q.query}</button>)}<button type="button" className="small-button" onClick={()=>setQuery('hilarious quest')}>hilarious quest</button></div>
      <div className="training-controls"><label htmlFor="retrieval-method">Ranking<select id="retrieval-method" value={method} onChange={e=>setMethod(e.target.value)}>{Object.entries(names).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label htmlFor="retrieval-mode">Word matching<select id="retrieval-mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="any">Any word · OR</option><option value="all">Every word · AND</option></select></label><label htmlFor="retrieval-limit">Runtime requirement<select id="retrieval-limit" value={limit} onChange={e=>setLimit(e.target.value)}><option value="all">No limit</option><option value="under120">Known runtime below 120 min</option></select></label><label htmlFor="retrieval-k">Result slots (K)<select id="retrieval-k" value={k} onChange={e=>setK(Number(e.target.value))}>{[1,3,5].map(v=><option key={v} value={v}>{v}</option>)}</select></label></div>
      <p className="retrieval-status" role="status"><strong data-search-lab="candidates">{r.statistics.candidates}</strong> matching, eligible movies · showing {r.results.length} of {k} slots. {limit==='under120'?'Unknown runtimes are excluded.':'All runtimes are eligible.'}</p>
      <details className="workshop-detail retrieval-index"><summary>Inspect query tokens and the inverted index</summary><p data-search-lab="tokens">Unique query terms: <strong>{r.tokens.join(' · ')||'None'}</strong>. Lowercase English letters/digits only; repeated query terms count once. Quotation marks do not enable phrase search.</p><p>Full index: {r.statistics.documents} summaries · average length {r.statistics.average_length} tokens. Runtime filtering does not rebuild these statistics.</p><div className="retrieval-table-wrap" tabIndex={0} role="region" aria-label="Query term postings"><table><thead><tr><th>Term</th><th>Documents (df)</th><th>Postings: movie → count [positions]</th></tr></thead><tbody>{r.terms.map(t=><tr key={t.term}><td>{t.term}</td><td>{t.df}</td><td>{t.postings.map(p=>`${p.id} → ${p.tf} [${p.positions.join(', ')}]`).join('; ')||'No posting'}</td></tr>)}</tbody></table></div><p>Positions start at 0. These are full-catalog postings, including movies that a runtime filter may later exclude.</p></details>
      <details className="workshop-detail retrieval-tuning"><summary>Explore BM25 settings</summary><p>These change BM25 only. Larger k1 rewards repeated terms more; b controls length normalization. The supplied 1.2 and 0.75 are starting values, not tuned winners.</p><div className="retrieval-sliders"><label htmlFor="retrieval-k1">k1 = {k1.toFixed(1)}<input id="retrieval-k1" type="range" min="0" max="3" step="0.2" value={k1} onChange={e=>setK1(Number(e.target.value))} disabled={method!=='bm25'}/></label><label htmlFor="retrieval-b">b = {b.toFixed(2)}<input id="retrieval-b" type="range" min="0" max="1" step="0.25" value={b} onChange={e=>setB(Number(e.target.value))} disabled={method!=='bm25'}/></label></div></details>
      <div className="retrieval-results" aria-label="Ranked movies">{r.results.map((d,i)=><article key={d.id} className="retrieval-result" data-movie-id={d.id}><div className="retrieval-result-head"><span className="eyebrow">{String(i+1).padStart(2,'0')} · {d.id}</span><span className="retrieval-score">{d.score.toFixed(4)} <small>score</small></span></div><h4>{d.title}</h4><p>{d.summary}</p><p className="retrieval-meta">{d.runtime_minutes===null?'Runtime unknown':d.runtime_minutes+' min'} · {d.length} summary tokens · matches: {d.contributions.filter(t=>t.tf>0).map(t=>t.term).join(', ')}</p><div className="retrieval-bar" aria-hidden="true"><span style={{width:`${r.results[0].score?100*d.score/r.results[0].score:0}%`}}/></div><details className="retrieval-score-detail"><summary>Explain this score</summary><div className="retrieval-table-wrap" tabIndex={0} role="region" aria-label={'Score contributions for '+d.title}><table><thead><tr><th>Term</th><th>tf</th><th>df</th><th>Contribution</th></tr></thead><tbody>{d.contributions.map(t=><tr key={t.term}><td>{t.term}</td><td>{t.tf}</td><td>{t.df}</td><td>{t.weight.toFixed(4)}</td></tr>)}</tbody></table></div><p>Sum the unrounded contributions. Bars are relative to this result list's top score, not probabilities. Exact ties use movie ID.</p></details></article>)}</div>
      {!r.results.length&&<p className="retrieval-empty" role="status">{r.tokens.length?'No lexical matches meet these settings. Try different words or relax a filter.':'Enter a query containing English letters or digits.'}</p>}
      <div className="retrieval-evaluation"><h4>Does this answer the search intent?</h4>{r.evaluation?<><p>{r.evaluation.intent}</p><div className="lab-metrics retrieval-metrics"><div><strong data-search-lab="precision">{pct(r.evaluation.precision_at_k)}</strong><span>Precision@{k}</span></div><div><strong data-search-lab="recall">{pct(r.evaluation.recall_at_k)}</strong><span>Recall@{k}</span></div><div><strong data-search-lab="rr">{r.evaluation.reciprocal_rank_at_k.toFixed(4)}</strong><span>Reciprocal rank@{k}</span></div></div><p className="local-note">{r.evaluation.relevant_retrieved} relevant results retrieved / {r.evaluation.relevant_total} relevant eligible movies. Judgments are authored for these three preset intents; unlisted IDs are nonrelevant. Missing result slots count as zero for Precision@K. Filtered recall uses a changed denominator.</p></>:<p data-search-lab="unjudged">No relevance judgments for this query. Scores show word matching; relevance metrics need a defined intent and labels. We do not invent them for arbitrary text.</p>}</div>
      <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset search</button><button className="small-button" onClick={download}>Download search result</button></div>
      <details className="workshop-detail retrieval-catalog"><summary>Read all eight movie summaries and judgments</summary>{dataset.movies.map(d=><div key={d.id} className="retrieval-catalog-row"><strong>{d.id} · {d.title}</strong><p>{d.summary}</p><p className="local-note">{d.runtime_minutes===null?'Runtime unknown':d.runtime_minutes+' minutes'}</p></div>)}{dataset.queries.map(q=><p key={q.query}><strong>{q.query}</strong>: relevant IDs {q.relevant.join(', ')}; all other IDs judged nonrelevant. Intent: {q.intent}</p>)}</details>
    </div>
    <div className="print-only"><p>Default query: space rescue. OR matching, no runtime limit, K = 3. Eight summaries have 94 tokens in total (average 11.75). Space occurs in 3 documents; rescue in 4.</p><table><thead><tr><th>Method</th><th>Top three movie IDs (scores)</th></tr></thead><tbody>{printed.map(p=><tr key={p.configuration.method}><td>{names[p.configuration.method]}</td><td>{p.results.map(d=>`${d.id} (${d.score.toFixed(4)})`).join(' → ')}</td></tr>)}</tbody></table><p>Titles: M008 = Parallel World; M004 = Quiet Orbit; M005 = Cafe Chaos; M001 = Moonlight Map. Relevant IDs are M004, M007, M008, so all three methods get Precision@3 = Recall@3 = 66.67% and reciprocal rank@3 = 1.</p><p>BM25 retrieves a cafe's “space” but misses Unlisted Voyage: “Astronauts save a stranded pilot beyond a distant moon.” AND removes partial matches but still misses M007. Runtime below 120 excludes M002 (140 min) and M007 (unknown); recall becomes 100% only within that smaller eligible set.</p></div>
    <noscript><p>Use the Python workbook or printable comparison if JavaScript is unavailable.</p></noscript>
  </section>;
}
