import {useId,useMemo,useState} from 'react';
import {validateDataset,experiment,predict,decide,metrics} from '../lib/supervised-learning.mjs';
const splits=validateDataset();
const defaults=[experiment('regression'),experiment('classification')];
const fmt=(x:number)=>Math.abs(x)<.00005?'0.0000':x.toFixed(4);
export default function SupervisedLab(){
  const [task,setTask]=useState('regression'),[strength,setStrength]=useState(0),[history,setHistory]=useState(.75),[threshold,setThreshold]=useState(.5),[split,setSplit]=useState('train');
  // Query and threshold edits reuse the fitted model. Only task/strength changes refit it.
  const fitted=useMemo(()=>experiment(task,strength),[task,strength]);
  const prediction=predict(fitted.model,history),classification=task==='classification';
  const reports={train:{model:metrics(splits.train,fitted.model,threshold),baseline:metrics(splits.train,fitted.baseline,threshold)},validation:{model:metrics(splits.validation,fitted.model,threshold),baseline:metrics(splits.validation,fitted.baseline,threshold)}};
  const result={...fitted,threshold:classification?threshold:null,query:{history_like_fraction:history,prediction,predicted_class:classification?decide(prediction,threshold):null},reports};
  const rows=split==='train'?splits.train:splits.validation;
  const report=split==='train'?reports.train:reports.validation;
  const id='supervised-'+useId().replace(/[^a-zA-Z0-9]/g,'');
  const xp=(x:number)=>62+x*570,yp=(y:number)=>252-(classification?y:y/5)*210;
  const curve=Array.from({length:101},(_,i)=>`${i?'L':'M'}${xp(i/100)} ${yp(predict(fitted.model,i/100))}`).join(' ');
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-13-model-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="lab supervised-lab" aria-label="Supervised learning workbench">
    <div className="lab-top"><span className="eyebrow">FIT A MODEL. INSPECT ITS PREDICTION.</span><span className="lab-tag">Real fitting · synthetic records</span></div>
    <h3>One input. Two learning tasks.</h3><p>Use a viewer's past enjoyment of this genre to predict a rating or a thumbs-up. Six training events fit the model. Three validation events let you inspect its behavior.</p>
    <div className="screen-only">
      <div className="training-controls"><label htmlFor="supervised-task">Prediction task<select id="supervised-task" value={task} onChange={e=>setTask(e.target.value)}><option value="regression">Regression · rating</option><option value="classification">Classification · thumbs-up</option></select></label><label htmlFor="supervised-strength">L2 strength λ<select id="supervised-strength" value={strength} onChange={e=>setStrength(Number(e.target.value))}><option value={0}>0 · no penalty</option><option value={.1}>0.1 · moderate here</option><option value={1}>1 · stronger here</option></select></label><label htmlFor="supervised-split">Inspect labeled events<select id="supervised-split" value={split} onChange={e=>setSplit(e.target.value)}><option value="train">Training · 6 events</option><option value="validation">Validation · 3 events</option></select></label></div>
      <div className="supervised-sliders"><label htmlFor="supervised-history">Past genre-like fraction: <strong>{history.toFixed(2)}</strong><input id="supervised-history" type="range" min="0" max="1" step=".05" value={history} onChange={e=>setHistory(Number(e.target.value))}/></label>{classification&&<label htmlFor="supervised-threshold">Thumbs-up threshold: <strong>{threshold.toFixed(2)}</strong><input id="supervised-threshold" type="range" min="0" max="1" step=".05" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label>}</div>
      <div className="lab-metrics supervised-metrics" aria-live="polite"><div><strong data-supervised="prediction">{fmt(prediction)}</strong><span>{classification?'Estimated P(thumbs-up)':'Predicted rating · 1–5 scale'}</span></div><div><strong data-supervised="decision">{classification?(decide(prediction,threshold)?'Thumbs-up':'Thumbs-down'):'Numeric output'}</strong><span>{classification?'Decision uses p ≥ threshold':'No class threshold applies'}</span></div><div><strong data-supervised="weight">{fmt(fitted.model.w)}</strong><span>Fitted weight w</span></div></div>
      <p className="supervised-equation" data-supervised="equation">{classification?'p = sigmoid(':'rating = '}{fmt(fitted.model.w)} × (2s − 1) + {fmt(fitted.model.b)}{classification?')':''}. {classification?'2,000 fixed gradient steps; probabilities are not proven calibrated.':'Closed-form fit; predictions are not clipped or guaranteed ratings.'}</p>
      <figure className="training-figure"><div className="training-plot-scroll" tabIndex={0} role="region" aria-label="Fitted supervised model chart"><svg viewBox="0 0 700 300" role="img" aria-labelledby={id+'-title '+id+'-desc'}><title id={id+'-title'}>{classification?'Logistic probability curve':'Linear rating prediction'}</title><desc id={id+'-desc'}>Curve: fitted model. Circles: selected split's observed labels. Dashed line: {classification?'decision threshold':'constant training-mean baseline'}. Diamond: your query prediction. The model uses training events only.</desc>
        {(classification?[0,.25,.5,.75,1]:[0,1,2,3,4,5]).map(y=><g key={y}><line x1="62" x2="632" y1={yp(y)} y2={yp(y)} className="plot-grid"/><text x="49" y={yp(y)+4} textAnchor="end" className="plot-tick">{y}</text></g>)}
        {[0,.25,.5,.75,1].map(x=><text key={x} x={xp(x)} y="271" textAnchor="middle" className="plot-tick">{x}</text>)}
        <text x="62" y="21" className="plot-label">{classification?'Probability / observed class 0 or 1':'Rating (observed labels are 1–5)'}</text><text x="347" y="294" textAnchor="middle" className="plot-label">Past genre-like fraction s</text>
        <line x1="62" x2="62" y1="42" y2="252" className="plot-axis"/><line x1="62" x2="632" y1="252" y2="252" className="plot-axis"/>
        <line x1="62" x2="632" y1={yp(classification?threshold:fitted.baseline.b)} y2={yp(classification?threshold:fitted.baseline.b)} className="error-line"/>
        <path d={curve} fill="none" className="prediction-line"/>
        {rows.map(r=><circle key={r.event_id} cx={xp(r.history_like_fraction)} cy={yp(classification?r.liked:r.rating)} r="5" className={split==='train'?'training-point':'validation-point'}/>)}
        <path d={`M${xp(history)} ${yp(prediction)-7} l7 7 l-7 7 l-7 -7 Z`} className="supervised-query"/>
      </svg></div><figcaption>Solid curve = trained model; circles = {split} labels; diamond = query. Dashed line = {classification?'threshold, which does not change the probabilities':'constant training-mean baseline'}. Switching the displayed split does not refit the model.<span className="mobile-only"> Scroll sideways to see the whole chart.</span></figcaption></figure>
      <div className="supervised-table-wrap"><table aria-label="Model versus constant baseline"><thead><tr><th>{split==='train'?'Training':'Validation'} results</th><th>Fitted model</th><th>Constant baseline</th></tr></thead><tbody>{classification?<><tr><td>Log loss · lower is better</td><td data-supervised="loss">{fmt(report.model.log_loss!)}</td><td>{fmt(report.baseline.log_loss!)}</td></tr><tr><td>Correct predictions</td><td>{report.model.tp!+report.model.tn!} / {rows.length}</td><td>{report.baseline.tp!+report.baseline.tn!} / {rows.length}</td></tr></>:<><tr><td>MSE · rating points²</td><td data-supervised="loss">{fmt(report.model.mse!)}</td><td>{fmt(report.baseline.mse!)}</td></tr><tr><td>MAE · rating points</td><td>{fmt(report.model.mae!)}</td><td>{fmt(report.baseline.mae!)}</td></tr></>}</tbody></table></div>
      <p className="local-note">The baseline always predicts {classification?'the training thumbs-up fraction, 0.5; it uses the same threshold':'the training mean rating, 3'}. These tiny authored samples illustrate calculations, not real recommendation quality. Test metrics are reserved for the workbook's explicit evaluation command.</p>
      <div className="workshop-actions"><button className="small-button" onClick={()=>{setTask('regression');setStrength(0);setHistory(.75);setThreshold(.5);setSplit('train');}}>Reset models</button><button className="small-button" onClick={download}>Download model result</button></div>
      <details className="workshop-detail"><summary>Inspect the selected events and predictions</summary><div className="supervised-table-wrap" tabIndex={0} role="region" aria-label="Labeled movie events"><table><thead><tr><th>Event</th><th>History s</th><th>Observed target</th><th>Prediction</th>{classification&&<th>Class</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.event_id}><td>{r.event_id}</td><td>{r.history_like_fraction}</td><td>{classification?r.liked:r.rating}</td><td>{fmt(predict(fitted.model,r.history_like_fraction))}</td>{classification&&<td>{decide(predict(fitted.model,r.history_like_fraction),threshold)}</td>}</tr>)}</tbody></table></div><p>Neither rating nor liked enters the input feature. IDs track events; each viewer belongs to one split.</p></details>
    </div>
    <div className="print-only"><p>Default query: s = 0.75, x = 0.5; λ = 0 and classification threshold = 0.5. Models fit only the six training rows.</p><table><thead><tr><th>Task</th><th>Prediction</th><th>Training loss</th><th>Validation loss</th></tr></thead><tbody>{defaults.map(r=><tr key={r.model.task}><td>{r.model.task}</td><td>{fmt(r.query.prediction)}</td><td>{fmt(r.model.task==='regression'?r.reports.train.model.mse!:r.reports.train.model.log_loss!)}</td><td>{fmt(r.model.task==='regression'?r.reports.validation.model.mse!:r.reports.validation.model.log_loss!)}</td></tr>)}</tbody></table><p>Regression losses are MSE in rating points². Classification losses are average negative log likelihood (natural logs). Their scales cannot be directly compared.</p><p>The rating is 3.9286; estimated thumbs-up probability is 0.8202. Threshold 0.50 predicts thumbs-up; threshold 0.90 predicts thumbs-down with the same probability and weights. At λ = 1 the rating becomes 3.2955 and the probability becomes 0.5261, illustrating shrinkage toward a constant baseline.</p><p>Validation regression MSE: model 0.1878 versus baseline 2.6667. Classification: both get 2 of 3 validation labels correct at threshold 0.5, but log losses differ: 0.3418 versus 0.6931. These are synthetic arithmetic results, not evidence of real-world quality.</p></div>
    <noscript><p>Enable JavaScript for the workbench or use the Python workbook and printable comparison.</p></noscript>
  </section>;
}
