import {useState} from 'react';
import {data,defaults,evaluate} from '../lib/systemEvaluation.mjs';
import '../styles/system-evaluation.css';
type Config={variant:string;slice:string;trial:string;minSuccess:number;maxLatency:number};
const percent=(n:number|null)=>n===null?'N/A':`${n.toFixed(1)}%`;
export default function SystemEvaluationLab(){
 const [config,setConfig]=useState<Config>({...defaults}),[selected,setSelected]=useState('T7:1');
 const r=evaluate(config),v=r.view,chosen=v.rows.find(x=>`${x.taskId}:${x.trial}`===selected)||v.rows[0],task=data.tasks.find(t=>t.id===chosen.taskId);
 if(!task)throw new Error('Evaluation record has no matching task');
 function change(k:keyof Config,value:string|number){setConfig({...config,[k]:value});}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-34-evaluation-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab system-evaluation-lab" aria-labelledby="evaluation-title">
 <div className="lab-top"><span className="eyebrow">MEASURE. COMPARE. INVESTIGATE.</span><span className="lab-tag">Authored fixtures · no model calls</span></div>
 <h3 id="evaluation-title">A better average. A reason to pause.</h3><p>Compare eight movie tasks with two authored trials each. Scores come from structured outputs, supplied fact IDs, and recorded watchlist changes. Timings and costs are fictional.</p>
 <div className="screen-only">
 <div className="evaluation-controls">
 <label htmlFor="eval-variant">Compare with baseline<select id="eval-variant" value={config.variant} onChange={e=>change('variant',e.target.value)}><option value="candidate">Candidate: better answers, write regression</option><option value="guarded">Guarded: candidate with write regression fixed</option></select></label>
 <label htmlFor="eval-slice">Display task slice<select id="eval-slice" value={config.slice} onChange={e=>change('slice',e.target.value)}>{['all','routine','edge','action'].map(s=><option key={s} value={s}>{s==='all'?'All tasks':s[0].toUpperCase()+s.slice(1)+' tasks'}</option>)}</select></label>
 <label htmlFor="eval-trial">Display trials<select id="eval-trial" value={config.trial} onChange={e=>change('trial',e.target.value)}><option value="all">Both trials</option><option value="1">Trial 1 only</option><option value="2">Trial 2 only</option></select></label>
 <label htmlFor="eval-minSuccess">Full-suite minimum success<select id="eval-minSuccess" value={config.minSuccess} onChange={e=>change('minSuccess',+e.target.value)}>{[60,75,90].map(n=><option key={n} value={n}>{n}%</option>)}</select></label>
 <label htmlFor="eval-maxLatency">Full-suite p95 limit<select id="eval-maxLatency" value={config.maxLatency} onChange={e=>change('maxLatency',+e.target.value)}>{[1800,2500,3000].map(n=><option key={n} value={n}>{n} ms</option>)}</select></label>
 </div>
 <div className="evaluation-stats" aria-live="polite"><div><span>Baseline · visible trials</span><strong data-eval="baseline">{percent(v.baseline.success)}</strong><small>{v.baseline.passed}/{v.baseline.n} pass</small></div><div><span>Compared version · visible</span><strong data-eval="success">{percent(v.candidate.success)}</strong><small>{v.candidate.passed}/{v.candidate.n} pass</small></div><div><span>Paired change</span><strong data-eval="delta">{v.paired.delta?.toFixed(1)} pp</strong><small>{v.paired.wins} wins · {v.paired.losses} losses</small></div><div><span>Visible p95</span><strong data-eval="p95">{v.candidate.p95} ms</strong><small>Mean cost: {v.candidate.meanCost?.toFixed(1)} units</small></div></div>
 <p className="local-note"><span data-eval="consistent">{v.candidate.allTrialsPassed}/{v.candidate.tasks}</span> tasks pass every displayed trial. Selecting one trial lowers that consistency requirement. Trial labels represent authored scenarios, not random seeds.</p>
 <div className="evaluation-gate" role="status"><h4>Release check: <span data-eval="decision">{r.decision}</span></h4><p>Always uses all 16 trials, regardless of display filters. Passing this example gate is not production approval.</p><ul>{r.gates.map(g=><li key={g.name}><strong>{g.pass?'PASS':'HOLD'}</strong> {g.name}<span>Observed {g.actual} · limit/reference {g.limit}</span></li>)}</ul></div>
 <div className="evaluation-table" role="region" aria-label="Paired trial results" tabIndex={0}><table><thead><tr><th>Task / trial</th><th>Baseline → version</th><th>Failed checks</th><th>Time</th></tr></thead><tbody>{v.rows.map((row,i)=><tr key={`${row.taskId}:${row.trial}`}><td>{row.taskId} / {row.trial}</td><td>{v.baselineRows[i].pass?'Pass':'Fail'} → {row.pass?'Pass':'Fail'}</td><td>{row.failures.join(', ')||'None'}</td><td>{row.latencyMs} ms</td></tr>)}</tbody></table></div>
 <details className="evaluation-inspector"><summary>Inspect a task and its recorded result</summary><label htmlFor="eval-record">Task and trial<select id="eval-record" value={`${chosen.taskId}:${chosen.trial}`} onChange={e=>setSelected(e.target.value)}>{v.rows.map(row=><option key={`${row.taskId}:${row.trial}`} value={`${row.taskId}:${row.trial}`}>{row.taskId} / trial {row.trial}</option>)}</select></label><p>{task.prompt}</p><pre>{JSON.stringify({expected:task.expected,requiredFacts:task.facts,allowedWrites:task.allowedWrites,expectedWrites:task.expectedWrites,record:chosen},null,2)}</pre></details>
 <div className="workshop-actions"><button className="small-button" onClick={()=>{setConfig({...defaults});setSelected('T7:1');}}>Reset experiment</button><button className="small-button" onClick={download}>Download evaluation report</button></div>
 </div>
 <div className="print-only"><p><strong>Worked comparison:</strong> eight tasks × two authored trials. Success requires the expected answer fields, required context facts, intended final state, and authorized writes.</p><table><thead><tr><th>Full suite</th><th>Baseline</th><th>Candidate</th><th>Guarded</th></tr></thead><tbody><tr><td>Successful trials</td><td>10/16 (62.5%)</td><td>12/16 (75.0%)</td><td>14/16 (87.5%)</td></tr><tr><td>Unauthorized-write trials</td><td>0</td><td>2</td><td>0</td></tr><tr><td>p95 latency</td><td>2800 ms</td><td>2400 ms</td><td>2600 ms</td></tr><tr><td>Default example gate</td><td>Reference</td><td>Hold</td><td>Pass</td></tr></tbody></table><p>Candidate wins 4 pairs and loses 2: +12.5 percentage points. Its two losses are unauthorized watchlist updates. The gate still holds when display filters hide those rows. Guarded fixes them, but two other trials still fail.</p></div>
 </section>;
}
