import {useMemo,useState} from 'react';
import {run,presets,dataset} from '../lib/training-diagnostics.mjs';
const f=(v:number)=>v.toFixed(4),pct=(v:number)=>(100*v).toFixed(2)+'%';
export default function TrainingLab(){
 const [preset,setPreset]=useState('fast'),[stop,setStop]=useState(false),[batch,setBatch]=useState(16),[checkpoint,setCheckpoint]=useState<'best'|'last'>('best');
 const r=useMemo(()=>run(preset,stop,batch),[preset,stop,batch]);const selected=r[checkpoint]!;
 const printed=useMemo(()=>Object.keys(presets).map(p=>run(p,false,16)),[]);
 const upper=Math.max(.8,Math.ceil(Math.max(...r.history.flatMap(h=>[h.train_loss,h.validation_loss]))*10)/10);
 const points=(key:'train_loss'|'validation_loss')=>r.history.map(h=>`${55+530*h.epoch/r.last.epoch},${195-160*h[key]/upper}`).join(' ');
 const predictions=checkpoint==='best'?r.best_predictions:r.last_predictions;
 const note=preset==='zero'?'Only the output bias learns. Hidden weights and activations remain zero; a nonzero total gradient does not prove the hidden layers work.':preset==='raw'?'Large adventure values saturate many tanh units at initialization. Compare the initial saturation with the scaled baseline.':preset==='fast'?'The large rate causes an early loss spike. Later, training loss keeps falling while validation loss rises. Checkpoint choice matters.':preset==='regularized'?'This L2 setting reduces weight size but raises validation loss relative to the baseline here. Regularization is a hypothesis to test, not an automatic improvement.':preset==='sgd'?'The optimizer changes while the numerical rate stays 0.03. This is a controlled illustration, not an optimally tuned comparison of SGD and Adam.':'Training and validation losses both improve on these authored cases. This is development evidence, not a final test result.';
 function reset(){setPreset('fast');setStop(false);setBatch(16);setCheckpoint('best');}
 function download(){const u=URL.createObjectURL(new Blob([JSON.stringify({...r,displayed_checkpoint:checkpoint},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='chapter-21-training-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 return <section className="lab training-lab" aria-label="Neural network training diagnostics">
  <div className="lab-top"><span className="eyebrow">TRAIN. OBSERVE. INVESTIGATE.</span><span className="lab-tag">16 training + 12 validation movies</span></div>
  <h3>Lower training loss. Worse validation.</h3><p>A real 2 → 8 → 1 tanh network learns fictional genre preferences. Six presets change one baseline setting. The curves are computed locally; no pretrained model or service is involved.</p>
  <div className="screen-only">
   <div className="training-controls"><label>Experiment<select id="training-preset" value={preset} onChange={e=>setPreset(e.target.value)}>{Object.entries(presets).map(([id,c])=><option key={id} value={id}>{c.label}</option>)}</select></label><label>Batch size<select id="training-batch" value={batch} onChange={e=>setBatch(Number(e.target.value))}><option value="16">16 · one update / epoch</option><option value="4">4 · four updates / epoch</option></select></label><label>Displayed checkpoint<select id="training-checkpoint" value={checkpoint} onChange={e=>setCheckpoint(e.target.value as 'best'|'last')}><option value="best">Best validation observed</option><option value="last">Last epoch reached</option></select></label></div>
   <label className="training-stop"><input id="training-stop" type="checkbox" checked={stop} onChange={e=>setStop(e.target.checked)}/> Stop after 30 epochs without a meaningful validation improvement</label>
   <p className="training-config" data-training="config">Optimizer: {r.config.optimizer.toUpperCase()} · learning rate {r.config.rate} · L2 λ = {r.config.l2} · scaling {r.config.scale?'on':'off'} · initialization {r.config.init}</p>
   <p className="lab-note">Changing a control reruns the same fixed initialization and epoch-seeded shuffle. Budget: 600 epochs. Patience resets after a loss improvement greater than 0.0001; the selected checkpoint is the lowest validation loss actually observed, including epoch 0.</p>
   <div className="lab-metrics training-metrics" aria-live="polite"><div><strong data-training="epoch">{selected.epoch}</strong><span>Displayed checkpoint epoch</span></div><div><strong data-training="train">{f(selected.train_loss)}</strong><span>Training data loss</span></div><div><strong data-training="validation">{f(selected.validation_loss)}</strong><span>Validation data loss</span></div></div>
   <p className="training-run-status" data-training="status">{r.last.epoch} epochs · {r.last.updates} updates · {r.stop_reason}</p>
   <div className="training-chart"><div className="training-legend"><span><i/>Training loss</span><span><i/>Validation loss</span></div><svg viewBox="0 0 630 247" role="img" aria-labelledby="training-chart-title training-chart-desc"><title id="training-chart-title">Training and validation data loss by epoch</title><desc id="training-chart-desc">{r.config.label}. Training loss goes from {f(r.history[0].train_loss)} to {f(r.last.train_loss)}. Validation loss goes from {f(r.history[0].validation_loss)} to {f(r.last.validation_loss)}. Displayed checkpoint: epoch {selected.epoch}. The vertical scale adjusts per experiment.</desc><path d="M55 25V195H590" fill="none" stroke="var(--muted)"/><polyline points={points('train_loss')} fill="none" stroke="var(--accent)" strokeWidth="2.4"/><polyline points={points('validation_loss')} fill="none" stroke="var(--gold)" strokeWidth="2.4" strokeDasharray="6 3"/><line x1={55+530*selected.epoch/r.last.epoch} x2={55+530*selected.epoch/r.last.epoch} y1="28" y2="195" stroke="var(--muted)" strokeDasharray="3 4"/><text x="43" y="199" textAnchor="end">0</text><text x="43" y="39" textAnchor="end">{upper.toFixed(1)}</text><text x="55" y="217">0</text><text x="585" y="217" textAnchor="end">{r.last.epoch}</text><text x="320" y="240" textAnchor="middle">Completed epochs</text></svg></div>
   <p className="lab-note">Both curves use mean binary cross-entropy in evaluation conditions, without the L2 penalty. The vertical marker is the displayed checkpoint; each experiment rescales the chart's vertical axis.</p>
   <div className="training-insight" data-training="note">{note}{preset==='raw'&&batch===4&&<p>Reproducibility example: this unscaled mini-batch run amplifies tiny floating-point differences. Its later Python and browser results can diverge despite matching seeds; compare the observed trajectories rather than expecting identical numbers.</p>}</div>
   <details className="workshop-detail training-diagnostics"><summary>Inspect gradients, saturation, and predictions</summary><div className="training-table" role="region" tabIndex={0} aria-label="Training diagnostics"><table><thead><tr><th>Diagnostic</th><th>Epoch 0</th><th>Displayed</th></tr></thead><tbody>{([['train_accuracy','Training accuracy'],['validation_accuracy','Validation accuracy'],['saturation','Saturated hidden activations']] as const).map(([key,label])=><tr key={key}><th>{label}</th><td>{pct(r.history[0][key])}</td><td data-diagnostic={key}>{pct(selected[key])}</td></tr>)}<tr><th>Mean objective gradient norm</th><td>{f(r.history[0].gradient_norm)}</td><td data-diagnostic="gradient_norm">{f(selected.gradient_norm)}</td></tr><tr><th>Training objective incl. penalty</th><td>{f(r.history[0].objective)}</td><td data-diagnostic="objective">{f(selected.objective)}</td></tr></tbody></table></div><p className="lab-note">Saturation means |tanh activation| &gt; 0.99 over training rows and hidden units; this threshold is a teaching diagnostic. The norm is the full-training mean objective gradient at that epoch, not the norm of every mini-batch update.</p>
    <p className="lab-note">The scaler is fitted on training rows only: means ({r.scaler.mean.map(f).join(', ')}), standard deviations ({r.scaler.std.map(f).join(', ')}). With scaling off, mean 0 and deviation 1 preserve raw features.</p>
    <div className="training-table" role="region" tabIndex={0} aria-label="Validation predictions"><table><thead><tr><th>Movie ID</th><th>Adventure / romance</th><th>Label</th><th>p(like)</th></tr></thead><tbody>{predictions.map(m=><tr key={m.id}><td>{m.id}</td><td>{dataset.validation.find(d=>d.id===m.id)!.x.join(' / ')}</td><td>{m.y?'Like':'Dislike'}</td><td data-training-prob={m.id}>{f(m.p)}</td></tr>)}</tbody></table></div><p className="lab-note">Decision threshold is 0.5 on unrounded probabilities. Validation guides this experiment; no independent test results are reported.</p>
   </details>
   <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset experiment</button><button className="small-button" onClick={download}>Download training report</button></div>
  </div>
  <div className="print-only"><p>Batch size 16; 600-epoch budget; early stopping off. Each row changes one baseline setting. “Best” means the lowest validation loss among the epochs observed.</p><table><thead><tr><th>Preset</th><th>Best epoch</th><th>Best validation loss</th><th>Final validation loss</th></tr></thead><tbody>{printed.map(v=><tr key={v.preset}><td>{v.config.label}</td><td>{v.best!.epoch}</td><td>{f(v.best!.validation_loss)}</td><td>{f(v.last.validation_loss)}</td></tr>)}</tbody></table><p>The large-rate run selects epoch 112 (validation loss 0.0419), while epoch 600 has loss 0.1899 and validation accuracy 91.67%. Training loss still falls. With patience 30 enabled, that run stops at epoch 46 and selects epoch 16 (loss 0.0738); a stopping rule cannot see the later recovery.</p><p>At initialization, unscaled inputs saturate 85.16% of hidden activations versus 0% with scaling. The all-zero model learns only an output bias. This particular L2 setting worsens validation loss compared with the baseline. These are authored development cases, not a ranking of optimizers or production-quality estimates.</p></div>
 </section>;
}
