import {useState} from 'react';
import {data,lora,preference} from '../lib/tuning.mjs';
import '../styles/tuning.css';
const f=(x:number)=>x.toFixed(4);
export default function TuningLab(){
 const [view,setView]=useState(1),[rank,setRank]=useState(1),[alpha,setAlpha]=useState(2),[stage,setStage]=useState('adapted');
 const [reference,setReference]=useState(.5),[beta,setBeta]=useState(.5),[rate,setRate]=useState(.5),[steps,setSteps]=useState(10),[chosen,setChosen]=useState('A');
 const l=lora(rank,alpha,stage),p=preference(reference,beta,rate,steps,chosen),end=p.final!;
 const path=p.history.map((r:{step:number;pA:number},i:number)=>`${i?'L':'M'}${40+r.step*11.2} ${145-r.pA*120}`).join(' ');
 function reset(){setView(1);setRank(1);setAlpha(2);setStage('adapted');setReference(.5);setBeta(.5);setRate(.5);setSteps(10);setChosen('A');}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({lora:l,preference:p},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='chapter-28-tuning-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="lab tuning-lab" aria-labelledby="tuning-title">
  <div className="lab-top"><span className="eyebrow">INSPECT. UPDATE. QUESTION.</span><span className="lab-tag">Small numerical models · no LLM loaded</span></div>
  <h3 id="tuning-title">Small updates. Different learning signals.</h3><p>Inspect a low-rank matrix update, then optimize a separate two-response policy.</p>
  <div className="screen-only">
   <div className="tune-tabs"><button className="small-button" aria-pressed={view===1} onClick={()=>setView(1)}>1 · Inspect LoRA</button><button className="small-button" aria-pressed={view===2} onClick={()=>setView(2)}>2 · Learn a preference</button></div>
   <div hidden={view!==1}>
    <p className="lab-note">A hand-set 4 × 4 layer, with no bias or dropout. These vectors are numeric examples, not movie scores. “Adapted” uses illustrative matrices, not weights learned by this workbook.</p>
    <div className="tune-controls"><label htmlFor="tune-rank">Rank<select id="tune-rank" value={rank} onChange={e=>setRank(+e.target.value)}>{[1,2].map(v=><option key={v}>{v}</option>)}</select></label><label htmlFor="tune-alpha">Alpha<select id="tune-alpha" value={alpha} onChange={e=>setAlpha(+e.target.value)}>{[1,2,4].map(v=><option key={v}>{v}</option>)}</select></label><label htmlFor="tune-stage">Adapter state<select id="tune-stage" value={stage} onChange={e=>setStage(e.target.value)}><option value="initial">Initial: B is zero</option><option value="adapted">Adapted: hand-set B</option></select></label></div>
    <div className="tune-insight" aria-live="polite"><p><strong data-tune="count">{l.trainableParameters} trainable adapter parameters</strong> + 16 frozen base parameters.</p><p>Scale α/r = <strong data-tune="scale">{f(l.scale)}</strong>. Rank 2 has as many adapter parameters as this tiny base matrix; low-rank savings require r to be small relative to layer width.</p></div>
    <p className="workshop-label">Scaled update ΔW = (α/r)BA</p><div className="tune-table"><table><thead><tr><th>Row</th>{[1,2,3,4].map(i=><th key={i}>Col {i}</th>)}</tr></thead><tbody>{l.delta.map((row:number[],i:number)=><tr key={i}><th>{i+1}</th>{row.map((v,j)=><td key={j} data-delta={`${i}-${j}`}>{f(v)}</td>)}</tr>)}</tbody></table></div>
    <p className="workshop-label">Output with x = [1, 0.5, 0, 1]</p><div className="tune-table"><table><thead><tr><th>Coordinate</th><th>Base W₀x</th><th>Update ΔWx</th><th>Sum</th></tr></thead><tbody>{l.output.map((v:number,i:number)=><tr key={i}><td>{i+1}</td><td>{f(l.baseOutput[i])}</td><td>{f(l.update[i])}</td><td data-output={i}>{f(v)}</td></tr>)}</tbody></table></div>
    <details className="workshop-detail"><summary>Inspect A, B, and the frozen base</summary><pre>{JSON.stringify({A:l.A,B:l.B,W0:data.base},null,2)}</pre><p>We use the conventional α/r scaling. Initial B = 0 leaves the output unchanged, while A is nonzero. Updating both matrices from all zeros would give zero gradients to both in this simple branch.</p></details>
   </div>
   <div hidden={view!==2}>
    <p className="lab-note">Exactly two fixed complete replies share one prompt. A single trainable logit θ determines P(A) = sigmoid(θ). This is a real scalar gradient update, not language-model training or a benchmark.</p>
    <div className="tune-pair"><p><strong>Prompt:</strong> {data.prompt}</p><p><strong>Reply A:</strong> {data.replies.A}</p><p><strong>Reply B:</strong> {data.replies.B}</p></div>
    <div className="tune-controls"><label htmlFor="tune-chosen">Labeler's preferred reply<select id="tune-chosen" value={chosen} onChange={e=>setChosen(e.target.value)}><option value="A">A · grounded</option><option value="B">B · unsupported claims</option></select></label><label htmlFor="tune-reference">Reference P(A)<select id="tune-reference" value={reference} onChange={e=>setReference(+e.target.value)}>{[.2,.5,.8].map(v=><option key={v}>{v}</option>)}</select></label><label htmlFor="tune-beta">Beta β<select id="tune-beta" value={beta} onChange={e=>setBeta(+e.target.value)}>{[.1,.5,1].map(v=><option key={v}>{v}</option>)}</select></label><label htmlFor="tune-rate">Learning rate η<select id="tune-rate" value={rate} onChange={e=>setRate(+e.target.value)}>{[.1,.5,1].map(v=><option key={v}>{v}</option>)}</select></label></div>
    <div className="slider-row"><label htmlFor="tune-steps">Gradient steps <output>{steps}</output></label><input id="tune-steps" type="range" min="0" max="40" step="1" value={steps} onChange={e=>setSteps(+e.target.value)}/><p className="lab-note">Every change recomputes the trajectory from the fixed reference.</p><button className="small-button" disabled={steps===40} onClick={()=>setSteps(s=>s+1)}>Take one step</button></div>
    <div className="tune-insight" aria-live="polite"><p>P(A) = <strong data-tune="probability">{f(end.pA)}</strong> · DPO loss = <strong data-tune="loss">{f(end.loss)}</strong></p><p>Pair-fit probability = <strong data-tune="pair-fit">{f(end.pairFit)}</strong> · KL from reference = <strong data-tune="kl">{f(end.kl)}</strong> nats.</p><p className="lab-note">Pair-fit measures the toy preference label, not factual correctness or the probability of generating reply A. {chosen==='B'?'The label now rewards unsupported claims. A falling loss can make this assistant worse.':'The grounded reply is preferred here, but one pair cannot establish generalization.'}</p></div>
    <div className="tune-chart"><svg viewBox="0 0 520 180" role="img" aria-labelledby="tune-chart-title tune-chart-desc"><title id="tune-chart-title">Probability of reply A over gradient steps</title><desc id="tune-chart-desc">Solid line is the changing policy; dotted line is the fixed reference. Horizontal axis runs from 0 to 40 steps and vertical axis from 0 to 1.</desc><path d="M40 20 V145 H492" fill="none" stroke="var(--line)"/>{[0,.5,1].map(v=><g key={v}><text x="28" y={149-v*120} textAnchor="end">{v}</text><path d={`M40 ${145-v*120} H492`} stroke="var(--line)"/></g>)}<path d={`M40 ${145-reference*120} H492`} stroke="var(--gold)" strokeWidth="2" strokeDasharray="5 4"/><path d={path} fill="none" stroke="var(--accent)" strokeWidth="3"/><circle cx={40+steps*11.2} cy={145-end.pA*120} r="4" fill="var(--accent)"/>{[0,10,20,30,40].map(v=><text key={v} x={40+v*11.2} y="167" textAnchor="middle">{v}</text>)}</svg><p className="lab-note">Solid: policy P(A) · dashed: reference P(A) · x-axis: gradient steps</p></div>
    <details className="workshop-detail"><summary>Trace the scalar update</summary><p>For A preferred, sign = +1; for B preferred, sign = −1. Margin = sign × (θ − θref). z = β × margin. Loss = −log sigmoid(z).</p><p>Gradient dL/dθ = −β × sign × sigmoid(−z). Update θ ← θ − η × gradient. The reference θ stays fixed. Current θ = <strong data-tune="theta">{f(end.theta)}</strong>; current gradient = <strong data-tune="gradient">{f(end.gradient)}</strong>.</p><p>At initialization the policy equals its reference, so margin = 0 and loss = log(2), whatever the initial preference for A. Repeatedly fitting one pair is not a real preference dataset.</p></details>
   </div>
   <div className="workshop-actions"><button className="small-button" onClick={download}>Download training report</button><button className="small-button" onClick={reset}>Reset experiment</button></div>
  </div>
  <div className="print-only"><p><strong>LoRA example:</strong> rank 1 and α = 2 give 8 trainable adapter parameters and 16 frozen base parameters. The hand-set update changes output [1, 0.5, 0, 1] to [1.4, 0.5, −0.2, 1.1]. With B = 0, the update vanishes.</p><p><strong>Preference example:</strong> start at reference P(A) = 0.5, choose A, β = 0.5, and η = 0.5.</p><table><thead><tr><th>Step</th><th>θ</th><th>P(A)</th><th>DPO loss</th></tr></thead><tbody><tr><td>0</td><td>0.0000</td><td>0.5000</td><td>0.6931</td></tr><tr><td>1</td><td>0.1250</td><td>0.5312</td><td>0.6624</td></tr></tbody></table><p>If B is incorrectly preferred, the first step gives θ = −0.1250 and P(A) = 0.4688, while the loss still falls to 0.6624. Fitting a bad label can reward unsupported claims.</p></div>
 </section>;
}
