import {useId,useMemo,useState} from 'react';
import {experiment,MAX_STEPS} from '../lib/unsupervised-learning.mjs';
const pcaResult=experiment('pca');
const printed=[experiment('clusters',3,'spread',1),experiment('clusters',3,'first',1),experiment('clusters',2,'spread',1),experiment('clusters',2,'spread',3)];
const fmt=(n:number)=>n.toFixed(4);
export default function UnsupervisedLab(){
  const [mode,setMode]=useState('clusters'),[k,setK]=useState(3),[start,setStart]=useState('spread'),[weight,setWeight]=useState(1),[steps,setSteps]=useState(0);
  const fit=useMemo(()=>experiment('clusters',k,start,weight),[k,start,weight]);
  const state=fit.trace![Math.min(steps,fit.trace!.length-1)],pca=pcaResult.model!,movies=fit.movies;
  const id='unsupervised-'+useId().replace(/[^a-zA-Z0-9]/g,'');
  const xp=(x:number)=>140+x*38,yp=(y:number)=>412-y*38;
  const reset=()=>{setMode('clusters');setK(3);setStart('spread');setWeight(1);setSteps(0);};
  const download=()=>{const result=mode==='pca'?pcaResult:experiment('clusters',k,start,weight,steps);const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-14-'+mode+'-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="lab unsupervised-lab" aria-label="Unsupervised learning workbench">
    <div className="lab-top"><span className="eyebrow">DISCOVER GROUPS. COMPRESS A REPRESENTATION.</span><span className="lab-tag">Real calculations · fictional movies</span></div>
    <h3>Same movies. Different structures.</h3><p>Nine movies have invented action and humor scores from 0 to 10. There are no supplied cluster labels or viewer-rating targets. Both methods fit this whole small collection for exploration.</p>
    <div className="screen-only">
      <div className="training-controls"><label htmlFor="unsup-mode">Explore<select id="unsup-mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="clusters">K-means · group movies</option><option value="pca">PCA · keep one coordinate</option></select></label>{mode==='clusters'&&<><label htmlFor="unsup-k">Requested groups<select id="unsup-k" value={k} onChange={e=>{setK(Number(e.target.value));setSteps(0);}}><option value={2}>k = 2</option><option value={3}>k = 3</option></select></label><label htmlFor="unsup-start">Initial centers<select id="unsup-start" value={start} onChange={e=>{setStart(e.target.value);setSteps(0);}}><option value="spread">Spread start · fixed rows</option><option value="first">First k movie rows</option></select></label><label htmlFor="unsup-weight">Humor coordinate<select id="unsup-weight" value={weight} onChange={e=>{setWeight(Number(e.target.value));setSteps(0);}}><option value={1}>Original score × 1</option><option value={3}>Emphasize humor × 3</option></select></label></>}</div>
      {mode==='clusters'?<><div className="workshop-actions"><button className="primary-button" disabled={state.converged} onClick={()=>setSteps(n=>Math.min(n+1,MAX_STEPS))}>Move centers and reassign</button><button className="small-button" disabled={state.converged} onClick={()=>setSteps(MAX_STEPS)}>Run to stop</button></div><div className="lab-metrics unsup-metrics" aria-live="polite"><div><strong data-unsup="step">{state.step}</strong><span>Completed update steps</span></div><div><strong data-unsup="inertia">{fmt(state.inertia)}</strong><span>Sum of squared distances</span></div><div><strong data-unsup="groups">{state.clusters_found}</strong><span>Occupied clusters</span></div></div><p className="unsup-status" role="status" data-unsup="status">{state.converged?'Stable assignments after updating centers. This is a stopping point, not proof of a global optimum.':'Initial assignment or intermediate state. Move each center to its current group mean, then assign movies again.'}</p></>:<><div className="lab-metrics unsup-metrics" aria-live="polite"><div><strong data-unsup="variance">{(100*pca.explained_ratio).toFixed(2)}%</strong><span>Variance retained by PC1</span></div><div><strong data-unsup="residual">{fmt(pca.mean_squared_residual)}</strong><span>Mean squared reconstruction distance</span></div><div><strong>2 → 1</strong><span>Original features → stored score</span></div></div><p className="unsup-status">PCA uses the original two scores with equal scale, independently of the clustering settings. It centers the points, learns a direction, and projects onto that line.</p></>}
      <figure className="training-figure"><div className="training-plot-scroll" tabIndex={0} role="region" aria-label="Movie structure chart"><svg viewBox="0 0 700 470" role="img" aria-labelledby={id+'-title '+id+'-desc'}><title id={id+'-title'}>{mode==='clusters'?'Movie clusters and current centers':'PCA projections and discarded detail'}</title><desc id={id+'-desc'}>{mode==='clusters'?'Each numbered circle is a movie; color and the member table identify its current group. Crosses mark current centers. Axes display original feature scores.':'Circles are original movies. Squares are one-component reconstructions on the fitted line. Dashed segments show discarded differences.'}</desc><defs><clipPath id={id+'-clip'}><rect x="140" y="32" width="380" height="380"/></clipPath></defs>
        {[0,2,4,6,8,10].map(v=><g key={v}><line x1="140" x2="520" y1={yp(v)} y2={yp(v)} className="plot-grid"/><line x1={xp(v)} x2={xp(v)} y1="32" y2="412" className="plot-grid"/><text x="126" y={yp(v)+4} textAnchor="end" className="plot-tick">{v}</text><text x={xp(v)} y="432" textAnchor="middle" className="plot-tick">{v}</text></g>)}
        <text x="140" y="20" className="plot-label">Humor score</text><text x="330" y="457" textAnchor="middle" className="plot-label">Action score</text>
        <g clipPath={'url(#'+id+'-clip)'}>{mode==='pca'&&<><line x1={xp(pca.center[0]-20*pca.axis[0])} y1={yp(pca.center[1]-20*pca.axis[1])} x2={xp(pca.center[0]+20*pca.axis[0])} y2={yp(pca.center[1]+20*pca.axis[1])} className="prediction-line"/>{movies.map((m,i)=><g key={m.id}><line x1={xp(m.action)} y1={yp(m.humor)} x2={xp(pca.reconstructed[i][0])} y2={yp(pca.reconstructed[i][1])} className="error-line"/><rect x={xp(pca.reconstructed[i][0])-4} y={yp(pca.reconstructed[i][1])-4} width="8" height="8" className="validation-point"/></g>)}</>}</g>
        {movies.map((m,i)=><g key={m.id}><circle cx={xp(m.action)} cy={yp(m.humor)} r="7" className={'unsup-point group-'+(mode==='clusters'?state.assignments[i]:0)}/><text x={xp(m.action)+10} y={yp(m.humor)-9} className="plot-tick">{i+1}</text></g>)}
        {mode==='clusters'&&state.centers.map((c:number[],i:number)=><g key={i}><path d={`M${xp(c[0])-8} ${yp(c[1]/weight)-8} l16 16 M${xp(c[0])-8} ${yp(c[1]/weight)+8} l16 -16`} className={'unsup-center group-'+i}/><text x={xp(c[0])+11} y={yp(c[1]/weight)+17} className="plot-tick">C{i+1}</text></g>)}
      </svg></div><figcaption>{mode==='clusters'?`Circles = movies; crosses = centers. Axes use original scores; distances in the fit use humor × ${weight}, so screen distance only matches the fit at ×1.`:'Circles = movies; squares = reconstructed points; line = first principal component. Dashed differences are lost when only one coordinate is retained.'}{' '}<span className="mobile-only">{' Scroll sideways to inspect the full chart.'}</span></figcaption></figure>
      {mode==='clusters'?<div className="unsup-members">{state.centers.map((c:number[],j:number)=><div key={j}><h4><span className={'unsup-swatch group-'+j}></span>Cluster C{j+1}</h4><p>{movies.filter((_,i)=>state.assignments[i]===j).map(m=>m.title).join(', ')||'No assigned movies'}</p><p className="local-note">Center in original units: ({c[0].toFixed(2)}, {(c[1]/weight).toFixed(2)}). Cluster numbers are arbitrary.</p></div>)}</div>:<p className="local-note">PC1 direction ≈ ({fmt(pca.axis[0])}, {fmt(pca.axis[1])}); center ≈ ({fmt(pca.center[0])}, {fmt(pca.center[1])}). About 69.97% retained variance does not mean 69.97% recommendation accuracy.</p>}
      <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset exploration</button><button className="small-button" onClick={download}>Download exploration result</button></div>
      <details className="workshop-detail"><summary>Inspect the movie coordinates and results</summary><div className="unsup-table-wrap" tabIndex={0} role="region" aria-label="Movie coordinates and results"><table><thead><tr><th>Point / movie</th><th>Action</th><th>Humor</th><th>{mode==='clusters'?'Cluster':'PC1 score'}</th>{mode==='pca'&&<th>Squared residual</th>}</tr></thead><tbody>{movies.map((m,i)=><tr key={m.id}><td>{i+1}. {m.title}</td><td>{m.action}</td><td>{m.humor}</td><td>{mode==='clusters'?'C'+(state.assignments[i]+1):fmt(pca.scores[i])}</td>{mode==='pca'&&<td>{fmt(pca.residuals[i])}</td>}</tr>)}</tbody></table></div><p>No outcome labels are used. Fit-on-all here describes this collection; it is not a held-out evaluation of future movies.</p></details>
    </div>
    <div className="print-only"><p>Default initialization: k = 3, spread start, original scores. Initial centers are M001, M005, and M009. Initial inertia is 75. After one update, assignments stabilize and inertia is 51.1667.</p><table><thead><tr><th>k</th><th>Start</th><th>Humor scale</th><th>Final inertia</th></tr></thead><tbody>{printed.map(r=><tr key={r.configuration!.k+r.configuration!.start+r.configuration!.humor_weight}><td>{r.configuration!.k}</td><td>{r.configuration!.start}</td><td>×{r.configuration!.humor_weight}</td><td>{fmt(r.state!.inertia)}</td></tr>)}</tbody></table><p>Only compare inertia when feature coordinates and data are the same. The two k = 3 starts reach different local solutions. Requested groups have no supplied “correct genre” labels.</p><p>PCA on the unweighted scores retains 69.97% of total variance in one component. Its mean squared reconstruction distance is 5.7459. Cafe Chaos (2, 9) reconstructs to about (5.6886, 5.5312), showing a meaningful difference that compression discards.</p></div>
    <noscript><p>Enable JavaScript to explore, or use the Python workbook and PDF's fixed comparison.</p></noscript>
  </section>;
}
