import {useId,useMemo,useState} from 'react';
import {dataset,experiment,norm} from '../lib/vector-search.mjs';
const pct=(x:number|null)=>x===null?'Undefined':(100*x).toFixed(2)+'%';
const vec=(v:number[])=>'['+v.map(x=>x.toFixed(3)).join(', ')+']';
const printed=[experiment(),experiment('space','dot'),experiment('space','cosine','raw','probe1'),experiment('space','cosine','raw','probe2')];
export default function VectorLab(){
  const [query,setQuery]=useState('space'),[metric,setMetric]=useState('cosine'),[normalization,setNormalization]=useState('raw'),[mode,setMode]=useState('exact'),[limit,setLimit]=useState('all'),[k,setK]=useState(3);
  const r=useMemo(()=>experiment(query,metric,normalization,mode,limit,k),[query,metric,normalization,mode,limit,k]);
  const id='vector-'+useId().replace(/[^a-zA-Z0-9]/g,'');
  const max=normalization==='raw'?3.3:1.2,px=(v:number)=>70+480*v/max,py=(v:number)=>315-255*v/max;
  const selected=new Set(r.results.map(d=>d.id));
  const reset=()=>{setQuery('space');setMetric('cosine');setNormalization('raw');setMode('exact');setLimit('all');setK(3);};
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chapter-17-vector-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="lab vector-lab" aria-label="Embedding geometry and vector search explorer">
    <div className="lab-top"><span className="eyebrow">COMPARE VECTORS. QUESTION THE NEIGHBORS.</span><span className="lab-tag">Real arithmetic · authored vectors</span></div>
    <h3>Same movies. A different representation.</h3><p>These three-dimensional vectors were chosen by hand. They illustrate retrieval mechanics; they are not outputs of a trained embedding model. Only three preset queries have supplied vectors.</p>
    <div className="screen-only">
      <div className="training-controls"><label htmlFor="vector-query">Preset query<select id="vector-query" value={query} onChange={e=>setQuery(e.target.value)}>{dataset.queries.map(q=><option key={q.id} value={q.id}>{q.query}</option>)}</select></label><label htmlFor="vector-metric">Comparison<select id="vector-metric" value={metric} disabled={mode!=='exact'} onChange={e=>setMetric(e.target.value)}><option value="cosine">Cosine · larger is closer</option><option value="dot">Dot product · larger ranks first</option><option value="euclidean">Euclidean distance · smaller is closer</option></select></label><label htmlFor="vector-normalization">Vector preprocessing<select id="vector-normalization" value={normalization} onChange={e=>setNormalization(e.target.value)}><option value="raw">Original lengths</option><option value="unit">Normalize both to unit length</option></select></label><label htmlFor="vector-mode">Search coverage<select id="vector-mode" value={mode} onChange={e=>{setMode(e.target.value);if(e.target.value!=='exact')setMetric('cosine');}}><option value="exact">Exact · all eligible vectors</option><option value="probe1">Coarse index · probe 1 cell</option><option value="probe2">Coarse index · probe 2 cells</option><option value="probe3">Coarse index · probe all 3 cells</option></select></label><label htmlFor="vector-limit">Runtime requirement<select id="vector-limit" value={limit} onChange={e=>setLimit(e.target.value)}><option value="all">No limit</option><option value="under120">Known runtime below 120 min</option></select></label><label htmlFor="vector-k">Final result slots (K)<select id="vector-k" value={k} onChange={e=>setK(Number(e.target.value))}>{[1,3,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div>
      <p className="vector-policy" role="status">Query vector <strong data-vector="query">{vec(r.query.active_vector)}</strong> · searched <strong data-vector="candidates">{r.index.searched_candidates}</strong> of {r.index.eligible} eligible vectors. {mode==='exact'?'Full scan for the selected comparison.':'Coarse routing uses cosine and fixed, authored centroids.'}</p>
      <figure className="training-figure"><div className="training-plot-scroll" role="region" tabIndex={0} aria-label="Two-coordinate view of three-dimensional vectors"><svg viewBox="0 0 630 370" role="img" aria-labelledby={id+'-title '+id+'-desc'}><title id={id+'-title'}>Two-coordinate view of the movie vectors</title><desc id={id+'-desc'}>Only coordinates one and two are shown. All three coordinates determine scores. Filled circles are returned movies, hollow circles are other eligible movies, gray crosses are filtered movies, and the gold diamond is the query.</desc>
        {(normalization==='raw'?[0,1,2,3]:[0,.4,.8,1.2]).map(v=><g key={v}><line x1={px(v)} x2={px(v)} y1="60" y2="315" className="plot-grid"/><line x1="70" x2="550" y1={py(v)} y2={py(v)} className="plot-grid"/><text x={px(v)} y="339" textAnchor="middle" className="plot-tick">{v}</text><text x="55" y={py(v)+4} textAnchor="end" className="plot-tick">{v}</text></g>)}
        <text x="70" y="27" className="plot-label">Coordinate 2</text><text x="310" y="366" textAnchor="middle" className="plot-label">Coordinate 1</text>
        {r.documents.map(d=><g key={d.id}><title>{d.id+' · '+d.title+' · '+vec(d.active_vector)}</title>{d.eligible?<circle cx={px(d.active_vector[0])} cy={py(d.active_vector[1])} r="6" className={selected.has(d.id)?'vector-point selected':'vector-point'}/>:<path d={`M${px(d.active_vector[0])-5},${py(d.active_vector[1])-5}l10,10m-10,0l10,-10`} className="vector-filtered"/>}<text x={px(d.active_vector[0])+(d.id==='M004'?-32:9)} y={py(d.active_vector[1])+(d.id==='M004'?17:-9)} className="plot-tick">{d.id.slice(1)}</text></g>)}
        <path d={`M${px(r.query.active_vector[0])},${py(r.query.active_vector[1])-8}l8,8l-8,8l-8,-8z`} className="vector-query-point"/><text x={px(r.query.active_vector[0])+12} y={py(r.query.active_vector[1])+6} className="plot-tick">Q</text>
      </svg></div><figcaption>Filled = returned; hollow = other eligible; × = filtered; Q = query. Labels are movie IDs. This view drops coordinate 3 and stretches the axes to fit; do not infer 3D distances from the picture. <span className="mobile-only">Scroll sideways for the full view.</span></figcaption></figure>
      <div className="vector-table-wrap" role="region" tabIndex={0} aria-label="Ranked vector search results"><table className="vector-results"><thead><tr><th>Rank / movie</th><th>{metric==='euclidean'?'Distance ↓':'Similarity ↑'}</th><th>Runtime</th></tr></thead><tbody>{r.results.map((d,i)=><tr key={d.id} data-movie-id={d.id}><td><strong>{i+1}. {d.title}</strong><small>{d.id} · cell {d.cell}</small></td><td data-vector-value>{d.value.toFixed(4)}</td><td>{d.runtime_minutes===null?'Unknown':d.runtime_minutes+' min'}</td></tr>)}</tbody></table></div>
      {r.results.length<k&&<p className="local-note">Only {r.results.length} of {k} slots are filled. A limited probe may leave relevant neighbors in an unvisited cell.</p>}
      <div className="lab-metrics vector-metrics"><div><strong data-vector="neighbors">{pct(r.audit.neighbor_recall_at_k)}</strong><span>Exact-neighbor recall@{k}</span></div><div><strong data-vector="precision">{pct(r.evaluation.precision_at_k)}</strong><span>Relevance precision@{k}</span></div><div><strong data-vector="recall">{pct(r.evaluation.recall_at_k)}</strong><span>Relevance recall@{k}</span></div></div>
      <p className="local-note">Neighbor recall compares with a separate exact scan of the same eligible vectors and metric. Relevance uses Chapter 16's authored labels. The exact audit also scans all eligible vectors, so the candidate count is not a speed benchmark. These selected coordinates do not demonstrate a trained model's quality.</p>
      <div className="vector-baseline"><h4>Keep the keyword baseline visible</h4><p data-vector="bm25">BM25: {r.lexical.results.map(d=>d.title).join(' → ')||'No matches'}.</p><p>Same query, runtime filter, and K. BM25 relevance precision: {pct(r.lexical.evaluation.precision_at_k)}; recall: {pct(r.lexical.evaluation.recall_at_k)}. Its score scale differs from vector similarity.</p></div>
      <details className="workshop-detail vector-cells"><summary>Inspect the cells and exact reference</summary><p>Each movie belongs to the centroid with highest cosine; ties use centroid ID. Query-to-centroid similarity selects the visited cells. Centroids are fixed teaching inputs, not k-means results.</p><div className="vector-table-wrap" role="region" tabIndex={0} aria-label="Coarse index cells"><table><thead><tr><th>Cell / centroid</th><th>Query cosine</th><th>Members</th><th>Visited</th></tr></thead><tbody>{r.index.cells.map(c=><tr key={c.id}><td>{c.id} · {vec(c.vector)}</td><td>{c.query_similarity.toFixed(4)}</td><td>{c.members.join(', ')}</td><td>{c.visited?'Yes':'No'}</td></tr>)}</tbody></table></div><p data-vector="reference">Exact top-{k}: {r.audit.exact_ids.join(', ')||'None'}. Filtered rows can still be listed as cell members; only eligible members are searched.</p></details>
      <details className="workshop-detail vector-values"><summary>Inspect all vectors and source summaries</summary><p>Space ID: <code>{r.space_id}</code>. Each vector has three coordinates, with no intrinsic word or genre labels assigned to individual axes.</p>{r.documents.map(d=><div key={d.id} className="vector-source"><strong>{d.id} · {d.title}</strong><p>{d.summary}</p><p className="local-note">Raw {vec(d.vector)} · raw norm {norm(d.vector).toFixed(4)}<br/>Active {vec(d.active_vector)} · {d.eligible?'Eligible':'Filtered'}</p></div>)}</details>
      <div className="workshop-actions"><button className="small-button" onClick={reset}>Reset vector search</button><button className="small-button" onClick={download}>Download vector result</button></div>
    </div>
    <div className="print-only"><p>Space-rescue query q = [1, 0, 0], original vector lengths, K = 3, no runtime filter. The default cosine order is M004 (Quiet Orbit), M008 (Parallel World), M007 (Unlisted Voyage).</p><table><thead><tr><th>Search</th><th>Results (score)</th><th>Neighbor recall@3</th></tr></thead><tbody>{printed.map((p,i)=><tr key={i}><td>{['Exact cosine','Exact raw dot','Cosine: 1 cell','Cosine: 2 cells'][i]}</td><td>{p.results.map(d=>d.id+' ('+d.value.toFixed(4)+')').join(' → ')}</td><td>{pct(p.audit.neighbor_recall_at_k)}</td></tr>)}</tbody></table><p>Exact-neighbor recall uses each row's own metric as its reference. Exact raw dot therefore gets 100% neighbor recall even though City Sprint (M002) is irrelevant to this intent. Raw Euclidean order is M004, M007, M008. Normalize both query and movie vectors: cosine, dot, and Euclidean rankings agree.</p><p>Cell A contains M004 and M008; B contains M001, M002, M003, M005, M007; C contains M006. Probing A alone misses M007. Probing A+B recovers the exact top three. BM25 returns M008, M004, M005. Authored vectors make the cosine example work; this is not a measured improvement from a trained encoder.</p></div>
    <noscript><p>Use the Python workbook and printable comparison to explore without JavaScript.</p></noscript>
  </section>;
}
