const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{
  const out=path.join(root,'tmp','qa');await fs.mkdir(out,{recursive:true});
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const context=await browser.newContext({viewport:{width:1512,height:1100},deviceScaleFactor:1,reducedMotion:'reduce'});
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4321/chapters/01-what-is-ai/',{waitUntil:'networkidle'});
  await page.screenshot({path:path.join(out,'desktop.png')});
  assert.equal(await page.locator('.chapter-content h2').count(),16);
  assert.equal(await page.locator('figure.diagram svg').count(),6);
  assert.equal(await page.locator('.katex').count(),1);
  assert.equal(await page.locator('.optional-depth').count(),5);
  assert.equal(await page.locator('.optional-depth[open]').count(),0);
  const missing=await page.locator('a[href^="#"]').evaluateAll(as=>as.filter(a=>a.hash&&!document.getElementById(decodeURIComponent(a.hash.slice(1)))).map(a=>a.getAttribute('href')));
  assert.deepEqual(missing,[],'All internal anchors exist');
  await page.getByRole('button',{name:'Search Chapter 1'}).click();
  await page.locator('#search-input').fill('threshold');
  assert.ok(await page.locator('.search-item:visible').count()>0);
  await page.locator('#search-input').fill('zzzzunknowntermzzzz');
  assert.equal(await page.locator('.search-item:visible').count(),0);
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Search Chapter 1'}).click();
  await page.locator('#search-input').fill('Python 3');
  await page.locator('.search-item:visible').filter({hasText:'12. Optional Python lab'}).click();
  assert.equal(await page.getByText('Run this with Python 3; no additional packages or account are needed.',{exact:true}).isVisible(),true);
  const pythonDepth=page.locator('details.optional-depth').filter({has:page.locator('summary',{hasText:'Optional lab:'})});
  await pythonDepth.locator(':scope > summary').click();
  await page.evaluate(()=>scrollTo(0,0));
  await page.getByRole('button',{name:'Switch to dark theme'}).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:path.join(out,'dark.png')});
  await page.getByRole('button',{name:'Switch to light theme'}).click();
  await page.locator('#threshold').scrollIntoViewIfNeeded();
  await page.locator('.lab astro-island').count();
  await page.waitForFunction(()=>!document.querySelector('astro-island[component-export="default"][ssr]')||!!document.querySelector('astro-island[component-export="default"]:not([ssr])'));
  await page.locator('#threshold').fill('0.4');
  await page.waitForFunction(()=>document.querySelector('.lab-metrics strong')?.textContent==='4/4');
  assert.ok((await page.locator('.lab-metrics').innerText()).includes('75.0%'));
  await page.locator('.lab').screenshot({path:path.join(out,'experiment.png')});
  await page.getByRole('button',{name:'Reset to 0.70'}).click();
  assert.equal(await page.locator('.lab-metrics strong').first().innerText(),'2/4');
  await page.locator('.solution summary').first().click();
  assert.equal(await page.locator('.solution').first().getAttribute('open'),'');
  await page.locator('.quiz').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>!document.querySelector('.quiz')?.closest('astro-island')?.hasAttribute('ssr'));
  for(const [i,a] of [1,2,0,1,2].entries())await page.locator(`input[name="question-${i}"][value="${a}"]`).check();
  await page.getByRole('button',{name:'Check my answers'}).click();
  assert.ok((await page.locator('.quiz-actions [role="status"]').innerText()).startsWith('5/5 correct'));
  await page.locator('.quiz').screenshot({path:path.join(out,'quiz.png')});
  await page.getByRole('button',{name:'Mark Chapter 1 complete'}).click();
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('#complete-chapter').getAttribute('aria-pressed'),'true');
  await page.evaluate(()=>document.getElementById('7-worked-example-a-score-becomes-a-decision').scrollIntoView({block:'start'}));
  await page.waitForFunction(()=>document.querySelector('.page-toc [data-section="7-worked-example-a-score-becomes-a-decision"]')?.getAttribute('aria-current')==='location');
  // The cursor position is the behavior under test. Click the visible sticky
  // control without Playwright's automatic pre-click document scrolling.
  const bookmarkButton=await page.locator('#save-place').boundingBox();
  assert.ok(bookmarkButton);
  await page.mouse.click(bookmarkButton.x+bookmarkButton.width/2,bookmarkButton.y+bookmarkButton.height/2);
  assert.equal(await page.locator('#resume-place').isVisible(),true);
  assert.equal(await page.locator('#resume-place').getAttribute('href'),'#7-worked-example-a-score-becomes-a-decision');
  await page.locator('.reader-tools summary').click();
  const downloadPromise=page.waitForEvent('download');await page.locator('#export-progress').click();const download=await downloadPromise;const backup=path.join(out,'progress-backup.json');await download.saveAs(backup);const saved=JSON.parse(await fs.readFile(backup,'utf8'));assert.equal(saved.complete,true);
  await page.locator('#import-progress').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":9}')});
  await page.waitForFunction(()=>document.getElementById('toast')?.textContent?.includes('not a valid'));
  await page.locator('#import-progress').setInputFiles({name:'good.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...saved,complete:false}))});
  await page.waitForFunction(()=>document.getElementById('complete-chapter')?.getAttribute('aria-pressed')==='false');
  for(const bookmark of ['9-real-world-walkthrough-an-incident-report-assistant','9-real-world-walkthrough-a-movie-recommendation-assistant']){
  const legacy={version:1,complete:true,bookmark};
  await page.locator('#import-progress').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});
  await page.waitForFunction(()=>document.getElementById('resume-place')?.getAttribute('href')==='#9-real-world-walkthrough-a-personal-learning-assistant');
  assert.equal(await page.locator('#complete-chapter').getAttribute('aria-pressed'),'true');
  await page.evaluate(p=>localStorage.setItem('ai-handbook-progress-v1',JSON.stringify(p)),legacy);
  await page.goto('http://127.0.0.1:4321/chapters/01-what-is-ai/#'+legacy.bookmark,{waitUntil:'networkidle'});
  assert.equal(await page.locator('#resume-place').getAttribute('href'),'#9-real-world-walkthrough-a-personal-learning-assistant');
  assert.equal(await page.locator('#complete-chapter').getAttribute('aria-pressed'),'true');
  assert.ok(page.url().endsWith('#9-real-world-walkthrough-a-personal-learning-assistant'));
  }
  await page.goto('http://127.0.0.1:4321/curriculum/',{waitUntil:'networkidle'});
  assert.equal(await page.locator('.curriculum-part li').count(),42);
  assert.equal(await page.locator('.curriculum-part small').count(),0);
  await page.screenshot({path:path.join(out,'curriculum.png')});
  const mobile=await context.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.goto('http://127.0.0.1:4321/chapters/01-what-is-ai/',{waitUntil:'networkidle'});
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No mobile body overflow');
  await mobile.screenshot({path:path.join(out,'mobile.png')});
  await mobile.getByRole('button',{name:'Open handbook navigation'}).click();assert.equal(await mobile.locator('#book-sidebar').isVisible(),true);await mobile.keyboard.press('Escape');assert.equal(await mobile.locator('#book-sidebar').isVisible(),false);
  await mobile.locator('.reader-tools summary').click();assert.equal(await mobile.locator('#save-place').isVisible(),true);
  assert.deepEqual(errors,[],'No JavaScript page errors');
  const report={passed:true,headings:16,diagrams:6,curriculumEntries:42,checks:['desktop/mobile rendering','anchors','math rendering','search and no-results state','theme toggle','threshold calculations','exercise reveal','quiz scoring','completion persistence','bookmark','progress export','invalid/valid progress import','mobile navigation'],errors};
  await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
